### ISSUE TITLE
Slow Queries Issue After Upgrading from Version 5.0.0 to 5.0.2

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#10331]
### Describe the issue

I have encountered a substantial surge in slow queries after updating from version 5.0.0 to 5.0.2 (I skipped version 5.0.1). This issue is particularly observed within PostgreSQL 14. I possess several hundred thousand translation text entries within my project. Detailed slow query SQL logs have been included in the attachment. Could you confirm if this is a known issue?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1.Update weblate from Version 5.0.0 directly to Version 5.0.2.
2.Utilize an external repository to upload translation text content.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/c4837b48-6889-4968-bb01-88a29fb027a0)
[das_slowlog_202311021440_pc-6we9dfayz053l2vok.csv](https://github.com/WeblateOrg/weblate/files/13235140/das_slowlog_202311021440_pc-6we9dfayz053l2vok.csv)
[das_slowlog_record_202311021427_pc-6we9dfayz053l2vok.csv](https://github.com/WeblateOrg/weblate/files/13235144/das_slowlog_record_202311021427_pc-6we9dfayz053l2vok.csv)

### How do you run Weblate?

Docker container

### Weblate versions

5.0.2.2

**Comment by nijel** [comment]
The only performance regression I'm aware of was fixed in a92e1049cfdfa4844585af612462fc4e3e0b1245 for the 5.1 release. Can you try upgrading?

Other things you might want to try:

* In case you've performed a PostgreSQL upgrade, running `ANALYZE` on all tables will help a lot. It can help in other situations as well, like after massive removal of rows.
* Some Django versions had bug in creating text field indexes, please see https://docs.djangoproject.com/en/4.2/releases/4.2.6/#bugfixes for info on how to detect these.
