### ISSUE TITLE
GPT MT divergent suggestions

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#10522]
### Describe the issue

I just reviewed some GPT generated suggestions and it looks like GPT has no understanding in the projects' glossary as its using different terms than used before.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Generate a GPT based suggestion for an already mostly translated component.
If you used some special terminology it won't be used for the suggestions.

### Expected behavior

Suggest strings which are more aligned in terms of terminology to the rest of the project.

### How do you run Weblate?

weblate.org service

### Additional context

I'm thinking about some way of feeding some translations back to the query as a reference point while possibly also adding the description of the app for allowing it to better adjust the terminology based on other related translations or just general approach.

**Comment by nijel** [comment]
Weblate will be feeding glossaries to GPT since https://github.com/WeblateOrg/weblate/pull/10516, it is just not yet deployed on Hosted Weblate. You can already configure persona and style in the engine configuration:

![image](https://github.com/WeblateOrg/weblate/assets/212189/61d6a3c4-7304-4dd8-be8d-c4d495e914fa)

For your case, use something like this for persona: You are translating an application for ...

**Comment by yarons** [comment]
This is awesome, so can I create a persona from all my previous translations or do I need to manually type in the rules I follow?

**Comment by yarons** [comment]
I'm not sure how if we can add examples as it's too complicated but sometimes yields the best results.
Thanks.
