### ISSUE TITLE
support parse and download special  language format 

### ISSUE THREAD

**Issue by gs-xpeng** [WeblateOrg/weblate#10669]
### Describe the problem

Our product's language file is designed by developer , we want to support parse and download special language format by ourselves , maybe we can add some script in someways

### Describe the solution you would like

Our product's language file is designed by developer , we want to support parse and download special language format by ourselves , maybe we can add some script in someways

**Comment by nijel** [comment]
My first suggestion would be to use one of the widely used formats instead of inventing the own one.

If you want to use custom format in Weblate, integration needs to be implemented. Look at https://github.com/WeblateOrg/weblate/tree/main/weblate/formats for existing ones. Most of them are based on the [translate-toolkit](https://github.com/translate/translate/) to do the actual parsing of the files. In case your format is similar to something existing, you might add a conversion layer on top of existing format, this is how Excel files are supported based on the CSV format in https://github.com/WeblateOrg/weblate/blob/main/weblate/formats/external.py.
