### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [WeblateOrg/weblate#10714]
### Describe the problem

GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

### Describe the solution you would like

It would be nice if the project's code were moved to GitLab or Codeberg.

**Comment by nijel** [comment]
Thanks for your suggestion, but I don't see an emerging reason to move:

* I don't really see the danger of GitHub being owned by Microsoft.
* We rely on plenty of GitHub features (actions, packages, code scanning) where there might be no matching functionality in the mentioned services.
* GitHub is typically better integrated with third-party services. For example, [PyPI Trusted Publishers](https://docs.pypi.org/trusted-publishers/) only work with GitHub.
* Moving to another service would cost us manpower and money. This includes both one-off tasks of the migration and possibly ongoing effort in case we would have to host (parts of) the service ourselves. I'm pretty sure it is better to invest our (limited) resources into improving Weblate rather than maintaining our infrastructure.

Moreover, both of the services have severe limitations for us:

* Our project most likely cannot be migrated to Codeberg, see https://codeberg.org/forgejo/forgejo/issues/340 (via https://github.com/friendica/friendica/issues/13391).
* We're not acceptable for [GitLab for Open Source](https://about.gitlab.com/solutions/open-source/) as we're selling services.
