### ISSUE TITLE
Project/component removal API/CLI

### ISSUE THREAD

**Issue by murhafh** [WeblateOrg/weblate#1092]
Is there a way to remove a project/component on the server using command line tools? for example using manage.py?
##

**Comment by nijel** [comment]
Not right now.

**Comment by mlachance** [comment]
Considering how large some projects may become (I cannot delete a duplicate because of the size leading to a timeout), it would be helpful to know how to delete a component or delete a project – which files to remove, which entries in the database to delete, and so on. Not just using manage.py, but also how to manually clean up using the normal terminal shell, MySQL queries, etc.

**Comment by nijel** [comment]
BTW: The deletion slowness has been identifies in https://github.com/nijel/weblate/issues/1160 and will be fixed.

**Comment by Jibec** [comment]
hi there, as https://github.com/WeblateOrg/weblate/issues/1160 is closed, I try to comment here.

The deletion process consumes a huge amount of memory and time.

You should try importing and then to remove man pages from this repository: https://gitlab.com/perkamon/man-pages-fr

It will take ages, the uwsgi process will consume more than 2GB of RAM and take more than 30 minutes to finish the job.

It works, but it's really slow ;)

**Comment by nijel** [comment]
Removing from Django UI is slow, because it collects every related object. Weblate disables display of that (see https://github.com/WeblateOrg/weblate/issues/1580) but the collection and permission check is still there (see https://code.djangoproject.com/ticket/10919). 

The UI for removal should be part of Weblate instead of using Django admin interface to avoid that (see https://github.com/WeblateOrg/weblate/issues/2221, which is planned for upcoming 3.3 release).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
