### ISSUE TITLE
Allow disabling the "Other components" box

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#11207]
### Describe the problem

When viewing a component's Overview page, there's always a huge box titled "Other components" at the bottom of the page, which shows other components from the same project. The number of components shown was limited to 10 (#4220), but that is still a lot of information that is not directly relevant to the component the user wanted to view.

I suppose the idea is similar to recommendations shown in online stores ("You might also like..."), but I'm not convinced that the benefits outweigh the visual clutter. It's also a question of philosophy: do we believe that sending translators down random rabbit-holes results in good translations? Maybe, but I would argue for better supporting intentional navigation and context-awareness instead.

### Describe the solution you would like

I would be fine with removing the Other components box altogether, but in case others find it useful, an option for administrators to enable or disable it would be a good compromise. (Or alternatively, an option for each user's personal configuration.)

**Comment by nijel** [comment]
> It's also a question of philosophy: do we believe that sending translators down random rabbit-holes results in good translations?

For projects with a dozen of components, it's not really sending to a random rabbit-hole, but showing other parts of a project the user might want to translate (for example at https://hosted.weblate.org/projects/weblate/application/cs/).

For projects with many components (let's say https://translations.documentfoundation.org/projects/libo_help-7-6/auxiliary/cs/), it indeed is not that useful because there is no reasonable selection of which components are shown.
