### ISSUE TITLE
Enforced 2FA

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#11341]
### Describe the problem

Once we have https://github.com/WeblateOrg/weblate/issues/1681 implemented, there should be a way to enforce 2FA for certain contributors.

### Describe the solution you would like

* Add option to Teams to require 2FA
* Add option to Project to require 2FA

This way we can cover both site-wide setups (requiring 2FA for Users group) and per project settings.

**Comment by raphaelm** [comment]
Sounds great!

**Comment by NameLessGO** [comment]
Will 2FA be mandatory or opt-in for [Administration role](https://docs.weblate.org/en/latest/admin/access.html#list-of-built-in-roles)?

Since it is an OP role, being mandatory makes sense for account protection/security (+1)

however there will be users that won't be satisfied with it, although in GitHub case, it was 2FA Mandatory **for every contribuitor**: https://github.com/orgs/community/discussions/63813

Thoughts about it?

**Comment by nijel** [comment]
It will be configurable in Weblate. For Hosted Weblate service, we've not yet decided the actual policy.
