### ISSUE TITLE
Commit translations per author

### ISSUE THREAD

**Issue by rvanlaak** [WeblateOrg/weblate#1157]
### Actual behaviour

If you are translating with multiple people and execute the Weblate commits manually, you will get lots of commits. Especially if you have one file that needs translating by multiple users.
### Expected behaviour

If I'm correct there was an option to make one commit of all translations, but what I'd like to see is having one commit per user. So, when 5 translators are translating at the same time this then would only result in 5 commits at most.
##

**Comment by nijel** [comment]
Weblate currently does no reordering of changes, so once another user starts translating, it has to commit changes done so far.

PS: See also https://github.com/nijel/weblate/issues/126

**Comment by rvanlaak** [comment]
Wouldn't it then be better to start by merging changes to multiple files in one commit? So if one translator works on four components, make one commit for all these changes. That would already save a lot of commits.

**Comment by nijel** [comment]
Yes, that also could be implemented :-).

**Comment by nijel** [comment]
As for multiple files in one commit it will get tricky with commit messages as they are currently composed per translation. (see also #1248)

**Comment by rvanlaak** [comment]
For me personally I don't mind that the commit messages will look ugly. It could be comparable to the merge message, it is subservient to grouping the translation work. In our scenario, one user is working on one file, e.g. `admin.fr.yml`, and the developer only adds translations to `admin.en.yml`. 

So creating as few commits as possible would be great, because that groups together editing history in Git, and allows us to easily debug translations when we annotate the translation files. 👍

**Comment by nijel** [comment]
What I think should be doable with current code:

- do not force commit when other user starts translating
- on editing ensure that pending flag is not present, otherwise force commit of pending changes (at least for this author, but it's probably cheaper to commit everything in this case)
- the commit would go though all pending units, group them by author and sort by last edit date, then it would create separate commits for each author (the author and timestamp are already available in the changes model)
- what needs to be decided is how to handle committing of pending changes as current approach might lead to quite huge amount of pending translations with this reordering in place

**Comment by rvanlaak** [comment]
Great news! 👍 

That would mean that "translation sessions" will end up in just a couple of commits, and we can keep track of when batches of translations were done.

Maybe we would eventually even have a cronjob that does run daily to commit and push.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
