### ISSUE TITLE
Check language when adding new translation

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1172]
Currently Weblate happily adds any new language which user chooses. It might do some validation whether adding such language makes sense.

For example adding zh_Hant/zh_Hans when zh_TW/zh_CN already exists is not really expected.

I'm not sure if there are other such examples.
##

**Comment by stanislav-brabec** [comment]
Adding {language}_{COUNTRY} if the {language} does not exist, with exception of:
zh_{COUNTRY} is permitted, zh does not exist at all.
pt_BR is permitted, even if pt does not exist.
(And maybe others.)

**Comment by nijel** [comment]
What is wrong in using country specific codes from beginning? It probably is good idea for software, but when translating book, the choice for specific locale seems reasonable (eg. https://debian-handbook.info/contribute/).

**Comment by marcperrin** [comment]
Yeah I don't think there is anything wrong with directly using fr-FR instead of fr. 
Some people like to have a nice hierarchy for fallback reasons, but in some industries (at least some common workflows in said industries...), using a country-less code looks downright outlandish.

**Comment by stanislav-brabec** [comment]
> Yeah I don't think there is anything wrong with directly using fr-FR instead of fr.

In almost all cases it is wrong to use fr_FR instead of fr for translation!

If you use fr_FR, users of fr_BE, fr_CH and fr_LU locales will not see your French translation. By using of fr_FR for translation, you explicitly say: This translation is intended only for French speaking people in France and nowhere else.

If there are strings exclusively intended for French in France, it makes sense to create two translations: fr for generic part of the translation, and fr_FR for strings exclusive to France. (Well, in this case, some Weblate features will not work best, but it is still possible to do it.)

**Comment by nijel** [comment]
@stanislav-brabec you see this too much from a Gettext world where it indeed works like you describe, but there are different solutions which do not have such fallbacks and choose locales differently.

Also see https://github.com/nijel/weblate/issues/1172#issuecomment-233636629 where I've mentioned another case where it makes perfectly sense to specify locale completely. When translating book, you don't need fallbacks, but you need to specify which exact locales are you using, so that all translators are on the same line.

**Comment by Artoria2e5** [comment]
Adding a worse example here: `zh`.
