### ISSUE TITLE
Allow to disable Autosave in Zen mode

### ISSUE THREAD

**Issue by yfdyh000** [WeblateOrg/weblate#1187]
### Steps to reproduce
1. Enter the translation interface, and Zen mode.
2. Modify a translation.
3. I want to copy another content on the page, e.g. a part of the original string.
### Actual behaviour

The translation of semi-finished are submitted and stored.
### Expected behaviour

Like a Autosave checkbox on the page, and "Save" & "Save All" buttons if the Autosave is disabled.
### Server configuration

Please paste the output of command `./manage.py list_versions` over here
##

**Comment by nijel** [comment]
Few years later, I'm still not convinced this is a good idea.

In your use case, once you modify the translation it would be saved and then you would be able to turn off the autosave. You would copy the string and then again enable autosave. I don't think that partial saved translations do any big harm. Give that nobody else commented on this issue since it's creation, it seems that nobody else cares about this as well.
