### ISSUE TITLE
New check: File is no longer on master repository

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#1200]
First of all, thanks for all the great work!

I would like to suggest a new feature: a check.
### Steps to reproduce
1. Configure a component
2. Delete it from master
3. You still have a component in weblate, and translators waste a bit of work.
### Actual behaviour

It would be great if there is some sort of 'no longer on master repo' check.
##

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported was fixed by 394b304b56d5b5824db2acbc4a23950620f65bdd. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
