### ISSUE TITLE
Check strings using dennis

### ISSUE THREAD

**Issue by jayvdb** [WeblateOrg/weblate#1252]
[dennis](https://pypi.python.org/pypi/dennis) ([github](https://github.com/willkg/dennis)) provides some linting of translation strings.

https://github.com/phpmyadmin/localized_docs/pull/2 shows some of the problems which can be caught either at the initial data entry, or maybe weblate should allow the problematic translation to be saved and then include these strings in the "Strings to check" UI.
##

**Comment by nijel** [comment]
Weblate does already have it's own checks framework (which in some things overlap with dennis). I'm not really sure how to mix these together. Weblate checks do rely on the database as well to get some metadata or to look at other translations in same project...

Also some checks are intentionally not there (URL difference) as this is really something for manual review rather than automated check. For example it is perfectly okay if `https://docs.phpmyadmin.net/en/latest/` is translated as `https://docs.phpmyadmin.net/pt_BR/latest/`.

Checking rst syntax is definitely something we lack right now, but that does not seem to be existing in dennis as well.

**Comment by jayvdb** [comment]
I've created two `dennis` bugs about the main problems you've identified.

Allow translated URLs is https://github.com/willkg/dennis/issues/80 
RST syntax support is https://github.com/willkg/dennis/issues/81

However even without those fixes, most `dennis` errors could be warnings in weblate that a human should review.

It would be good if the validation of translation messages is done in an external package, which can be used outside of weblate.  If not `dennis`, perhaps another one?  translate-toolkit? (does weblate use the [pofilter tests](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/pofilter_tests.html) ?
 
Or maybe the existing weblate checkers can be separated from the webapp into a new package?  So then a linter CLI can be wrapped around them.

**Comment by nijel** [comment]
Weblate uses separate set of checks and does not use pofilter ones. The reason was that in time I wrote this, several checks there were broken in way I didn't want to use them and they didn't accept contributions back then (PRs were stuck for year or so). That's why I've written own framework what allowed us to use database stored metadata.

The database access is one of things where Weblate checks do not fit into other modules, but maybe the code could be written in a way usable in Weblate and separately as well.

**Comment by willkg** [comment]
If it helps, Dennis is both a commandline as well as a library. I built it with the intention that it'd be used by other systems. I had similar issues with pofilter and translate toolkit which pushed me into writing Dennis.

**Comment by nijel** [comment]
Going though old issues and I'm still not sure this is good idea. However the main question before I start considering this again is: Is Dennis still maintained? Last commit seems to be more than one year old...

**Comment by willkg** [comment]
Dennis is still maintained. It hasn't had a release in a while because not much work has been done on it. It pretty much does what it needs to.

If there are things you're interested in working on, I'm happy to review PRs.

**Comment by nijel** [comment]
I finally found some time to look at Dennis and I don't think it's much useful for Weblate:

* It supports only python-format and python-brace-format, while Weblate already supports [much more variants](https://docs.weblate.org/en/latest/user/checks.html#formatted-strings
* There doesn't seem to be anything which already not covered by Weblate for the translations
* It seems to be bound only to PO files, pulling in polib as a dependency

On the other side, it has some [useful source checks](https://github.com/willkg/dennis/blob/master/dennis/templatelinter.py) which we do not have right now.
