### ISSUE TITLE
Improve lazy commit algorithm to commit all pending changes of a given user

### ISSUE THREAD

**Issue by rhertzog** [WeblateOrg/weblate#126]
Hi Michal,

When you use lazy commits, you obviously want to limit the number of commits appearing in the Git history. The current algorithm is not  optimal. Currently it commits the changes on a .po file as soon as someone else starts to work on it.

When this happens, it should not commit only the changes on that .po file but all the pending changes of that user, even on other files. The logic is that once you decided to create a commit for a user, you should try to put as much changes as possible in that commit.

Then I have the feeling that there's a bug that forces some commits too early, like when the same PO file of another language changes but I'm not sure. It's worth double checking though.
##

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by adding support for squashing git commits per autho, see #2102 for more details.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
