### ISSUE TITLE
Check if translated according to glossary

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1297]
Quality check which would fail if word from glossary is not translated as is in glossary. This could help keeping consistency.

Related to #701

**Comment by tjhietala** [comment]
This would cause a lot of false positives in languages that use inflections a lot, such as Finnish.

**Comment by tjhietala** [comment]
Also, glossary entries may need to include explanatory text, esp. as long as #1718 is not implemented.

**Comment by mayeulk** [comment]
@tjhietala Could we think about having in the glossary, next to the translated word and [comment](https://github.com/WeblateOrg/weblate/issues/1718), a regular expression to be checked against? This would work in the few languages that I know (French, Spanish, English, Italian, Portuguese, German). For instance:
Source: Armed conflict
Spanish: conflicto armado
Spanish regex: conflicto* armado*
Italian: conflitto armato
Italian regex: conflitt* armat*  (because plural is conflitti armati)

In addition to wildcard, one could even go further with alternatives:
mouse|mice

Hope this helps. Cheers!

**Comment by tjhietala** [comment]
Finnish inflections are a bit more complex than that, and we shouldn't assume translators are regex wizards. I think the Finnish language tool [Voikko](https://github.com/voikko) (and similar tools for other languages) could be used, but I don't know how much work it would take to integrate it with Weblate.

Perhaps this feature should be enabled by default only for whitelisted languages?
