### ISSUE TITLE
Permalink copy does not work in Zen mode

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#13074]
### Describe the issue

Clicking on permalink icon in zen mode should copy the link, but instead it follows the link.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to zen mode (for example https://hosted.weblate.org/zen/weblate/legal/cs/?offset=1&)
2. Click on copy permalink icon

### How do you run Weblate?

weblate.org service

**Comment by meel-hd** [comment]
@nijel can you double check again. I have just tried it and it seems working fine. Maybe there is some inconsistency with the html template and the cached javascript since the last update that changed `data-*-text` attributes. 
![image](https://github.com/user-attachments/assets/edfea14b-c705-4925-afff-4d7dea59177c)

Try hard clearing cache by:
- opening dev tools.
- then right click on the refrech icon and choose Empyt Chach and Hard Reload, and see if the issue persists.
![image](https://github.com/user-attachments/assets/f4281a0f-01f5-48b5-babc-aae576500773)

**Comment by nijel** [comment]
Just tested it, and it works for the first page, but it doesn't work on the next page of strings once it is loaded.
