### ISSUE TITLE
Glossary changes not reflected in machinery results

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#13122]
### Describe the issue

The machinery caching does not include glossary state for backends utilizing it. That can lead to showing outdated results in automatic suggestions.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Install machinery service supporting glossaries.
2. Create a glossary entry for a term used in a string
3. View automatic suggestions on that string
4. Change the glossary term
5. View automatic suggestions on that string again

### Expected behavior

The automatic suggestion should reflect glossary changes.

### How do you run Weblate?

Git checkout

### Additional context

`get_cache_key` for `GlossaryMachineTranslationMixin` should include a glossary checksum, most likely logic from `get_glossary_id` should be extracted and reused here.

**Comment by AdamGerthel** [comment]
Is this fixed in 5.9 as well or only 5.10+?

**Comment by nijel** [comment]
It was fixed for 5.9 as you can see from the issue milestone.

**Comment by AdamGerthel** [comment]
> It was fixed for 5.9 as you can see from the issue milestone.

Thanks for confirming 🙏

I wasn't sure because the reason I found this issues was because I was trying to figure out how to refresh the automatic translation after having updated the glossary, but it seems I must've been mistaken and that it had already been refreshed. I noticed in other instances that it worked as expected.

Perhaps an option to manually force a refresh (per service) under the automatic translation tab? And perhaps a way to add context on component level or even string level? Anyway, those are feature request that are bit beside this topic...
