### ISSUE TITLE
Needs review and fuzzy confusion

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1314]
Since 91895e53843ba541750e2c827fa15babd8bfff43 we label "fuzzy" strings as marked for review. This was probably not a good move as it adds further level of confusion. Some feedback I got:

> Could you consider adding a note next to the 'needs review' checkbox, indicating that 'needs review' also necessarily means that for all practical purposes, such messages are considered untranslated. I.e. the program will not use them.
> 
> Currently, translators may think of 'needs review' as an administrative setting, for personal use or communication with other translators, and without further consequences. And then wonder why their hard work doesn't end up in their favorite program...

What we probably need is separate flags for following situations:

* The string was fuzzy matched and needs proper translation
* The string needs review, but is properly translated

Mapping these two should be different based on file format:

* Gettext `fuzzy` should be flagged as `fuzzy matched`
* Qt TS `unfinished` should be flagged as `fuzzy matched`
* XLIFF without `approved="yes"` should get into `needs review`
* Weblate own tracking changes on monolingual strings should get `fuzzy matched`

Open questions:

* Should there be way to manually set `fuzzy matched` on translation? I sometimes use it for situations where I found string which is translated wrongly, but can not fix it (eg. I don't understand the language).

Related issues:

* https://github.com/WeblateOrg/weblate/issues/1073 - support for traditional review-based workflow
* https://github.com/WeblateOrg/weblate/issues/1203 - Feature: Reviewer can review only other people's translations
* https://github.com/WeblateOrg/weblate/issues/1033 - Allow mark 'review' for string of second languages in translate interface
* https://github.com/WeblateOrg/weblate/issues/756 - Ability to flag canonical texts for review
* https://github.com/WeblateOrg/weblate/issues/1081 - All translations were marked as fuzzy after reload

**Comment by daniele-athome** [comment]
I don't know if it's related to this problem, but I got a weird behaviour with version 2.10 today:

* a user modified a source string
* all other languages got marked as review (and that's ok)
* I reverted the source string modification because it was a mistake
* the other languages were not marked as review anymore if I open the single string, however language overview still had "Strings needing review" with "1". If I clicked it, it said no strings needed review (WTH?!?)

Looks like a bug to me (nothing really serious, if I manually mark the string as "need review" and back again, the problem goes away, still I have I to do that manually for 14 languages :-), but I don't know if it's worth to open a new issue given what I'm reading here in this issue.

**Comment by nijel** [comment]
@daniele-athome Can you please open separate issue on that? It's probably some caching issue.

**Comment by daniele-athome** [comment]
Sure: #1326.

**Comment by nijel** [comment]
I quite like using "needs edit" instead of fuzzy as suggested in https://github.com/WeblateOrg/weblate/issues/1616#issuecomment-326946263

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
