### ISSUE TITLE
How I can clone repository from the weblate to resolve conflicts

### ISSUE THREAD

**Issue by AlexMost** [WeblateOrg/weblate#1340]
Recently I had conflicts in .po file on the weblate server. I tried to follow this article https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations
but I can't realize how to get proper url for the component, to be able to clone it. I have added `weblate.gitexport` to INSTALLED_APPS and see 'Exported repository URL' setting in the admin interface.
My weblate host is http://weblate.dev-cluster.uaprom. I have set exported repository url to `http://weblate.dev-cluster.uaprom/git/uaprom-vas/vas-frontend` and tried to clone it with:

```sh
git clone http://weblate.dev-cluster.uaprom/git/uaprom-vas/vas-frontend
```
I guess I am missing something from the documentation, can someone help me?

**Comment by nijel** [comment]
The setting is always there, with gitexport installed, the URL is automatically generated and you should not edit it. However the URL you've mentioned looks correct, is there something in the server logs? Maybe the git-http-backend can not be found on your server. The path was hardcoded in 2.10 release, the discover has been added later in 952bbb0a3259eaf1acc750cfbf70c3dc957e13d6.

**Comment by AlexMost** [comment]
I have added gitexport app only after the component was created, so maybe that is the reason

**Comment by nijel** [comment]
It should add the correct URLs on database migration (but you have to execute it after adding it, this should be probably mentioned in the docs...)

**Comment by rzeznik-kasia** [comment]
@nijel I have the same issue but no migration is needed because 'gitexport app' is in use already.
I did:
`git remote add iotweblate https://my.weblate.host/git/iot/main/`
and after:
`git remote update`
in console I've got:
`fatal: https://my.weblate.host/git/iot/main/info/refs not valid: is this a git repository?`
In other tools when i try to do the same I got:
`invalid Content-Type: text/html; charset-utf-8`
When I entered `'https://my.weblate.host/git/iot/main/info/refs'` in the browser its looks ok because it prints:
```

<commin-id>	refs/heads/weblate
<commin-id>	refs/remotes/origin/weblate
<commin-id>	refs/tags/1.10.0
<commin-id>	refs/tags/1.10.0^{}
```

Git clone produces same behaviour. On the other mashines there is the same bahaviour.
I've also tried
`git remote add iotweblate 'https://user:token@my.weblate.host/git/iot/main/'` and (un)suprisingly there is the same behaviour.
Anyone has the same issue?
