### ISSUE TITLE
Inflexible current vcs workflow

### ISSUE THREAD

**Issue by pchinery** [WeblateOrg/weblate#1358]
We have decided against weblate pushing commits to our developer branch directly, as this results in a large amount of commits and download the translations in our build script instead. This leads to a problem for us. As we need to update all languages with msgmerge whenever we add a translation, we regularly have to update all translations inside a commit. As weblate is not allowed to push, it creates a lot of commits that will never be pushed, but they yet create merge conflicts. This results in weblate not being able to have the latest translations once we have reached this situation.

The question now is how we could tackle this. The main problem probably is that we are not using the intended workflow. In a perfect world, different workflows would be possible.

One option we are looking into is to have a seperate branch for translations, where weblate would be allowed to push and update it when needed. Thus, we would be able to resolve merge problems locally. This does not work at the moment due to #1357

Otherwise, it would probably make sense if weblate could update the translations when changes on the pot files are detected. As this is the root of all these problems, that would probably be the best solution. I know that it was discussed before and considered to take place outside weblate, but I really think that weblate should be aware of what is supposed to be translated instead of relying on the actual translations that are already present.

Many thanks in advance for all opinions and discussions!

**Comment by nijel** [comment]
The problem is that in most cases people do not even update pot files and want *that* to happen magically. Anyway I've always thought that most of the frameworks do update pot and po at the same time.

Currently the best approach to avoid merge conflicts is documented here: https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts

In case you want to manually merge the po files, you can also reset the weblate repository after changes.
