### ISSUE TITLE
Strings requires action also includes translated strings

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#1491]
### Steps to reproduce
1. Follow this link: https://hosted.weblate.org/translate/weblate/master/he/?type=todo

### Actual behaviour
I'm seeing 349 strings instead of 23 like the main activity screen shows.

### Expected behaviour
I should see only the strings I want to work on without translated strings.

### Server configuration
This is on hosted weblate and it happened May 19th.

**Comment by nijel** [comment]
It works as expected for me. Did you happen to work on the translation before, when there were much more strings to translate? The list of matched strings is cached in order to allow navigation back while translating, so probably old list was used in your case. Probably we should avoid using cache in case the offset is not specified...

**Comment by yarons** [comment]
Yes, that's exactly the case, thank you.
