### ISSUE TITLE
No way to disable acl

### ISSUE THREAD

**Issue by jmaxxz** [WeblateOrg/weblate#1615]
### Steps to reproduce
1.  Enable ACL on a single project
2.  Disable ACL on project

### Actual behaviour
All projects use project specific group ACLs members of Users group can no longer access any project.

### Expected behaviour
Projects without "Enable ACL" checked should be accessible to all users with `trans | Project | Can access project` permission

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

 * Weblate weblate-2.8-3558-g42a9039
 * Python 2.7.12
 * Django 1.11.4
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.6.4
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.9.1
 * hub 2.3.0-pre9
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
Indeed the current code really doesn't handle removal of the groups:

https://github.com/WeblateOrg/weblate/blob/60251e081a09bd809604e40482363c45f2aed0c5/weblate/trans/models/__init__.py#L245-L275

On the other side, it was supposed reset the Group ACL filtered permissions, so the project should be accessible after disabling it. However looking at the docs, the set method doesn't not delete extra ones by default, so that's something to fix...

Anyway long term plan is to make this more flexible, see https://github.com/WeblateOrg/weblate/issues/1434.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jmaxxz** [comment]
Still having issues after applying 946a1bd if I disable acl on a project I still need to have a group acl for that project. Members of user group are still unable to access project.

**Comment by nijel** [comment]
The GroupACL should be always there, it just should not filter access to the project just the administrative tasks....

**Comment by nijel** [comment]
...and it really works like that in my testing (I've also added unittest to cover this).
