### ISSUE TITLE
Automatic creation/deletion of Components

### ISSUE THREAD

**Issue by uhon** [WeblateOrg/weblate#1667]
Thanks for the awesome Tool, which we want to use to improve our companies translation-process towards Continuous Translation.

We work with a Git-Flow approach, having short living feature-branches which get merged back into development branch after review, testing and translating.

After evaluating Weblate (dockerized setup) for our needs, it remains still unclear how we would implement automatic Component creation (for new feature-branches) in the most efficient way.

It is tedious to set up a new component in the Web-UI for every feature-branch we start working on, so we are looking for a way to automate this.

Unfortunately the WEB-API doesn't allow to create components (https://github.com/WeblateOrg/weblate/issues/1225). What is the reason behind this?

Github Web-Hooks can only be used to update components, but won't create new ones.

The only achievable way we found is to use manage.py (rsp. weblate alias in docker container) to create components via "import_json" command. "import_project" does not work for us, since it has too few configuration options.

Using manage.py to automatically create components looks a little strange to us. Needing to have our CI-Server to call Weblate via SSH to execute configuration within a named docker-container isn't the most elegant solution to go with.

Did we overlook something? Might there be a better way to achieve this? If not, are there plans to implement component-creation/deletion in a different way?

Thanks.

**Comment by nijel** [comment]
Yes, the API is missing this because nobody did implement it. And it's probably best way to deal with various setups like your. It should not be that hard to implement https://github.com/WeblateOrg/weblate/issues/1225, just somebody needs to find time for that or pay somebody to find time for that ;-). Actually it should work pretty out of the box with rest framework we're using it just needs proper testing if that doesn't break anything.

There is also https://github.com/WeblateOrg/weblate/issues/802 covering automatic discovery (but that mostly covers files in existing repo, not branches you want to handle).

Anyway I'm closing this in favor of #1225.

**Comment by ilocit** [comment]
We think this is a great request and would be willing to sponsor this. Please contact us if the interest is still there.
