### ISSUE TITLE
Enabling ACL for a project  blocks the acces of ACL group with permissions for it

### ISSUE THREAD

**Issue by MirabelaBiciin** [WeblateOrg/weblate#1687]
Hi, 
I try to limit the users access to a certain language for all projects. I created  an ACL group for which I selected a group, a language and some permissions like: access project, save translations, add translations etc. I didn't select a project and a subproject which means the users of my ACL group will have access at all projects and components but for the selected language. When I enable the ACL for a project, the users of my ACL group can not access that project. It would be great if you could help me to understand what is the problem. Maybe I don't configure it well or it's a bug. Thank you for your work. Have a nice day!

**Comment by nijel** [comment]
Currently there is no easy way to setup per language access control.

**Comment by lawmaestro** [comment]
This is also something I tried setting up on our project recently as we were looking for per language access control. This would be a good addition to the ACL feature.

**Comment by nijel** [comment]
Since 5193d8f4f284765b194ebcdfde8fc6f4679914be it is possible to switch off access management in Weblate (so that it will not mess up with GroupACL) and define completely custom access levels in Django admin interface. The drawback is that you will have to manage everything in Django admin interface, the user management in Weblate will be disabled in this case.

I know this is not perfect solution, but at least it allows people to create custom access levels without Weblate interfering.

**Comment by nijel** [comment]
Besides the mentioned workaround, I think it's time to get rid of current permission management in favor of something what will better fit Weblate needs, see #1798

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by merging https://github.com/WeblateOrg/weblate/pull/2002.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
