### ISSUE TITLE
Cannot upload offline translation file

### ISSUE THREAD

**Issue by eakkas** [WeblateOrg/weblate#1690]
### Steps to reproduce
1. Download XLIFF file for offline translation
2. Translate file
3. Try uploading the file back into the system

### Actual behaviour
I receive an error - File content merge failed: 'xliffunit' object has no attribute 'value'
This error message comes up even if I try to upload the file that I just downloaded, without making any changes
https://goo.gl/QJDZ27

### Expected behaviour
Offline translations should be imported and merged

### Server configuration
Running Weblate 2.18 on ubuntu 12.10
Note that list_versions does not seem to be available in manage.py anymore

**Comment by nijel** [comment]
What file format was the translation using originally?

PS: list_versions is still present, there was no change in this.

**Comment by mbieren** [comment]
I have the same problem while reloading a prev. exported file with weblate. Weblate 2.17.1 and the following error message "File content merge failed: 'xliffunit' object has no attribute 'value'"

**Comment by nijel** [comment]
My answer is still the same: What file format was the translation using originally?

**Comment by mbieren** [comment]
If you mean that I have to execute ? (Otherwise how do I find out)

$  python manage.py list_versions
 * Weblate 2.17.1
 * Python 3.5.2
 * Django 1.11.8
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Nevermind, I probably found the problem. It would be great if you can test whether the patch really fixes your issue.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mbieren** [comment]
We are stuck with version Weblate 2.17.1 so I merged yout fix into that. The problem still exists. I have to select "Import as string needing review" or "Import as translated"

**Comment by nijel** [comment]
What file format is your translation using natively? I understood that you're downloading it converted to XLIFF and then try to upload back, rigth?

**Comment by mbieren** [comment]
My fault your fix is working. I was using weblate with gunicorn and forgot to reload. Sorry for that

**Comment by nijel** [comment]
Great :-)
