### ISSUE TITLE
summary and database are not in sync

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1704]
Database and untranslated summary can be out of sync. Similar problem was first seen in weblate-2.6, then these discrepancies disappeared after upgrade to 2.13.1. The currently reported problem appeared first in 2.13.1, and did not disappear after upgrade to 2.17.1. I tried rebuild_index --all (in 2.13.1) and it did not help.

### Steps to reproduce
1. Go to https://l10n.opensuse.org/projects/zypper/master/cs/
2. Click to "Not translated strings: 1 (3 words)"

### Actual behaviour
No string matched your search!

### Expected behaviour
Summary matching the database.

### Server configuration
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.6.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
The index rebuild is not related to this, it just rebuilds fulltext index.

I remember fixing few such issues in last months, so yes, it could happen. I've now found 26c2eedcb6fadbcda34b01cdaebc8b672ab6f856, but I think there were more related changes.

The state should be fixed by `./manage.py fixup_flags --all`, but that will take quite some time, so you might rather run in only selected projects...

**Comment by stanislav-brabec** [comment]
I just called
./manage.py fixup_flags zypper/master
Operation completed, but the inconsistency remains.

**Comment by burner1024** [comment]
probably related to caching? #1561

**Comment by stanislav-brabec** [comment]
@burner1024 It does not look so. I do not have redis caching defined. My settings.py uses default setup here.

**Comment by nijel** [comment]
Some of the stats are stored in the database (see https://github.com/WeblateOrg/weblate/issues/1705), so that's where the inconsistency is. This was bad design decision in the past and should be addressed for next release.

Anyway I've just committed aad42b6b6 to make fixup_flags update stats in all cases, previously it was easy to miss the update in case none of the units had needed flags set.

**Comment by stanislav-brabec** [comment]
The upper mentioned inconsistency disappeared by itself even without applying the patch.

I recovered my old snapshot of the database into my staging instance. I was again able to reproduce. Then restarted server, called fixup and restarted server again to verify that it does not help. Then applied the patch and repeated the same fixup procedure again. Now it is fixed in the testing instance.

Thanks.
