### ISSUE TITLE
Weblate 2.19-dev - Parts of the UI are in english

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#1766]
See screenshot : in this screen at least 3 parts of the UI which were available in french are now displayed in english ;-(.
![translation broken](https://user-images.githubusercontent.com/1452146/34314261-06bc7bd8-e772-11e7-909b-bae173586f64.jpg)

**Comment by nijel** [comment]
Indeed the translations are not yet there as we had some proofreading of the English strings (see recently closed pull requests). I was waiting for this to complete before pushing updates to translators, but this was now done in 0102691115dc559cfdf7fbbf1b64a42e9951dea2.

**Comment by ldmpub** [comment]
Hi,

Thanks for you quick response. I should recognize that I'm surprised / lost:
1. some strings are still in english in french screens
2. a lot of translations have to be reworked in french
3. some of these strings have lost their history (which were previously OK) : see for instance https://hosted.weblate.org/translate/weblate/master/fr/?checksum=99b3a76a52492ab5

Can you please give me some explainations?

**Comment by nijel** [comment]
Many strings have been reworded in English, meaning they are now different source strings.

You can see the changes here: https://github.com/WeblateOrg/weblate/compare/586b19c7bc7379fab6ec95bdfbd7f02723d780f3...69dadaefe70d6ae631c82cc71d9d0ee00f245817

I've decided to let the translations be reworked as meaning of many of the English sentences could have been confusing and I have no clue whether the translator did pick up the right meaning.

The string you're mentioning used to be "Good translations" and now is only "Good", that's why it has no history: https://github.com/WeblateOrg/weblate/compare/586b19c7bc7379fab6ec95bdfbd7f02723d780f3...69dadaefe70d6ae631c82cc71d9d0ee00f245817#diff-61eb03060d7d7defa4ef10ba9e5ea2a6L5
