### ISSUE TITLE
Share a component

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#183]
I have some utility libraries that are used in several websites. It would be nice if I can use separate projects for each website and the utility libraries would show up in all of them.
##

**Comment by tariver** [comment]
Describing my case as asked by @nijel in #3384

Initially we had two languages in our project - Russian (in which the system is developed) and English. Before system's localization files were integrated into Weblate they ware partially translated to German by just copying the English files and translating some strings in them, leaving other strings in English.
As a result, localization files for German now contain strings both in English and German.

These files were then integrated into Weblate project where source language was set to Russian and target languages set to English and German. And here a problem arose - how to easily sort out English strings in German files, because going through a couple of thousands strings manually is a cumbersome task.

My idea was to utilize Weblate's "Unchanged translation" check, but because this check only triggers if a string is the same in source and target language, not between two target languages, I decided to "mirror" all components (i.e. using the same files) in another project, where the source language is set to English. In this second project all the strings that are same in source language (English) and target language (German) would have a failed check "Unchanged translation", solving the problem.

There are two options to create this second project - either by using [Weblate's internal repository](https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls) or use the same git server as the first projects.

But both options come with drawbacks:
- Using internal repository lead to some inconveniences (see #3379) and undesired behavior (see #3384).
- Using the same git server may lead to merge conflicts.
