### ISSUE TITLE
Download/Upload in XLSX

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/weblate#1879]
when working with external translation agencies (or external translators), it would be helpful to download/upload translations in XLSX since many users work with Excel.

I've tried to use the CSV download, but Excel has giant problems with creation of a compatible CSV for the upload in Weblate.

I am thinking of the following workflow:

- export the translations from weblate via "Files -> Download translations as XLSX"
- send this XLSX file to our external translators
- receive the modified XLSX file
- upload the XLSX file via "Files -> Upload translations"

**Comment by nijel** [comment]
There was fork of Weblate adding Excel export/import, but it was never submitted for merging and quickly looking at it I found several specific hacks specific to their usage (but I might have been wrong). Anyway it probably could be used as starting point for implementing something what could be merged: https://github.com/dontnod/weblate/commits/dev

**Comment by mlaggner** [comment]
thanks for that hint - I'll try to create an exporter/importer next week

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/weblate/pull/1888 and https://github.com/WeblateOrg/weblate/pull/2164.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
