### ISSUE TITLE
Hidden components

### ISSUE THREAD

**Issue by atallahade** [WeblateOrg/weblate#2016]
From what I saw on the [FAQ](https://docs.weblate.org/en/latest/faq.html#how-do-i-translate-several-branches-at-once), I should be able to translate several branches at once. To do that, I tried to create two components with the same settings except for the branch that are different. Here are the problems I have:
1. I need to hide one of the component to make it easier for users to make translations
2. I tried to set the source code repository with a link to the other component (i.e. ` weblate://project/component`) but it didn't seems to work (only one branch was being used)

**Comment by atallahade** [comment]
@nijel It will not be very efficient if I do that unfortunatly. Do you have any other alternative?

**Comment by nijel** [comment]
No, weblate needs working copy for each branch. The only alternative with Git would be to use worktrees, but I don't think that would bring any significant benefits as Weblate already does swallow clones not fetching history of unrelated branches.

**Comment by atallahade** [comment]
Ok thanks, I think I'll stick with your solution then but it would have been nice to be able to hide components so users only see components with master branch.

**Comment by atallahade** [comment]
In our case there is none.

**Comment by vmassol** [comment]
I don't think they should be hidden since that would prevent them being translated. However the UI could not advertise them as pro-eminently as the master translations so that users doing translations don't pick the wrong branch by error.

Another problem is the setup cost: whenever a new branch is created you need to create duplicate components for all of them (and remove them once the branch is deleted). I guess this could be automated somehow with scripting and using the weblate REST API?

@atallahade I think we need to automate the component creation in a script that will automatically discover all translation resources from a given github organization (or github repository, but less good) and automatically create a weblate component for them. Maybe using the weblate REST API?

@nijel is that doable with the weblate REST API?

**Comment by nijel** [comment]
This is currently not doable with the API (it doesn't allow to add components). It can be automated using import_json CLI though.

**Comment by vmassol** [comment]
> but we will need to scan every files of every repository to find out if they are used for translation or not

Either that or use a github hook to register/unregister components when translation files are added/removed from git... :) (ofc we'll need a one time script execution to import existing translation files).

I wonder if anyone has written such a hook already :)

**Comment by atallahade** [comment]
> Yes but the problem is that this file cannot be imported automatically AFAIU...

What I meant is that we can easily edit the script to take as arguments the 3 points that I've given and call the script each time we find a new translation file (would also work with already imported one).

**Comment by nijel** [comment]
Revisiting this few years later:

* There is now API for creating components: https://docs.weblate.org/en/latest/api.html#put--api-components-(string-project)-(string-component)-
* You can define ordering of the components: https://docs.weblate.org/en/latest/admin/projects.html#priority
* You can restrict access to certain components: https://docs.weblate.org/en/latest/admin/projects.html#restricted-access

That should address pretty much all questions raised here.
