### ISSUE TITLE
Original and translated textboxes: Switch between horizontal and vertical 

### ISSUE THREAD

**Issue by SantosSi** [WeblateOrg/weblate#2033]
### Steps to reproduce
With longer strings resolution might not be high enough to have both the full texts strings visible at the same time, necessary for translation and review. Today's screen ratio is widescreen, but this is not effectively used with vertical textbox organization.

### Actual behaviour
Textbox organization is fixed.

### Expected behaviour
Provide a button to switch case by case (string by string).

### Server configuration
Hosted

**Comment by nijel** [comment]
Related to https://github.com/WeblateOrg/weblate/issues/2022 (though that is for zen mode and this is probably for classic one).

**Comment by comradekingu** [comment]
@SantosSi Can you provide a screenshot?
From what I can tell, having fields top to bottom is more effective overall. You can add/use scaling if it falls outside. I don't think this complexity is needed for a scenario where splitting up a string is almost always the thing to do instead.

**Comment by SantosSi** [comment]
I cannot provide a screenshot, as it is a request 
for a new feature.
I find it useful to have the original text and the 
translation side by side on today's 16:9/16:10 
screens. Basically the request is to give people 
the choice to decide which concept fits their 
preferences best.

**Comment by PowerKiKi** [comment]
I agree with @SantosSi. I think it would be counter-productive to have strings side-by-side, especially on a wide screen, because you will then have to constantly move your eyes from let to right, wile staying on the same horizontal line. It would be especially annoying for short strings, but even for longer strings I cannot imagine you could be faster reading/skimming.

Adding configuration for that seems way overkill IMHO.

**Comment by PowerKiKi** [comment]
On a side note, how are you posting from the future ?! 

![image](https://user-images.githubusercontent.com/72603/47962413-89f08380-e070-11e8-8fd6-0a66b5759d9d.png)

**Comment by comradekingu** [comment]
@PowerKiKi You disagree with @SantosSi.
With horizontal panels, you have twice the chance of wrapping unshifted lines, (because the screen is split) and when it happens, the need and likelihood of having to keep track of a multi-relational references go up. And not only that, they are also spread farther apart, making matters worse still.

On the contrary, if you have to start scrolling one string, something is wrong, but not with the layout. The idea is generally to cram two fields so close together they are in the active field of view. Maybe for review that makes sense, but the editors have far greater problems as of now.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
