### ISSUE TITLE
Longer file masks

### ISSUE THREAD

**Issue by NEOhidra** [WeblateOrg/weblate#2082]
### Steps to reproduce
1. Create a new component which file mask will be be 52 characters long
2. Save it

### Actual behaviour
The component will not be created because of this error:
> Language code resources/language/English (New Zealand)/strings.po is too long, please check filemask

### Expected behaviour
Create components which file mask can be longer then 50 characters.

### Server configuration
 * Weblate 3.0
 * Python 3.6.5
 * Django 2.0.6
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.sqlite3
 * Cache backends: default:LocMemCache

Is there a way to override this limit?

**Comment by nijel** [comment]
The problem is not long mask, but using "English (New Zealand)"  as a language code, which is supposed to be  ISO 639-1 or 639-2 code (en_NZ in this case).

Anyway this check is there mostly to catch invalid masks (eg. when language code is matched against something what is not language code), so it might use some improvements.

**Comment by nijel** [comment]
I've tried to improve the situation for these use cases, but still the recommended approach is using language codes instead of full names. Anyway it will work better in future releases:

* I've added definition of English (New Zealang) language
* The matching already works against language names, not only against codes
* The warning will not be shown if existing language has matched

**Comment by NEOhidra** [comment]
After adding a new language "English (New Zealand)" - Weblate 3.0 still fails to create the component.

Changing the folder name to something shorter like "English (Zealand)" works fine (without language defined). Changing it to something longer and the same error appears.

Can I force v 3.0 to create a component while still using "English (New Zealand)" as language code?

**Comment by nijel** [comment]
No, it will however work in 3.0.1 which will be released in next few days.

**Comment by NEOhidra** [comment]
Great!

Thank you for this fix!
