### ISSUE TITLE
Increase granularity in "Go to" options

### ISSUE THREAD

**Issue by adrmzz** [WeblateOrg/weblate#2116]
### Steps to reproduce
In an uncompleted translation, with non-consecutive untranslated segments, say you want to get to segment number 789.

### Actual behaviour
1. You can use the "Nearby messages" in the translation editor to browse segments in groups of ten (from 1-10, 11-20, etc.)
2. You can use the Search feature and filter by user, keywords, change date or other parameters.
3. You can filter by status (non-translated).
4. You can not (AFAIK) get directly to segment 789 out of 1000.

### Expected behaviour
Implement a "Go to" feature to get directly to a segment number. This would allow you to write down the segment number where you left a translation and resume translating at any time exactly at the same point.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has already been fixed by 349ca39cafc5ad17399c7db92fe5bffb19568e46.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
