### ISSUE TITLE
RC not supported on Python 3

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/weblate#2119]
### Steps to reproduce
1. install 3.0.1-4 from docker
2. visit http://localhost/admin/performance/

![image](https://user-images.githubusercontent.com/199095/42515958-a9a3e6de-8465-11e8-952d-0f4a9b80699b.png)

not sure even what that means. what is RC?

**Comment by nijel** [comment]
It's [Windows RC files](https://docs.weblate.org/en/latest/formats.html#windows-rc-files).

**Comment by nijel** [comment]
I've improved the error message and the docs to better indicate what is it about.

Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by freefri** [comment]
I'm getting the same error and I am a little bit confused:

Can I disable RC in any way so I do not get this warning? In the documentation I could not find any reference how to disable a format.

I think the key message is "You can safely permanently ignore errors for file formats you do not intend to use. These are usually caused by missing or outdated dependencies." If this message means that I can just ignore the error, maybe it could be more clear and more prominent (not so small font and light gray color).  It would be great to add a link to the documentation next to this error. It would be great to change the wording from "Error" to "Warning" since warning seems to be something you can ignore and error seems to be something you have to take care of.

![image](https://user-images.githubusercontent.com/2754631/58412440-b9032c80-8076-11e9-90d7-6514f4d798e5.png)

**Comment by nijel** [comment]
Don't you have the error from some older version? It is ignored in current versions:

https://github.com/WeblateOrg/weblate/blob/039346aa7dadd292ee403c884d9fad7d52ff3e6d/weblate/formats/models.py#L53-L54

What doesn't happen though is removing the error if it was triggered before...

**Comment by freefri** [comment]
I am running weblate from docker using the tag weblate/weblate:3.6-1 after upgrading from an older version, so maybe you are right and in a new setup this message is no longer displayed

**Comment by nijel** [comment]
Just dismiss it and should not appear again
