### ISSUE TITLE
Weblate sends an HTTP callback URL on an HTTPS installation

### ISSUE THREAD

**Issue by Zoddo** [WeblateOrg/weblate#2138]
### Steps to reproduce
1. Install weblate in docker behind a reverse proxy with HTTPS configuration
2. Sets `WEBLATE_ENABLE_HTTPS=1` in `docker-compose.override.yml`
3. Try to login with OAuth (i.e. with GitHub or Google)

### Actual behaviour
The callback URL sets in the URL is in HTTP.

### Expected behaviour
Weblate should sends an HTTPS callback URL accordingly to the `WEBLATE_ENABLE_HTTPS` environnement variable.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Can't find where the manage.py script is stored on the docker container.**

### System checks
Please paste the output of command `./manage.py check --deploy` over here

**Comment by nijel** [comment]
I can't reproduce this with [recommended https setup](https://docs.weblate.org/en/latest/admin/deployments.html#docker-container-with-https-support) so it's most likely something misconfigure on your reverse proxy.

The problem is that WEBLATE_ENABLE_HTTPS affects Weblate generated URLs, but this one is generated by third party app (social-auth) and that get's the http(s) protocol from the request information.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
