### ISSUE TITLE
Glossary matches on a single word instead of the whole string

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#2183]
### Steps to reproduce
1. Upgrade to Weblate 3.1.1
2. ./manage.py rebuild_index --all --clean

### Actual behaviour
Glossary will show all entries which have at least one word present in the source. See screenshot, all entries containing "the" are shown.
![screenshot](https://user-images.githubusercontent.com/1279852/44265959-f23e7e80-a252-11e8-8461-7a4429219e03.png)

### Expected behaviour
Glossary showing the entries that have full match. (+ wordforms/plurals? Not sure if that was the case in 2.x)

### Server configuration and status
```
 * Weblate weblate-3.1.1-4-ge65c8c6a9c
 * Python 3.6.5
 * Django 2.1
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * PyYAML 3.13
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.15.18-1-pve (x86_64)
```
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.
```

**Comment by nijel** [comment]
Yes, now it matches if single word matches. See https://github.com/WeblateOrg/weblate/issues/1773 for reasons why this was chosen, but suggestions how to implement better lookup are certainly welcome.

**Comment by burner1024** [comment]
Oh, so this is intentional. OK... here are my thoughts:
1) I don't quite understand the referred use case. HTML tags in glossary? Or source strings? Seems defeating Weblate's purpose.
2) Not sure if stemmer matches just plurals or wordforms as well? If just plurals, I'd trade that for strict multiword match.
3) A bit of a hack, but if the main reason is db load, maybe filter the result before displaying? For each multi-word item in glossary lookup result, generate forms with stemmer, check if at least one of them is an exact match for the string, if not - discard the item?

**Comment by nijel** [comment]
It's not really intentional, it's really more a best effort evolution from single word matches it did originally. Having something better is certainly desired for future. Maybe we can use fulltext engine to do the matches instead of doing that in the SQL database.

The referenced issue was about regexp based matching which was used for some time. That behaved better in most cases, but it produced too complex regexps for long texts.

**Comment by milossramek** [comment]
+1 to this issue and especially to nijel's suggestion to add an option to look up in the glossary by a whole phrase.

My motivation is as follows.

In LibreOffice we have a ton of strings to translate: GUI strings and Help strings. The Help strings often refer to GUI objects, therefore it is necessary to look the objects up either in LibreOffice itself or in the translation in order to know the correct translation. This is a cumbersome task (LO is a complex program).

The OmegaT CAT tool enables its users to upload the GUI translation to its glossary. One can then conveniently find in OmegaT's Glossary widget each translated phrase, found in the source string. This is very convenient and speeds up translation significantly.

I've tried to get the same by uploading the GUI translation to Weblate's glossary. I get, however, exactly what nijel described in #2828 - one correct suggestion in a list of many hundreds nonrelated ones. This helps a little, but if the lookup were performed by exact phrase matching I would get just one (the right) suggestion.

Thank you for considering this
Milos
