### ISSUE TITLE
Facebook Login doesn't work

### ISSUE THREAD

**Issue by Johnson145** [WeblateOrg/weblate#2250]
**Describe the bug**
Currently, it seems to be impossible to login using the Facebook login feature. You can see the problem e.g. on the [official demo project](https://demo.weblate.org/accounts/login/?next=/).

**To Reproduce**
1. Go to the Weblate login form.
2. Click on the Facebook icon.
3. If you aren't logged in to Facebook yet, you'll be successfully redirected to the login form on facebook.com.
4. After you've entered your credentials on facebook.com (or already have been logged in there), you'll be redirected to your Weblate login.
5. Unfortunately, you're still not logged in to your Weblate project. It seems like nothing has changed and you could repeat the above steps several times.

**Expected behavior**
After following the steps listed above, you should not only be logged in to facebook.com, but to your Weblate project as well.

**Server configuration and status**
As stated above, this applies e.g. to the current demo version, too.

Any help is appreciated very much!

PS: E.g. the Google login does still work.

**Comment by Johnson145** [comment]
Thanks for the quick reply.

If you haven't reverted your changes already, I don't think they are related, because I still can't login on the demo using Facebook.

**Comment by nijel** [comment]
Strange, it now works for me and it did not work before.

Anyway for Hosted Weblate the issue is different: 

> your app is currently in violation of Facebook Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.

**Comment by Johnson145** [comment]
Interesting. I've cleared my cache and tried a few different browsers, but nothing has changed for me. You're using [this link](https://demo.weblate.org/), too, right?

**Comment by nijel** [comment]
Yes, I'm using that. Just one more question: Do you have existing account or creating new one? I'm using existing account.

**Comment by Johnson145** [comment]
It's an existing Facebook account, but I don't got any Weblate account on the demo website yet (at least if no [broken] one has been created during my trials).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. We didn't specifically request email from the Graph API and it was causing this. The existing associations were not affected and that's what confused me (I had existing association on demo, but not on hosted, that's why it has behaved differently for me).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
