### ISSUE TITLE
Screenshot upload menu not available

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2256]
Can't for the life of me find the menu to upload screenshots.
https://hosted.weblate.org/screenshots/trebleshot/strings/ still works, whereas
https://hosted.weblate.org/screenshots/pentobi/strings/ does not.

Is it a subscription feature?

https://hosted.weblate.org/stats/ says there are no screenshot uploads, so something is off.

**Comment by nijel** [comment]
There is no component called strings in pentobi :-). The correct URL is https://hosted.weblate.org/screenshots/pentobi/pentobi/ . You don't see the menu that you're trying to construct URLs manually?

The stats are not counting older uploads as we didn't track users for them, so it's only counting since this was changed.

**Comment by comradekingu** [comment]
Ah, I had to click into the component to get to the menu. My bad.
