### ISSUE TITLE
Filtering projects by license

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2263]
**Is your feature request related to a problem? Please describe.**
On Hosted Weblate some translators might want to contribute only to libre projects and not to proprietary ones.

**Describe the solution you'd like**
One of options is to manage list of licenses and whether they are libre (note that this might be questionable) and allow users to filter their projects based on that.

**Describe alternatives you've considered**
Another approach is to indicate this in project listing, see https://github.com/WeblateOrg/weblate/issues/2194

**Additional context**
See https://github.com/WeblateOrg/weblate/issues/2141

**Comment by comradekingu** [comment]
The subscription model is a bit broken, as it requires way too much clicking.
"Subscriptions" used to have license, now they are in https://hosted.weblate.org/projects/androbd/#information that is worse IMO.

Project license should be in https://hosted.weblate.org/projects/androbd/#information in any event.

I believe in presenting the user with all projects (non-paged), and using settings for sorting and removal. Proprietary projects should be removed by default.

In the main view one should be able to follow them, so that they are sorted on top.
Similarly, sorting by Android / crypto / and/or GPLv3+ would be great. Crowdin does this in a hierarchical way, but with metatags it would be much nicer.

**Comment by nijel** [comment]
The license was always bound to a component, not project, for example [OsmAnd translations are MIT licensed](https://hosted.weblate.org/projects/osmand/main/#information), while [OsmAnd iOS are GPLv3 licensed](https://hosted.weblate.org/projects/osmand/ios/#information).

**Comment by comradekingu** [comment]
It could be sorted last? For "GPLv3+, MIT"?

**Comment by nijel** [comment]
I've added displaying of licenses for project in 9718a728d8f5eb8dbeea7dfb7037a431aa77d610.

**Comment by nijel** [comment]
I think the current indication is good for most use cases without making the whole licensing stuff too complex.

**Comment by comradekingu** [comment]
@nijel 
OsmAnd-licensing only says MIT for the Android component.
![Skjermbilde på 2019-03-16 22-26-05](https://user-images.githubusercontent.com/13802408/54481867-ada3b180-483a-11e9-8b0e-85353d4bd507.png)

While that might be an unsolvable bug in itself, I think translator license should be listed only if it differs from the project license.

**Comment by comradekingu** [comment]
@nijel I liked it a lot better when it was
https://user-images.githubusercontent.com/13802408/54481867-ada3b180-483a-11e9-8b0e-85353d4bd507.png instead of the long format ones. Also gives some connection with the icon tags to use short ones #3419 

The mouseover could be the long format.
