### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by akcansoft** [WeblateOrg/weblate#2470]
Can you add "Copy to Clipboard" button for source strings.

![image 1](https://user-images.githubusercontent.com/7031346/50376812-dd6c6000-0623-11e9-9f26-288353ea3e10.jpg)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/WeblateOrg/weblate/pull/2528.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
@akcansoft We're currently revisiting some things in the translation interface and I'd love to hear your use case for this feature to help us understand how it is being used.
