### ISSUE TITLE
Component list should show missing translations

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2610]
**Describe the bug**
We use component lists to indicate list of components to translate for particular product. If I add a component with no po files, it is not visible in the component list view. It is very confusing, as the translator does not see a missing translation.

**To Reproduce**
1. Add a new component with pot only, no po files, ability to automatically add languages.
2. Add this component to a component list.
3. Go to the main page and click to the component list.
4. The newly added component is not visible.

Example:
I added yast2-rmt/master to list-sle-15-sp1. yast2-rmt contains no languages. It is not visible in
https://l10n.opensuse.org/#list-sle-15-sp1
https://l10n.opensuse.org/projects/yast-rmt/master/

**Expected behavior**
The newly added component is visible, either as 0%, or with a N/A note.

**Screenshots**

**Server configuration and status**
./manage.py list_versions
 * Weblate 3.3
 * Python 3.6.5
 * Django 2.0.8
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.6.1
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.3
 * pyuca 1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.12.14-lp150.12.45-default (x86_64)

./manage.py check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E019) The Celery does not process tasks or is too slow in processing them.
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#celery

System check identified 1 issue (0 silenced).

**Additional context**
All projects view shows the project, but 100% in this case. 0% or N/A would be more intuitive.

**Comment by nijel** [comment]
Yes, component lists only show existing translations. I don't really see how it should work differently - Weblate has no knowledge into what languages you want to translate this component. Do you expect it to show up on *all* languages? 

The best approach to this is IMHO to create languages you want at once.

PS: They are intentionally showing 100%, see https://github.com/WeblateOrg/weblate/pull/2071.

**Comment by stanislav-brabec** [comment]
If the component list is used by translators, then this behavior is very confusing.

If the package is in the component list, and the translation does not exist, Weblate should mention these component in the component list view somehow. Otherwise these components can be easily overseen by translators.

**Comment by nijel** [comment]
So your expectation is to show the components which do not have translation into current language as well in all cases? No matter what language(s) user is using?

**Comment by stanislav-brabec** [comment]
I would like to see an information that the component is in the component list, but its translation to the current/selected language is missing. Otherwise it is hard to guess, why we have a 100% in the component list, but the software still has untranslated strings.

Example: https://l10n.opensuse.org/#list-sle-15-sp1 with a Czech user currently does not contain any mention about yast-rmt (that is in the component list) because it has no cs.po. But Weblate displays no information about it.

I would prefer to display “0%”, “N/A”, ideally with a button “Start new translation”.

**Comment by comradekingu** [comment]
@nijel I envision this being a full list for all selected languages.
The unadded/missing components would be transparent.
Otherwise component discovery is a case of knowing to look for it, and component addition is a process of comparing the source list to the respective language. And sometimes there isn't a source list even (?)

**Comment by sr258** [comment]
I think it would be great if the component list of a project displayed placeholder entries like @comradekingu describes if the user has selected a "language" and a "project" (like here: https://deutsche-h5p-uebersetzungscommunity.tk/languages/hr/h5p/). In the link you'll see that there are only two components, but the project actually has dozens of components. For translators its quite tedious to check which components need new files.

It would also be great if components without language files for a language would still be considered as untranslated for the statistics generated for the language (in the overview and for the badges). Weblate tells me that 83% of the Croation translation is finished, while it's probably only 1% (because of all the components that weren't taken into account).

**Comment by comradekingu** [comment]
@sr258 For the widgets, sometimes the % of a reduced set of components is correct, which (other than performance of needlessly adding components) is why they don't show "of total" numbers. Lets say someone only wants to have the main app in the main language, and not the guide intended for another demographic.
Overall I think "of total" numbers are better, because it gives yet another way to find un-added components.

**Comment by sr258** [comment]
@comradekingu I do agree that the use case exists and it would be great to have an option to choose which statistic you want.
