### ISSUE TITLE
E-mails addresses in sent language request e-mails.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2701]
There was no "feature report", so I guess this is a bug.
New language requests, and additions, will have the requesters name listed as a link to the requesters e-mail address.

![Skjermbilde på 2019-04-20 15-17-05](https://user-images.githubusercontent.com/13802408/56457764-a747ae80-637f-11e9-9f96-2ce7c9537b86.png)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported was already fixed in 14463ec20a9b69c9fb2651048ed6ad237a24c987.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
