### ISSUE TITLE
Can't remove metadata components

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2711]
Tried to remove some empty languages:

Went to https://hosted.weblate.org/projects/f-droid/#languages

Clicked https://hosted.weblate.org/projects/f-droid/f-droid-metadata/bn/

Administrate ↓ Removal
Enter name

Server fault: 7948f8254c43487e9262efee88080823

Edit: The Language Consistency plugin was turned on, then turned off. All other components within bn were deleted manually.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed by 35a098d8443669f394cfa42f1786f035099759af.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
