### ISSUE TITLE
Show completion based on potentially added strings.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2732]
Right now there is no easy way to compare completion across languages with different components added. It would be nice to have the option.
Especially comparing total language progress, across all potential components is interesting.

**Comment by nijel** [comment]
At what level would you like to see that? 

I think we used to have this at project level, but was changed to show actual state for existing translations at some point because it was confusing (though I can't find any reference for that right now).

If some project aims at having full set of translations, it should enable [Language consistency addon](https://docs.weblate.org/en/latest/admin/addons.html#language-consistency). This way all translations will be actually present.

**Comment by comradekingu** [comment]
@nijel At every level. So one can switch between them. Both are useful in their own right.
For example in https://hosted.weblate.org/languages/ knowing one can see that "Patwa" is almost completed, but that is a bit arbitrary, seeing as it has two components.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by comradekingu** [comment]
(This belonged here, not where I pasted it)
In my head it is generated data, a run each day is fine.
https://hosted.weblate.org/stats/ has
(total amount of) translatable strings and
(total amount of) translatable words

https://hosted.weblate.org/languages has
(current amount of) translated strings and (though in %)
(current amount of) translated words (though in %)
However that is derived, the "all strings" for each component, per language, is the number.

It would be nice to have current in % completion of total, in two extra columns in https://hosted.weblate.org/languages, and/or make both current columns sortable by total completion.

![bilde](https://user-images.githubusercontent.com/13802408/58926999-4c122580-874d-11e9-8919-e50a8c37372c.png)
