### ISSUE TITLE
No short-cuts activated in "Commons App"

### ISSUE THREAD

**Issue by ccppoo** [WeblateOrg/weblate#2745]
What I was working on ↓ 
![image](https://user-images.githubusercontent.com/46418312/57713224-019d0c00-76ad-11e9-96e1-acfa24fdd921.png)

Other langauges seems to have same problem.
It's not really a problem I could just copy and paste it, but I just wrote this because I've ever seen short cuts not activated.

source [link](https://github.com/commons-app/apps-android-commons/blob/967d3ea5938f240c878bc7a6f401539c79be5646/app/src/main/res/values-ko/strings.xml#L104)

**Comment by nijel** [comment]
The problem is that the source is not well formed XML (it's missing quotes around attributes). Weblate currently uses XML parser to detect this...

**Comment by ccppoo** [comment]
So someone should tell to the owner of this source
But most of the translators of other languages just copy and pasted... just minded if there was something wrong with Weblate
Close this if there's nothing wrong with Weblate :)

**Comment by nijel** [comment]
You can edit the source string as well to fix this, just click on the pencil icon next to it :-).

But the actual problem here is different: The application uses translatewiki for translations and nobody told us, so the project on Weblate is abandoned. I've just asked the original requestor to handle this.

**Comment by ccppoo** [comment]
I should try as much as I can.
Thanks for specific reply :)
