### ISSUE TITLE
Continuous "request rate limit ..."

### ISSUE THREAD

**Issue by ccppoo** [WeblateOrg/weblate#2751]
![image](https://user-images.githubusercontent.com/46418312/57833480-11c00300-77f5-11e9-99a6-dbfe72f7e734.png)

[What I'm working on](https://hosted.weblate.org/translate/debian-handbook/00b_foreword/ko/?type=all&offset=52)
When I try to add glossary, that pop up several times when I clicked onece again [add] on glossary.
Is this some problem related to server? or is I'm the one doing not encouraged to do?

**Comment by nijel** [comment]
This happens when rate limiting has been applied. I need to check what limits are there for glossary edits ...

**Comment by ccppoo** [comment]
sounds it's not a problem :)

**Comment by nijel** [comment]
Well this is not supposed to happen in normal operation :-)

**Comment by ccppoo** [comment]
Oh, I heard like you limited for some reasons...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. The ratelimiting is intentional, but the scope was wrong and not documented properly.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
