### ISSUE TITLE
Top padding different between views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2794]
![bilde](https://user-images.githubusercontent.com/13802408/59001142-de79fe00-880d-11e9-95c8-171c1620c1b9.png)
https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview
**vs**
![bilde](https://user-images.githubusercontent.com/13802408/59001161-f5205500-880d-11e9-9ecd-36c9355773b6.png)
https://hosted.weblate.org/projects/guardianproject/

Click from one to the other to see difference.

---
- [x] **Top padding**
The padding up top is different, which throws the A/B comparison off. (Top green pepper)

**Comment by nijel** [comment]
Thanks for your report. It would be better to report each of the issues separately, this way it will be harder to track what has been addressed and what not...

**Comment by comradekingu** [comment]
@nijel Will do, it kept piling on as I looked at it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed by https://github.com/WeblateOrg/weblate/commit/10c30047b2f3d5920ccd2ff64a395b84340a104b and https://github.com/WeblateOrg/weblate/commit/76ccda3b7e67cc0fa3ee076b47951715c0b9fa00.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
