### ISSUE TITLE
Same translation used twice

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2798]
Hi,

The same translation string is used twice:
* on the dashboard, it should be a plural
* as a tooltip in the translation checks, it should be a singular.

See 2 screenshots from hosted weblate:

![DashBoard](https://user-images.githubusercontent.com/1452146/59031662-9934eb00-8864-11e9-8b42-a74a80389e5c.jpg)

![Details of checks](https://user-images.githubusercontent.com/1452146/59031426-faa88a00-8863-11e9-9329-29c6f0dbf000.jpg)

Request: create 2 different strings for these 2 contexts, thanks

**Comment by nijel** [comment]
This is valid for all checks - they have just one description which is used in both cases.

**Comment by comradekingu** [comment]
@ldmpub Could you do a back-translation, explain it directly in English?

The real solution would probably to do singular if there is just one failing string,
and then plural if there are more than one.

**Comment by ldmpub** [comment]
Here is the concerned string used twice: https://hosted.weblate.org/translate/weblate/master/fr/?checksum=a996d4cfc8b3114d / in english: "This string has been translated in the past".

I agree with @comradekingu, we need 2 strings:
- one string singular only, used as tooltip (see my 2d screenshot)
- one string singular and plural used in the dashboard depending on 1 or several strings concerned (see my 1st screenshot)

What do you think?

**Comment by nijel** [comment]
Maybe it would be better to write the check description in a way that it would work in both places?

What we currently have:

 * Source and translation are identical
 * Source and translation do not both start with a newline
 * Source and translation do not both end with a newline
 * Source and translation do not both start with same number of spaces
 * Source and translation do not both end with a space
 * Source and translation do not both end with a full stop
 * Source and translation do not both end with a colon or colon is not correctly spaced
 * Source and translation do not both end with a question mark or it is not correctly spaced
 * Source and translation do not both end with an exclamation mark or it is not correctly spaced
 * Source and translation do not both end with an ellipsis
 * Source and translation do not both end with a semicolon
 * Translation should not exceed given length
 * The decorative kashida letters should not be used
 * Python format string does not match source
 * Python brace format string does not match source
 * PHP format string does not match source
 * C format string does not match source
 * Perl format string does not match source
 * JavaScript format string does not match source
 * C# format string does not match source
 * Java format string does not match source
 * Java MessageFormat string does not match source
 * AngularJS interpolation strings do not match source
 * Some plural forms are not translated
 * Some plural forms are translated in the same way
 * This string has more than one translation in this project
 * This string has been translated in the past
 * Number of \n in translation does not match source
 * BBcode in translation does not match source
 * Translation contains extra zero-width space character
 * Translation rendered text should not exceed given size
 * The translation is not valid XML
 * XML tags in translation do not match source
 * Markdown link references does not match source
 * Markdown links do not match source
 * Markdown syntax does not match source
 * The translation does not contain an URL
 * The string is optionally used as plural, but not using plural forms
 * The string uses three dots (...) instead of an ellipsis character (…)
 * The translations in several languages have failing checks

The only ones which look problematic to me are starting with "The string", so it's probably better to rephrase these descriptions...

**Comment by comradekingu** [comment]
It has often annoyed me that these are so long, it could have a section saying
"Mismatched:" and then do away with even that word

- Unchanged
- Missing newline
- Missing ending newline
- Mismatched number of starting spaces
- Mismatched ending space
- Mismatched ending full stop
- Mismatched ending colon, or incorrectly spaced colon /// should be two categories IMO (?)
- Mismatched ending or incorrectly spaced question mark /// should be two categories IMO (?)
- Mismatched ending or incorrectly spaced exclamation mark /// should be two categories IMO (?)
- Mismatched ending ellipsis
- Mismatched ending semicolon
- Too long
- Kashida letters used
- Mismatching python format string
- Mismatching Python brace format
- Mismatching PHP format string
- Mismatching C format string
- Mismatching Perl format string
- Mismatching JavaScript format string
- Mismatching C# format string
- Mismatching Java format string
- Mismatching Java MessageFormat string
- Mismatching AngularJS interpolation strings  /// why strings here?
- Untranslated plural /// why forms here?
- Unchanged plural /// why plurals here?
- Mismatching translation /// possibly: Translated differently
- Already translated ///
- Mismatching number of \n
- Different BBcode used
- Extra zero-width space /// mismatching?
- Rendered text too long /// why not next to "too long"?
- Invalid XML
- Mismatching XML tags
- Broken markdown link
- Mismatching markdown link /// why links?
- Mismatching Markdown
- URL added
- Missing plural /// why is it optional plural, because of language, or string?
- Three dots (...) instead of ellipsis (…)
- Often fails

**Comment by nijel** [comment]
To clarify some of the checks:

> The string is optionally used as plural, but not using plural forms

Is source string check triggered when plural should be used, for example if the string is `Apple(s)`, the correct way  should be plural string `Apple`/`Apples`.

> Translation rendered text should not exceed given size

There are two similar checks - one checks simple text length and this one renders the text using defined font and checks dimensions in pixels.

**Comment by comradekingu** [comment]
That sounds like "unpluralised" to me.
The extra explanation is good for the second one.

**Comment by ldmpub** [comment]
Hi, what about my original request?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
