### ISSUE TITLE
Naming of component/Project button different between views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2803]
**Different names**
At-least in Norwegian one field is 
"Component"
![bilde](https://user-images.githubusercontent.com/13802408/59001399-b0e18480-880e-11e9-833b-c4721a100659.png)

https://hosted.weblate.org/translate/weblate/master/bg/?checksum=25c3e74edddbe2ff

The other is "Project"
![bilde](https://user-images.githubusercontent.com/13802408/59001414-c35bbe00-880e-11e9-9fcd-8c70d6a13859.png)

https://hosted.weblate.org/translate/weblate/hosted/ach/?checksum=774e4485998217c6
https://hosted.weblate.org/translate/weblate/master/sc/?checksum=774e4485998217c6

Which is a distinction lost on me, and not necessary (?) seeing as the "Component" tab is selected for both. 
![bilde](https://user-images.githubusercontent.com/13802408/59002056-61e91e80-8811-11e9-8d8c-43ea3aaafe3d.png)

[One way](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview)
vs
[The other](https://hosted.weblate.org/projects/guardianproject/)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed by f149f2c4e7a9e03d0a128e4fb76fcee8e95075cf.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
