### ISSUE TITLE
Hide components a user can not translate

### ISSUE THREAD

**Issue by Kingdutch** [WeblateOrg/weblate#2814]
**Is your feature request related to a problem? Please describe.**
We have various components within a project that should have a consistent language (shared translation memory). However, some of the components should be translatable by users that do not need to see all the components in the project. 

We can get very far using a lot of groups with component lists. However, when a user has access to translate a single component in a project into a single language then they can suddenly view all components and languages for that project. This could expose information from a component that is managed by one user and should not be shown to another user.

**Describe the solution you'd like**
Ideally there is a (project/platform) setting where components can be hidden for users if they do not have the ability to add suggestions/add translations or otherwise interact with it.

**Describe alternatives you've considered**
Splitting out the prohibited components to a different project can be considered a workaround. However, this loses the possibility of a shared translation memory because this is not yet supported across projects (implementing that would probably also fix our problem).

**Comment by comradekingu** [comment]
I didn't understand why a user working on a limited set of components shouldn't be able to see all components, especially if you want consistency. That it is not needed is true, but is that an inconvenience, or a problem? What is the problem?

I think it is possible to hide projects, where users need different sorts of accounts. @nijel will know.
TM works across projects as far as I know, what is it that fails there, and what version of Weblate are you using?

On the whole, I really don't like not seeing something. Seeing it as grayed out would be preferable. Right now there is no such visual clue for projects that only accept suggestions for example.

**Comment by nijel** [comment]
The access control was designed in this way, pretty much for reasons mentioned by @comradekingu. Not accessible projects are not visible at all to users, but there is no strict filtering at component or language level - it only controls what is user able to translate, but he can see other components and translations as those are typically useful when translating.

**Comment by kissu** [comment]
Hi, I'm opening this one back to add more context on why such a feature would be nice.

Our app is currently translated in a mix of 2 things:
- a determined locale, like `fr` or `en-GB`
- a name identifying some minor changes for a specific client like `greenpeace` or `wwf` 

So, we do have something generated like `fr-greenpeace.json` or `en-wwf.json`.

Tomorrow, we wish to let some clients generate their own locale, like an arabic client (to avoid poor translations on our part or simply strip that from their initial setup fee).
The issue is that we already had the situation where a `client A` wished to use our product **only if** we discarded it for a `client B` (for example `greenpeace` not being ok with other companies).

We are neutral on that part but we will probably have issues between some of our clients if we cannot hide the locales.

Creating specific projects may be kind of a solution but it will be annoying quickly when our `Sales` team will try to edit out a typo or complete a new JSON key.

**Comment by nijel** [comment]
Since Weblate 4.1 you can hide individual *components*, see https://docs.weblate.org/en/latest/admin/projects.html#restricted-access
