### ISSUE TITLE
No string invalidation/change without source letter change

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2830]
https://hosted.weblate.org/translate/tinymediamanager/translations/nb_NO/?checksum=80ac69e3a5087dc9

This seems to have slipped past me, but upon seeing the string in other languages, it seems the languages where it is unchanged didn't get their non-changed string updated. (?)

Meaning if it previously was "IMDB" with autopopulated "IMDB", it is still "IMDB" after the source changed to "IMDb"

Could it be because it is technically not unchanged after the source changes and the string isn't updated?

Plenty of examples in https://hosted.weblate.org/translate/tinymediamanager/translations/nb_NO/?checksum=990646749503bf23

Edit: If changing a translated language to "IMDb", the number of unchanged strings doesn't increase, but the check does show up in the regular editor…

**Comment by nijel** [comment]
I'm a bit confused with this - six months ago you've fixed the source string, now the translation. The missing needs edit flag after source change might be caused by #2602, but that will be hard to verify as it was quite some time ago.

When testing editing this on Czech, the flag and count on translation page is properly updated, so I'm probably doing something different than you.
