### ISSUE TITLE
Always show "Admin" labels

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2846]
In https://hosted.weblate.org/projects/ a little label ![bilde](https://user-images.githubusercontent.com/13802408/60389355-3c71cc80-9ac0-11e9-9bf0-50bb3c6ae794.png) is shown if the user browsing it is an administrator for any particular project, whereas in
https://hosted.weblate.org/languages/nb_NO/
there are no such labels.

It is useful to know when this ability is present to single out a project, or to work on the ones with the most features available.

**Comment by nijel** [comment]
Currently the admin badge is shown only for selected views (when listing projects). The question is whether it should be shown in all places or just pick more locations where to show it.

It's not shown in all places because it's probably not that useful piece of information when browsing components in a project or translations in a component, because either all would have the badge or none would have it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
