### ISSUE TITLE
Clarify words/strings of total labels

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2866]
**Describe the bug**
The "Strings of total" / "Words of total" columns available on some views are confusing to many users.

**Additional context**

See discussion at https://hosted.weblate.org/translate/weblate/master/fi/?checksum=655539e4b9213b2e#comments

This was introduced in https://github.com/WeblateOrg/weblate/issues/2732

**To Reproduce**
1. Go to https://hosted.weblate.org/languages/

**Comment by comradekingu** [comment]
The difficulty is with keeping it short and sweet. Since the first is already "strings" and "words"
(____) "of instance total." or (____) "of total on instance".
A possible mouseover that describes how many strings there are total, and states it in absolute numbers would be helpful.
For me the confusion is which field the bar corresponds to, and I don't know exactly what the description of the problem is. Back when it was implemented there was one bar for each.

How about being able to click the actual field name to show the corresponding bar?
That, along with some indication that the "Strings" is selected (by default), would maybe help?

**Comment by ldmpub** [comment]
My concern is to understand and then to clarify for users by using "good" words what "total" are we speaking about here?

Total can not be used alone but needs a "reference" for instance: "Total of words in a phrase / in a book". Above the word "instance" does not refere to anything, as far as I know in Weblate ; maybe it means "server"?

**Comment by comradekingu** [comment]
@ldmpub 
A total does not need to be qualified. https://www.merriam-webster.com/dictionary/total
Regardless, your point remains I was wrong suggesting it.
Since the bar, and "half-full glass" way of looking at a bar is describing the added, rather than the missing part, it needs to detail completion positively.

I rather like the "on instance", because then all the graphs can have this segment.
In the dashboard it would detail how many % of the total available strings/words any respective project represents. (In danger of confuzingu striking), also, the % of currently untranslated is missing there. (but it was anyway…)

![bilde](https://user-images.githubusercontent.com/13802408/61009702-e7fa0700-a373-11e9-8b12-811b982316a1.png)

![bilde](https://user-images.githubusercontent.com/13802408/61009780-27285800-a374-11e9-9f2d-5f151d70b461.png)

I don't know that the ( )s made it any clearer, nor do I know what happens with this way of doing it in RTL languages.

**Comment by ldmpub** [comment]
@comradekingu Thanks for your confirmation "instance = server".

I'm quite lost by your other explainations and I'm still confused on using, understanding and translating theses dashboard statistics :-(.

If I go back to my major concern, in merriam it's stated

> Total noun
> English Language Learners Definition of total (Entry 2 of 3)
> : the number or amount of everything counted

So it confirms, from my point of view, that a total is counting something which should be clearly identified by a name and / or context.

**Comment by comradekingu** [comment]
@ldmpub There are however many ways to use "total".
A count or tally comes to _a total_. You could describe that number as _the total_, by saying "the total is x".

**Comment by comradekingu** [comment]
I have given up on being theoretically correct and problematic in practice.

To make a long trail of thought short, I want to go from
![bilde](https://user-images.githubusercontent.com/13802408/71085216-4a62f900-2197-11ea-97e3-704633e64112.png)
to
![bilde](https://user-images.githubusercontent.com/13802408/71085414-c65d4100-2197-11ea-99f9-e7858310c74c.png)

The idea being to represent unadded strings as a percentage of the total of the bar. This way it is easy to see if components are not added, and their respective breakdowns, without having an extra category.

**Comment by nijel** [comment]
I'm not really convinced it's a good idea to assume this is something that interests most projects. In case projects wants, it can enable language consistency and the stats is what you want to see. In case it doesn't, what are these numbers for?

Typical example could be [OsmAnd](https://hosted.weblate.org/projects/osmand/). The iOS and Android apps are developed and translated independently, so there is really no pressure to have same languages supported in both.

**Comment by comradekingu** [comment]
@nijel If it doesn't interest most projects, then why is "of total" of interest? This removes "of total", and the reason why it confuses people, retains the same info, with less visual elements.
It would be great for OsmAnd iOS if more people discovered the resource. It is nearly always the case that things should be added when they could. In due time, and for what is deemed important to the translators.

**Comment by nijel** [comment]
C. Rüdinger suggested on https://hosted.weblate.org/translate/weblate/master/en/?checksum=655539e4b9213b2e:

> What about "share in total" (percentage share of all strings in project)?

**Comment by nijel** [comment]
Revisiting this now as the column is still a source of confusion. While I can see this information is useful to some users, it doesn't seem to be widely needed. Going through proposals I've seen so far, I think we should pick one out of:

* Remove the column without any replacement, most people won't notice it's not there
* Move the information to progress bar only, that seems to be confusing as well, as the progress bar would not match the numbers
* Find better description for the column. It seems we have failed in this for several months
* Find alternate metrics which would be easier to understand and describe. How about using "Missing"? That should be understandable to most of the users while still giving the information.

Unless I see compelling reasons against that, I'm going to implement the last option.

**Comment by comradekingu** [comment]
@nijel 

With there now being ghosted components if they aren't added, the need to discover unadded projects through the "of total" is not as present.
Moreover, it is very kingu-like, for a platform that otherwise is very easy going, so removing it is an outright benefit that plays into the consistency of what Weblate is. The ghosts work, and this is sort of both, so I am thinking ghosts only.

If going with bars, they would have to differentiate between "missing" and "unadded" (like the last part of Airsonic here) That maybe isn't obvious, so let's see what happens without.

![bilde](https://user-images.githubusercontent.com/13802408/100634162-da596e80-3326-11eb-9762-0a1c52aa5400.png)

It would be nice if the icon could mouse-over to give more specialized info.

To carry the ghost-icon into the bar works (in the interest of not adding complexity), (Andor's Trail example) but not if there isn't room, like it would be for Airsonic.
