### ISSUE TITLE
colon spacing rule does not apply correctly in French

### ISSUE THREAD

**Issue by jnavila** [WeblateOrg/weblate#287]
For what I know,in French, colons must be preceded by a space or a non-breaking space. The rule to check this fails at checking it correctly.

See https://l10n.cihar.com/projects/weblate/javascript/fr/translate/?type=end_colon

If I am mistaken, what is the expected correct format for the space before the colon ?

**Comment by BoFFire** [comment]
Hi,
Check for french should be :
U+202F before ?!: but attached to each one.
Example :
```
french-wordU+202F?
french-wordU+202F!
french-wordU+202F:
```

The result will be :

```
french-word ?
french-word !
french-word :
```

Another thing to add is a check for `'` U+0027 to be replaced by `’` U+2019. Note that autofix can break some translations such as in this context :
`User is banned because '{%reason}'`

I advice *not to apply an autofix* for U+2019 but just run it as a *check to inform translators* that in french U+0027 *should be* replaced by U+2019.
The translator can run a Search an Replace to review the strings.

If need more information, just ask :)
Regards,

**Comment by nijel** [comment]
Can you please open separate issue on that instead of continuing in 5 years closed issue? Anyway this is what the check currently does:

https://github.com/WeblateOrg/weblate/blob/b5e54664dc8a5307ee3f64b9c632b9a85c229c23/weblate/checks/chars.py#L172
