### ISSUE TITLE
E-mail or email

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2883]
https://hosted.weblate.org/search/weblate/?checksum=&offset=&q=email&search=substring&source=on&type=all&ignored=False&date=&only_user=&exclude_user=&lang=nb_NO 
or
https://hosted.weblate.org/search/weblate/?checksum=&offset=&q=e-mail&search=substring&source=on&type=all&ignored=False&date=&only_user=&exclude_user=&lang=nb_NO

Currently more "email" then "e-mail", the latter is my preference, because then people don't forget the dash. I looked at one "email" string, and results were though better than usual.

**Comment by nijel** [comment]
It seems that recommended English spelling these days is "email", but I tend to use "e-mail", because it's what's mostly used in Czech. 

See [Oxford dictionary](https://www.lexico.com/en/definition/email), [Wiktionary](https://en.wiktionary.org/wiki/email) or [From E-mail to Email: Is the Sky Falling?](https://cmosshoptalk.com/2017/10/11/from-e-mail-to-email-is-the-sky-falling/).

**Comment by comradekingu** [comment]
For a language that allows "email", but then requires "A-bomb" I think the preference should be with having fewer errors in translation. Besides "e-mail" is a little more formal, which isn't out of place when asking for real money to provide a service.
