### ISSUE TITLE
Problem of overlay "source string information" hides history entries

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2928]
See screen shot 
![Pb of overlay](https://user-images.githubusercontent.com/1452146/62310212-4c971600-b489-11e9-8b90-ca2656b8e5d3.jpg)

Taken from this page
https://hosted.weblate.org/translate/keepass-dx/strings/fr/?type=all&offset=309#history

User is not able to "read" the end of sentences because they are "under" the info block when navigator has a zoom.

**Comment by ldmpub** [comment]
Hi,

I use Firefox 68.0.1 (64 bits), don't forget to "zooom" to reproduce.

**Comment by nijel** [comment]
Even if I zoom, it still looks correct for me:

![Screenshot_2019-08-02 KeePass DX Strings - Francouzština](https://user-images.githubusercontent.com/212189/62383785-ebd31080-b550-11e9-8752-53aac5daaada.png)

**Comment by ldmpub** [comment]
Ok, I can not reproduce it either today ;-( ... you can close this issue (without explainations).

Thanks,

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since we observed that this issue may relate to a potential vulnerability, has it been disclosed in CVE already? Hope to receive your reply.
Description of potential vulnerability: Yes. This issue report relates to security because it mentions a problem with overlay source string information hiding history entries. This could potentially lead to a lack of transparency and accountability in the system, making it easier for malicious actors to cover their tracks and exploit vulnerabilities.

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since we observed that this issue may relate to a potential vulnerability, has it been disclosed in CVE already? Hope to receive your reply.

**Comment by nijel** [comment]
@jzySaber1996 How did you come to an idea that an unreproducible display issue might need a CVE?

**Comment by jzySaber1996** [comment]
We're sorry about that. This is the reported result of the automatic vulnerability identification tool, and this issue is tracked by the issue tracking system, so it may have the false-positive results, and we're now collecting the feedback.
Best wishes!

**Comment by nijel** [comment]
@jzySaber1996 It would be great to review your findings before posting comments like this.
