### ISSUE TITLE
Upgrade from 2.20 to 3.0: wrong number (2) of constraints for trans_check

### ISSUE THREAD

**Issue by michaelarlt** [WeblateOrg/weblate#2945]
**Describe the bug**
i have upgraded version 2.13 to 2.17 and then to 2.20. After that i wanted to jump to 3.0 which ist failing due to the migration issue i'm getting

**To Reproduce**
im not sure if this can be reproduced as i think the table structure of trans_check is somehow invalid

**Expected behavior**
Migration should work fine

**Screenshots**
![image](https://user-images.githubusercontent.com/18514062/62690994-09c7c780-b9ce-11e9-8827-55726a347f65.png)
![image](https://user-images.githubusercontent.com/18514062/62691040-206e1e80-b9ce-11e9-9874-d603c4c1ae5b.png)
![image](https://user-images.githubusercontent.com/18514062/62691074-2f54d100-b9ce-11e9-8caf-37377ad1f40d.png)

**Server configuration and status**
Since weblate is not starting properly and crashing due to the migration i can only provide generic informations.
Server Ubuntu 18 LTS, Docker3, weblate dockerized version 3.0.1-6

**Comment by nijel** [comment]
The problem is that Django is now strict on order of constraints, but it didn't used to be in the past and created some of them in wrong order. 

The workaround is to patch Django to ignore ordering for constraints or to fix the indices manually, see https://github.com/WeblateOrg/weblate/issues/1631 or https://github.com/WeblateOrg/weblate/issues/1417, Django upstream isn't going to fix this, see https://code.djangoproject.com/ticket/27826 and https://code.djangoproject.com/ticket/23906

**Comment by michaelarlt** [comment]
Thanks @nijel for the quick reply. I might be able to apply that patch if it was native but since im using docker, its more or less hard for me to apply that. Even im more experienced with mysql statements but postgresql. and i dont not really know what exacly might be missing or maybe is a mess in the table schema.
If you can give me a hint how the table constraints and keys should look like i can fix that manually by removing and recreating them

**Comment by nijel** [comment]
Hmm, looking at your dump, I don't see any duplicate there. In case there are really two and the tool you're using is not showing it, then you can delete the index ending with `_uniq`. Backup is of course recommended prior to this :-).
