### ISSUE TITLE
Improve status widgets page

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2961]
**Is your feature request related to a problem? Please describe.**
The current page listing status widgets has become quite messy over time - with small badges and huge multi language or open graph images.

**Describe the solution you'd like**
Better way to present and select available widgets for use. Maybe using thumbnails.

**Additional context**
See https://hosted.weblate.org/widgets/weblate/

**Comment by comradekingu** [comment]
**Small status badge**
![image](https://user-images.githubusercontent.com/13802408/63134825-78f37c00-bfcb-11e9-8b19-33e066bfb9af.png)
Could be "46% translated", instead of "translated 46%"

**Language racks**
Maybe the ability to generate one with custom colours, in all three levels?
One tri-level on that works for colourblind people would be nice.
Mouseover to arrange by order of completion?
or mouseover to see strings/checks/review status/etc.
Click to go to language in question?

**Small widgets**
These could be visual loading bars, according to completion, maybe dropping the %.
Not sure the pipe/vertical borders do anything (?)
Could be rounded.
Also available in borderless variants.

The stats on https://weblate.org are nice and dynamic.

**Comment by nijel** [comment]
This issue was meant to improve page showing widgets, not really focused on widgets themselves :-). Also the timeline is something we can have after implementing some project management feature which will allow to track these.

>  Could be "46% translated", instead of "translated 46%"

This kind of badge is sort of standard, so better to stick with that, see https://shields.io/category/analysis

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
