### ISSUE TITLE
Copying plural string foregoes markup

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2988]
https://hosted.weblate.org/translate/etar-calendar/strings/nb_NO/?type=allchecks&offset=2

Tried to copy the plural here, ended up with 
"+1 event"

Expected 
"+<xliff:g xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2" id="count">%d</xliff:g> events"

**Comment by nijel** [comment]
Is this about https://hosted.weblate.org/translate/etar-calendar/strings/nb_NO/?checksum=95603a68eb786621 (it's better to share permalink especially in case you fix the checks). There seems to be rather some issue with parsing the file.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported should be fixed by https://github.com/translate/translate/pull/3918.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
