### ISSUE TITLE
Allow users to create projects

### ISSUE THREAD

**Issue by beli3ver** [WeblateOrg/weblate#2995]
Hello,

Is there a way: Group, Role to allow every user to create projects?
Thanks

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed by 4fea246d2c972d11846d231f9826bbc3aad78c03.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by beli3ver** [comment]
When will you release version 3.9

**Comment by nijel** [comment]
It's scheduled on mid-October, see https://github.com/WeblateOrg/weblate/milestone/43
