### ISSUE TITLE
Extend screenshots API [$100]

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3076]
**Is your feature request related to a problem? Please describe.**
The screenshots API is currently limited to listing screenshots and does not support adding new ones.

**Describe the solution you'd like**
Extend API to allow:

* List screenshots per component
* Add new screenshots
* Associate strings with screenshots

**Additional context**
https://docs.weblate.org/en/latest/api.html#screenshots

Blocked by #2831

**Comment by brymut** [comment]
Hi @nijel , having a look at this today. May I please get assigned to it?

**Comment by nijel** [comment]
You're welcome, I've just assigned it to you.

**Comment by brymut** [comment]
Thank you

**Comment by brymut** [comment]
Hi again @nijel , I've finally had a look and come up with some possible solutions. However, I have a question regarding 

> * List screenshots per component

Given the current API organisation and the viewset pattern implemented. Would you also find it fit to add this under the translations component API with the request pattern
`GET /api/components/(string:project)/(string:component)/screenshots/` 
instead of
`GET /api/screenshots/(string:project)/(string:component)/` 
 as per my initial look at this would require fewer changes and subsequently complexity to the API views implementation. 
What do you think?

**Comment by nijel** [comment]
>  `GET /api/components/(string:project)/(string:component)/screenshots/`

Yes, this makes sense to use this approach.

**Comment by jammmet** [comment]
How are you getting on @brymut?

**Comment by brymut** [comment]
Hi @jammmet, still working on some test cases. Unfortunately got overwhelmed with other stuff over the past week but should be submitting a pull request by Thursday

**Comment by mikemassing** [comment]
Hi @brymut, I would be happy to test if needed.

**Comment by jammmet** [comment]
> Thursday

Great. Stay safe in Nairobi (I'm based here). Let me know when you have something to test (I posted the bounty)

**Comment by brymut** [comment]
Hi, @jammmet @mikemassing  finally got a chance to submit the PR, apologies for the delay, it took longer than I would have liked it to because of some previous commitments and the current situation.

The PR should be available now for review if you'd like to have a look and test and stay safe too. 👍
(Nice to know you're based here too 🙂)

**Comment by nijel** [comment]
Implemented in https://github.com/WeblateOrg/weblate/pull/3665
