### ISSUE TITLE
Document how to make things easy for translators

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3084]
Since #2789 we have basic technical guidance to configure translations on Weblate side. It would be great to have also documentation covering this topic - what the developers should do or avoid to make translators job easier.

It should end up here: https://github.com/WeblateOrg/weblate/blob/master/docs/devel/community.rst

**Comment by comradekingu** [comment]
In the style of https://contribute.funkwhale.audio/guides/translate/ or just understand to get the idea of things?

**Comment by nijel** [comment]
I more meant guide for developers/project admins how to make things smooth. Describing individual items from the checklist is certainly useful, but I also wanted to cover things which are not easy to be checked automatically - some of that is already covered by https://docs.weblate.org/en/latest/devel/starting.html, but there are definitely more things needed to build good community of translators around project.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by Bachstelze** [comment]
Heyho
I am collecting some resources for the docu:
- [A brief introduction to writing a post-editing guide](http://www.tcworld.info/rss/article/a-brief-introduction-to-writing-a-post-editing-guide/)
- [MT Post-editing Guidelines](https://www.taus.net/academy/best-practices/postedit-best-practices/machine-translation-post-editing-guidelines)
- http://multitranslation.space/thesis
- http://wiki.languagetool.org/checking-translations-bilingual-texts
- [Improving the Translation Environment for Professional Translators ](https://www.mdpi.com/2227-9709/6/2/24)
- [Recommendations for Translation Environmentsto Improve Translators’ Workflows](https://uhdspace.uhasselt.be/dspace/bitstream/1942/19963/1/TC3715.pdf)
- [The Efficacy of Human Post-Editingfor Language Translation](http://vis.stanford.edu/files/2013-PostEditing-CHI.pdf)
- [Machine Translation Qualityand Post-Editor Productivity](https://www.cs.jhu.edu/~phi/publications/machine-translation-quality.pdf)
- [Human Effort and Machine Learnability in Computer Aided Translation](https://www.aclweb.org/anthology/D14-1130.pdf)
- [Cognitive Demand and Cognitive Effort in Post-Editing](https://www.cs.cmu.edu/~alavie/papers/Lacruz-et-al-AMTA-2014-PEWorkshop.pdf)
- [Predictive Translation Memory: A Mixed-InitiativeSystem for Human Language Translation](https://nlp.stanford.edu/pubs/green+chuang+heer+manning_uist14.pdf)
- [Indices of cognitive effort in machine translation post-editing](https://research-information.bristol.ac.uk/files/55676957/VieiraLN2014.pdf)
- [The impact of metadata on translator performance: How translators work with translation memories and machine translation](https://www.researchgate.net/profile/Carlos_Teixeira19/publication/274955547_The_impact_of_metadata_on_translator_performance_How_translators_work_with_translation_memories_and_machine_translation/links/552d211b0cf29b22c9c4b3c1/The-impact-of-metadata-on-translator-performance-How-translators-work-with-translation-memories-and-machine-translation.pdf)
- [Effects of Word Alignment Visualization onPost-Editing Quality & Speed](https://pdfs.semanticscholar.org/00c6/bbc10fab4ec7c69d8914f31e84249aedba77.pdf)
- [Translation Quality and Error Recognition in Professional Neural Machine Translation Post-Editing ](https://www.mdpi.com/2227-9709/6/3/41)
- [Integrating Artificial and Human Intelligence for Efficient Translation](https://arxiv.org/pdf/1903.02978.pdf)
- [Productivity and quality when editing machine translation and translation memory outputs: an empirical analysis of English to Welsh translation](https://www.degruyter.com/downloadpdf/j/scp.2017.2.issue-1/scp-2017-0007/scp-2017-0007.pdf)

Do you want to write with me the guide?

**Comment by nijel** [comment]
Yes, help with that is certainly welcome.

**Comment by Bachstelze** [comment]
# Building a translators community
Following these recommendations support the creation of a full, multilingual post-editing tool. Good translations are defined through the systemic-functional model of House which aims at a contextual correct translation. Write your own [post-editing guide](https://www.taus.net/academy/best-practices/postedit-best-practices/machine-translation-post-editing-guidelines) and alter these recommendations to fit your own definitions. In most cases the [browser-plugin of languageTool](https://www.languagetool.org/#firefox_chrome)  is useful as the proof-reading tool.

## Localization guide
The `Localization guide` which can be found in the `Insights` menu of each component can give you guidance to make your localization process easy for translators. 

## Terminology management
Post-editing of MT with terminology assignment influences each level of the translation process.
The machine translation system can be adapted to the specific vocabulary and style with a continued training or [neural fuzzy repair](https://www.aclweb.org/anthology/P19-1175.pdf). [Import](https://docs.weblate.org/en/latest/admin/memory.html#imported-translation-memory) your existing translation memory into weblate or create an initial scope with your basic terminology. In the end the lector should be instructed with additional terminology documents to guarantee a good knowledge and output in the field.

example: British English or American English?

## Machine translation
The quality of the automatic translation (often measured with the BLEU-score) correlates with editing time [1]. Choose a machine backend which supports the needed languages and domains. Make clear how the translation backend functions and which quality the post-editor has to expect.

## Review translations
The translations should be reviewed by a second person after the post-editing. With an impartial and competent revisor, the two man rules reduces the errors and improves the quality and consistency of the content.

## Structured feedback
There are many [quality checks](https://docs.weblate.org/en/latest/user/checks.html) in weblate. Pay the lectors to give structured feedback and use it to increase those checks.

## Translation definition
In addition to the mentalistic and impact-based definitions which make a strong reduction, the text-based linguistic approach fits best with the implemented translation methods. A well-formulated theory for translation evaluation is House's systemic-functional model, which focuses on the relation between original and translation. The model assumes that translation is an attempt to keep the semantic, pragmatic, and textual meaning of a text equivalent when crossing from one linguistic code to another.
The degree of quality of a translation is based on the degree of equivalence, the correspondence between the text profile and the text function. Because it cannot be calculated automatically, sufficient information should be collected to enable a uniform human evaluation. The two main parameters of agreement in a corresponding model are the macro-context - i.e. embedding in a larger social and literary context - and the micro-context consisting of field, tenor and mode. 

## Sources
[1] Marina Sanchez-Torron and Philipp Koehn in Machine Translation Quality and Post-Editor Productivity, Figure 1: https://www.cs.jhu.edu/~phi/publications/machine-translation-quality.pdf 
[2] Joanna Best und Sylvia Kalina.Übersetzen und Dolmetschen: eine Orientierungs-hilfe. A. Francke Verlag Tübingen und Base, 2002. Möglichkeiten der Übersetzungskritik S.101 und Folgende
[Translation definition] Kalle Hilsenbek, Gruppenbasierte Umgebung für mehrsprachige Übersetzungsquellen, 7.7 Übersetzungskritik, 2017: http://multitranslation.space/thesis 
[post-editing guide] Sharon O'Brien and Fred Hollowood in MT Post-editing Guidelines, 2010 https://www.taus.net/academy/best-practices/postedit-best-practices/machine-translation-post-editing-guidelines
[neural fuzzy repair] Bram Bulté and Arda Tezcan in Neural Fuzzy Repair: Integrating Fuzzy Matches into Neural MachineTranslation, 2019 https://www.aclweb.org/anthology/P19-1175.pdf

### Draft status
This is my first draft for the technical guidance. Do you think it covers the open topics?
There is probably more documentation, e.g. about the translation definition or the following implementations issues. But I don't know exactly where. Therefore, let us start a discussion!

### Implementation discussion
- dictionary integration for single words which are the critical issue while post-editing. They could be displayed as overview over the POS-types.
- arrange the post-editing interface over the frontend
- integrate  a framework for the text editor to relieve the implementation of edit methods like auto complete and word deletion
- terminology extraction via named entity recognition
- shortcut to show all available shortcuts
- displaying of different, but high quality translation suggestion that are exchangeable.
- allow to instantly change the translation method to the point of printing the selected, parallel text and turning off the computer

**Comment by Bachstelze** [comment]
I conclude that there is nothing to discuss - hopefully in a good sense. Should we expand the `Community localization checklist` e.g. with a project-based terminology definition?

**Comment by nijel** [comment]
Sorry, seems like I've missed previous comment. Going through that right now and it looks reasonable. Can you please create a pull request for the docs so that it's integrated there?

As for the terminology in checklist, I think it will make more sense once https://github.com/WeblateOrg/weblate/issues/243 is implemented.
