### ISSUE TITLE
Make user's email addresses private by default

### ISSUE THREAD

**Issue by di** [WeblateOrg/weblate#3105]
**Is your feature request related to a problem? Please describe.**
After creating a Weblate account (via Github login) and adding a translation to a project, I was surprised to find that my email address (and the email addresses of other contributors) was published in the list of authors in the corresponding PO file for the project.

I was especially surprised to find my personal email address listed, since I use di@users.noreply.github.com on Github to keep this address private, however it seems like this is explicitly prohibited by Weblate (https://github.com/WeblateOrg/weblate/commit/7ddfd55cf70a501945ad541fea5b876e74b0e866)

I understand that Weblate needs a working email address for every account, but I don't recall telling it to use this one when creating my account (I have multiple email addresses on my Github account).

**Describe the solution you'd like**
Ideally all user emails are private by default, not included in authorship attribution in any PO files, and only public (the current behavior) by explicitly opting in.

In addition, if a Github account is associated with a `@users.noreply.github.com` account, the user should be given an option for which email address Weblate should use instead for notifications.

**Describe alternatives you've considered**
I am considering putting our translation efforts on hold until this is resolved, so as not to unintentionally leak our contributors contact details.

**Comment by nijel** [comment]
The usage of name and email in VCS commits is clearly documented in all [legal documents](https://hosted.weblate.org/legal/), so your surprise comes from not reading these.

When registering through GitHub, Weblate chooses primary email and if that is not available, random one is chosen (I think it's the last one returned by GitHub). You can add other email addresses in your profile and choose which one to use.

There is currently no support for hiding user e-mails from the commits. One of the reasons is that gives maintainers way to contact the translators.

**Comment by AwesomeStickz** [comment]
Adding an option to let only the maintainers view emails of translators would be better in my opinion, because that way the translators wouldn't have to worry about everyone being able to view their email address but just the maintainers which seems like a valid thing to me, because in most cases I guess only the maintainers might want to contact the translators.

But it could also be possible that translators wants to contact translators regarding translations so having it as both project wide option for maintainers to set as public/private for all their translators and translators setting just for themselves would be great I guess

**Comment by maboroshin** [comment]
This feature is under development for 2021-2022 : https://github.com/WeblateOrg/weblate/issues/6508

I am surprised that there is no other option than unnecessary disclosure of personal data.

Weblate's legal document states.
> 6. Your rights :<br>
>Restrict the Personal Data processing

This was not set forth by Weblate. This is derived from `Article 18 : Right to restriction of processing` in GDPR. In this case, perhaps Article 18(d). He seeks nondisclosure, because there is no benefit from being public.

https://github.com/WeblateOrg/weblate/issues/3105#issuecomment-541449372 : 
> One of the reasons is that gives maintainers way to contact the translators.

I don't know if he consented to his personal data being used for this purposes. Clear consent is required for each purpose of use of personal data in GDPR. And, There is no easily understandable information that the e-mail will be widely publicized in Weblate's legal document. In any event, he claims the right of restriction.
