### ISSUE TITLE
Removing push URL should remove related alerts

### ISSUE THREAD

**Issue by ariasuni** [WeblateOrg/weblate#3118]
**To Reproduce**
1. Add a non-working push URL in component (Manage → Settings → Version Control →  Repository push URL)
2. Try to push (Manage → Repository maintenance → Push)
3. The push fails (this is normal). See that there is an alert.
4. Redo step 1 but remove URL instead
5. The alert is still, is annoying and can’t be removed

**Expected behavior**
The alert disappears.

**Server configuration and status**
Weblate 3.7

**Additional context**
This is a problem that’s annoying if you have the right on a component but not on the instance, because you can’t add the SSH key of the host I’m trying to push to, but if you notice that too late then you’re stuck with your eternal alert.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed in d086a8f12028d1ddd6c2a958f6b2741194723bc4, please upgrade.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ariasuni** [comment]
Oh sorry, I’m not the admin and thought Weblate was up-to-date. I’ll be more attentive next time to avoid making you lose time. Thanks!
