### ISSUE TITLE
No language consistency for new components

### ISSUE THREAD

**Issue by aparcar** [WeblateOrg/weblate#3122]
**Describe the bug**
I enabled the language consistency plugin which creates missing PO files after enabling it. However when a new component is added, no additional PO files are added.
To solve this I have to uninstall the addon and re-install it to create missing files.

**To Reproduce**
1. Setup component
2. Install *language consistency*
3. Enjoy automatically created PO files
4. Add another component
5. No new PO files added

**Expected behavior**

The plugin should be triggered every time a new component is added.

**Screenshots**

**Server configuration and status**
I'm using hosted.weblate.org

**Comment by nijel** [comment]
The addon triggers on adding new languages and is also executed daily, so it might take some time to add new languages in this case. It could be certainly improved to act immediately in this case.

**Comment by aparcar** [comment]
Thank you for this clarification, daily works for me, feel free to close this issue.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by documenting this behavior. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
