### ISSUE TITLE
Show different string lengths of same term/message together (responsive design)

### ISSUE THREAD

**Issue by fennibay** [WeblateOrg/weblate#3141]
**Is your feature request related to a problem? Please describe.**

For software running on different form factors, there is a common practice to define texts in several shapings differing in lengths (e.g. Monday->Mon->M). The software following responsive design principles then picks up the according text length according to the current form factor.

Typically the software follows a key convention for such texts such that the keys have a common part and a varying part such and short/medium/long as a suffix.

However, the translators do not see these texts together, each entry is shown as an independent entity. So translation errors can happen such as:
* not following length rules (e.g. short translation longer than the medium translation)
* not following the same semantic for different lengths of a message.

So, the translators need a way of seeing different shapings of a term/message together.

**Describe the solution you'd like**

* The keys follow a certain pattern such as `<key><separator><shaping>`, e.g. `monday#s`
* The separator or a regular expression for defining shapings in keys can be configured in component settings in Weblate
* Weblate then will group/show these entries always together
* Weblate doesn't need to interpret shapings further, as the software developer can define different max-lengths for each shaping entry

**Describe alternatives you've considered**

Alt. 1: If the message has multiple shapings, provide a `Shapings` tab similar to the `Nearby strings` tab underneath, and show other shapings of the message there, so the user knows immediately there are other shapings to consider. Mock screen:

![image](https://user-images.githubusercontent.com/30393701/67404382-989eb600-f5b3-11e9-81ae-5e0b70c1c072.png)

Alt. 2: Show shapings in the upper part of the window, similar to plurals.

Alt. 3: Provide a `Nearby keys` tab similar to the `Nearby strings` tab, showing the nearby strings based on key proximity rather than physical proximity in the translation file.

Alt. 4: (No Weblate change needed): Order the translation files by keys so that nearby strings is the same as nearby keys.

Alt. 5: Extend the addon interface of Weblate to be able to customize translator frontend, so such functionality can be added on-demand.

**Additional context**

Example project: [locale file from npm moment](https://github.com/moment/moment/blob/develop/locale/en-gb.js), uses xxx, xxxShort, xxxMin.

**Comment by rhofer** [comment]
Assuming we go for Alt. 1, I propose the following solution approach:

### Component configuration

Add an additional configuration option to the component configuration, which enables handling of *Shapings* based on regex expressions. If regex is set then component has shapings else no treatement of shapings. Mock screen proposal:

![Shaping-ComponentSettings-mock](https://user-images.githubusercontent.com/8058166/70772174-037a9b00-1d74-11ea-986d-2f918bf24474.png)

Since *Shapings* is not standardized in any format / library / etc. it has to be a convention between SW project and Weblate integration (means dev's to talk to weblate ops), where from an agreed regex has to result.

### Component handling

#### Example 1

Assumption: 
- regex: `/#[S|M|L]/`
- format: JSON
- example keys
  - key1: `app.dialogue.key`
  - key2: `app.dialogue#S.key`
  - key3: `app.dialogue#M.key`

Procedure:
- Weblate is scanning all keys with given regex.
- It hits e.g. key2 where `#S` is found
- The key is reduced by the *Shaping* expression to derive the base key: 
  - key2: `app.dialogue#S.key` >> remove `#S` >> base key found: `app.dialogue.key`
- The base key is then somehow marked with *has shapings*
- The same for `#M`

Assuming with Alt. 1, we have now a separate tab for *Shapings*. When translating key1, it matches the base key of key2 and key3. Hence, key2 and key3 are shown in the *Shapings* tab. What also applies when translating key2 or key3.

Appearence:
- For *Shapings* we need then an additional information in the translation area and also in the *Shapings* tab. Besides context information to show *Shapings* information as well.
- Weblate shall take the *Shapings* indicator directly from regex (in given example `S`, `M` or `L`)
- Weblate shall not interpret this information, just pass through. It is not expected that weblate knows what S, M and L means. This also has to be communicated to translators, by convention.

#### Example 2 : i18next

For i18next we already have a suffix for plural detection (`key_plural`). Assuming we add *Shapings*, it could look like `key#M_plural`. Then the order of treatment should be:
1. Detect plural first (cut off ‘_plural’), results in `key#M`
2. Then, secondly, detect shaping, means `key#M` would then be found with regex `/#[S|M|L]/` or even `/#[S|M|L]$/`

#### Example 3: suffix

In the example given in issue description above, we could also do a setting form moment.js with e.g. regex `/(Short|Min|)$/`, what detects the suffixes applicable for shapings.

### Documentation

Weblate documentation to provide best practice examples for good regular expressionf for *Shapings* detection.


@nijel would this hit a feasible way to implement with solution generic enough to cover for all variability needed?

**Comment by nijel** [comment]
Thanks a lot for providing such detailed analysis, I think it's feasible approach.

**Comment by fennibay** [comment]
Hi @nijel, thank you very much for this feature.

I read the [documentation](https://github.com/WeblateOrg/weblate/blob/master/docs/devel/translations.rst#string-shapings), and one point I'm not sure about is whether you allow empty strings.

In the suffix identification case, I see that the key `month` without a suffix is shown as an example, but the regular expression wouldn't actually match that. For this the regex has to be `(Short|Min|)$` instead of `(Short|Min)$`

**Comment by nijel** [comment]
That's intentional, because we use the regex to identify shapings. With `(Short|Min|)$` *all* strings would match and that's not really useful. Using `(Short|Min)$` only the *additional* shapings are matches and the base one is automatically included. Probably the docs is not clear in this, as it's not described in details, but only shown in the examples.

**Comment by fennibay** [comment]
OK, now it's clear for me. Thanks for clarifying so quickly. 👍

**Comment by nijel** [comment]
I've now also clarified the docs.

**Comment by rhofer** [comment]
@nijel many thanks for this feature. As far as I tested, this works as expected.

Whilst testing, I saw at the beginning that no all keys with a common base key are found and added to the shaping list. Is the search for shapings based on the whoosh search index? If yes, would it be wise to recreate this index by executing `./manage.py rebuild_index --clean --all` ?

**Comment by nijel** [comment]
No, it doesn't use this index. Can you please open separate issue for this? Did it happen when adding shapings configuration to the existing component?

**Comment by rhofer** [comment]
Yes it happened when adding shapings to existing component. At the beginning it said that only 1 exists (of 2). After waiting a while (navigating around, waiting, doing something else, refreshing weblate, ...) it correctly brought up 2 of 2. So it's not a bug (I guess). Just wanted to doublecheck, whether you'd expect this behaviour.

**Comment by nijel** [comment]
Yes, it's expected to happen in background.
