### ISSUE TITLE
Antispam protection improvement

### ISSUE THREAD

**Issue by dakur** [WeblateOrg/weblate#3189]
**Describe the bug**
I tried to write a comment for few translations to our translator that I need him to review my changes. When I was submitting about fifth comment, antispam protection logged me out with message below.

![image](https://user-images.githubusercontent.com/9862581/68376250-99ede800-0148-11ea-9a2b-35b05429c1a5.png)

Even if I log in again, I'm still not able to submit a comment, it logs me out again.

**To Reproduce**
1. Make comments to 5+ translations.
2. See error

**Expected behavior**
Distinguish user-actions from spams.

**Screenshots**
Above.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by dakur** [comment]
@nijel I don't think raising up limit with 1 guess more is a fix. Even if it would be +10, it just moves the problem few minutes later. Proper fix is to recognize user interaction, not to rely on number of guesses.

**Comment by nijel** [comment]
It's not 1 more, it's also reducing the period for the limit from 600 seconds to 60 seconds.

Do you have any suggestion on recognizing user interaction without relying on third parties with problematic privacy reputation such as ReCapcha?

**Comment by dakur** [comment]
@nijel You can investigate user account's history for example. You can create some algorithm that will label user with "normal history" or "suspicious history" tag. Then in case of the first one no limit would be applied and in case of the latter additional confirmation would be required (for example change of password + e-mail reactivation or something like that). But this needs more research on how other people solve this problem and what conditions are good enough and not annoying in the labeling algorithm.

**Comment by nijel** [comment]
I think most projects either do nothing or rely on tools like reCAPTCHA, which does the hard word of analyzing user behavior for them. I'd like to see some existing implementations of this, because it's not really something we can build from scratch ourselves.

**Comment by dakur** [comment]
@nijel Dunno, I did not investigate it. But my experience tells me it is not so black&white - nothing or recaptcha.

However, I would think about what was the antispam created for? I can for example create a bot, which will add annoying comment to translations every 1 or 10 or whatever minutes. Or 1000 comments in 2 seconds. As long as the timeout interval is coded in source code of Weblate on GitHub, whatever it is, I can parse it and change the limit in my malicious script or accomodate to any new code.

From my point of view, core of the problem is elsewhere: have you or anyone experienced spam in Weblate? If so, what was the bot's behavior? Flooding with thousands of comments in a minute, or added few in a day...? Does Weblate allow anonymous access to translations as well? Do the antispam behaviour differ for such users? I do not know your software well, so maybe I ask stupid questions, but they are essential. Based on this knowledge and experience, you can do qualified decision about antispam form. If no spam has occured to Weblate, whichever antispam protection is just blind-shot and will just annoy users.

Sorry, if my post sounds offensive, it does not suppose to be. I appreciate your work a lot, it allowed us to ship complete translation of our quite big application in just two weeks! Just trying to fit in words my thoughts roughly.

**Comment by nijel** [comment]
Yes, you can certainly workaround that limitation with a bot, but it will reduce possible damage. The supposed setup is to have limits high enough that regular user would never hit them, while bot firing requests would hit them soon. To be honest one of reasons for the rate liming here was to avoid getting reports on HackerOne about lack of rate limiting on comments, suggestions or translations.

The only anonymous content we accept by default are suggestions and there is quite some spam. But there is also Akismet involved in checking that content and it blocks most of that (we've seen thousands of spam posts in a month). In this case some privacy is sacrificed for the anonymous users.

**Comment by rhofer** [comment]
@nijel @dakur I see you're discussing a generic solution for anti spam, which might be hard to achieve when trying to cover all use cases.

Just to give you some insights in my use case. I have weblate self-hosted for my company I work with. Therefore, I even would not need any kind of rate limits since this instance is "locked-down" by user management and automatic group assignment:

- anonymous not allowed
- user registration and login done via our Oauth2 provider only (no email registration)
- regex for automatic group assignment detects whether newly registered user is member of the company based on our Oauth2 authentication success message.
- In case we have external translators (not member of the company) we do a separate manual onboarding (manual grant permissions in weblate by admin)

@nijel Depending on my use case, we encountered a situation where a translator was searching for a specific substring, which was still pretty odd in our landscape. In order to start discussion on it, he intended to attach the same comment for the let's say 20+ occurrences of this string. With this, he easily exceeded the 6 in 60sec limit. Hence, I may need to adjust the rate limits for my use case individually. Could we expose the rate limits as env variables (docker deployment), so that I have the chance to further tune it for my purpose?
- default: as per your settings in the code
- Override: only if variable is set.

**Comment by nijel** [comment]
Looking again at the limits, I see no good reason to have comments limit lower than glossary or translate one, so I've increased it to be same. For your use case, it would be better to have support for bulk operations, see https://github.com/WeblateOrg/weblate/issues/3136

**Comment by rhofer** [comment]
Yes, thanks. That's a good idea to have such things handled in bulk changes as noted in #3136

**Comment by rhofer** [comment]
Many thanks for the rate limit adaption. Tested with 3.10.3, works now as expected.
