### ISSUE TITLE
Copy feature for assistant languages

### ISSUE THREAD

**Issue by milupo** [WeblateOrg/weblate#3250]
Hi,

I'm LibreOffice translator for Upper Sorbian and Lower Sorbian. As I translate into two similar languages I could often copy translated strings from one of them into the other one, e.g. an Upper Sorbian string into Lower Sorbian. Until now I have to select the string of the assistant language by mouse. That's a little inconvenient. So implement a copy button for assistant languages, please, as it exists for English.

Thanks in advance,

Michael Wolf

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed by bab9a4e7bedbd9a0054e9a84b7f56adec5e753a2.

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by milupo** [comment]
Thank you nijel for the prompt execution.

**Comment by nijel** [comment]
Well it was fixed month ago ;-).

**Comment by milupo** [comment]
I think it is depending on what Weblate version LibreOffice is using. Currently it is still version 3.8.
