### ISSUE TITLE
Ability to disable auto update

### ISSUE THREAD

**Issue by hefee** [WeblateOrg/weblate#3341]
For Tails we are using Weblate with a set of scripts to integrate Weblate into the rest of our infrastructure [1]. Therefore the `update-remotes` cronjob should not be run. Currently we use a broken git url to make sure, that Weblate can't update the repository on it's own. But it is quite annoying to see always the alerts:

    The VCS repository has many changes compared to the upstream. Please merge the changes manually or set up push to automate this.
    --- 
    Weblate could not fetch upstream changes when updating the repository.

I searched around to lean about celery, but I haven't found a way to disable task, that's why  I think it needs to be supported by Weblate itself. If it is possible to disable cronjobs outside touching the Weblate code I would also be happy. 

[1] https://git.tails.boum.org/puppet-tails/tree/files/weblate/scripts/cron.sh

**Comment by nijel** [comment]
The task is currently hardcoded:

https://github.com/WeblateOrg/weblate/blob/d75addfd133b91767733910d0ba0d19e0ce40409/weblate/trans/tasks.py#L375-L377

But it could certainly be made configurable. We already do this for backups:

https://github.com/WeblateOrg/weblate/blob/d75addfd133b91767733910d0ba0d19e0ce40409/weblate/utils/tasks.py#L97-L100

**Comment by nijel** [comment]
There already is [AUTO_UPDATE](https://docs.weblate.org/en/latest/admin/config.html#auto-update) setting which configures whether local repos should be updated. Maybe we should have one setting for all that instead of adding another one. Tentative choices: 

* `none` - no daily updates at all
* `remote` (also accept False for backwards compatibility) - update remotes
*  `full` (also accept True for backwards compatibility) - update remote and merge working copy
