### ISSUE TITLE
Po minification addon

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3350]
The structure of po files may have a big impact on the git repository size and change readability.

Here is a Python script to allow po minification: https://libvirt.org/git/?p=libvirt.git;a=blob;f=scripts/minimize-po.py;h=c3052297212e7416fd94866af3b3e5348a41b503;hb=HEAD

This work was done by Daniel P. Berrangé and documented there: https://www.berrange.com/posts/2018/11/29/improved-translation-po-file-handling-by-ditching-gettext-autotools-integration/

I assume this could be a feature of the command line tool.

**Comment by nijel** [comment]
I don't see much point in doing this in Weblate. In case you want to have minimal PO files in the repository, you have to do that before Weblate is involved. Doing that in Weblate will not have impact on the repository size (actually it will just *increase* the repository size, because it would create additional commit removing this information). 

Most of the things can be controlled by Gettext directly:

* ``--no-location`` removes filenames with location, but that one is also useful context for translators
* ``--sort-output`` sorts string, but makes it harder for translators as nearby strings in the code (and this presumably in the UI) are no longer nearby in the PO file
* obsolete units can be removed by ``msgattrib --no-obsolete -o messages.po messages.po``, this is something what might be useful in Weblate

**Comment by Jibec** [comment]
I wanted to share with you this upstream method I never saw before. I am unsure how to really make use of it.
But maybe, weblate could be the only one to contain pot and real po? The upstream project would only pull minimized files?

**Comment by nijel** [comment]
Basically what they use is human readable MO - it contains only things needed at runtime, but removes anything what might be useful for translators. Maybe it's then better to pull MO files directly instead of inventing something in between.

Once https://github.com/WeblateOrg/weblate/issues/3263 is implemented, there will be an option to have bilingual PO files in Weblate and export anything you want. Right now however the PO exports include as much metadata as possible (including suggestions or comments done in Weblate).
