### ISSUE TITLE
Call "shapings" something else

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3484]
https://docs.weblate.org/en/latest/devel/translations.html#labels
String clustering is what I understand this as. Could be there are even more descriptive titles to be had.

A string cluster, forming with others many string clusters, by the process of clustering strings / string clustering.

**Comment by nijel** [comment]
We were considering this as well, but [clustering](https://en.wikipedia.org/wiki/Cluster_analysis) is already widely used in machine learning and that could be confusing as well.

PS: The actual docs link is https://docs.weblate.org/en/latest/devel/translations.html#string-shapings

**Comment by fitojb** [comment]
I was thinking of “string variants” or “forms”.

The term “shaping” has a specific meaning w.r.t. the formation of words in complex scripts like Devanagari and Arabic.

**Comment by comradekingu** [comment]
String grouping?

**Comment by nijel** [comment]
Maybe @fennibay and @rhofer could provide some input as well?

**Comment by rhofer** [comment]
@nijel many thanks for taking us into discussion.

First at all, "Shapings" was an input from our side (@fennibay and @rhofer), we defenitely do not need to enforce this term. If somebody has a better proposel how to name it and to better reflect the semantic in behind.

## Background

The basic definition of the semantic of a term is given in weblate with the combination of *context* (usually the key/msgid), *source* term (e.g. `en`) and *translation* (any other language). Beyond this, depending on the format, we may have more descriptive information (e.g. comment), screen shots or even somewhere a live preview of the underlying SW application.

In some cases we need to **maintain and keep the semantic (context) and need to provide different string lenth**, may call it tailored or shaped string length.

- **Use Case: responsive design**: assuming we have an HTML5 application accessed via webbrowser from different devices (Desktop PC, Tablet, Smartphone), we need to encounter for responsive design (e.g. with bootstrap). Therefore, we want to provide different string length by keeping the semantic but encountering for the variable real estates (display). What may results in `myKey` to use on Desktop, `myKey#M` to use on Tablet and `myKey#S` to use on Smartphone.

- **Use Case: cross application alignment**: In a broader system context (multiple SW applications and devices to shape a system), we need to encounter for a Windows SW/Tool (e.g. written in C#, .NET), a HTML5 application or even an embedded device with display (e.g. old fashioned low sophisticated monochrome dot matrix LCD's). Since all of them are part of the same system, we want to use a common semantic by aligning the terms we use. Therefore, we have a kind of central pot, where such strings are maintained. Again, for keeping the semantics but encountering for the system participants, we need to provide different string length as we called it *Shapings*.

## Discussion

Technically, the proposals above are all correct (according my opinion). But we should rather go for a user centric term, which is crisp and clear about what is meant for a translator.
- String clustering: yes it clusters string but for what purpose?
- String grouping:  yes it groups string but for what purpose?
- String variants: yes it provides variants but for what variability does it encounter?

(Thinking more about this, technically it is less a *sting* clustering, but more a *context/key* clustering.)

Hence, we're looking for a title which says that
- we have here a set of strings, all belonging together b'cause they have the same base context, hence fulfilling the same semantic, but have a certain variability, in this case: different string length.

From this PoV *Shaping* is quite appropriate, at least when having a look at possible German translations of it provided by e.g. dict.leo.org (I'm native german speaker), what results in "Gestaltung", "Formänderung", "Formen" or "formgebend", "formgestaltend". Hence it implies that we only change the string's shape / form across different keys (in this case the string length) but keeping the semantic. (In mechanical terms: we keep the base material and its base properties but provide it in different shapes).

Furthermore, *Shapings* is generic enough, so that depending on the related SW project, exposed as translation component in weblate, it could be individually decided, what exactly is the variability part encountered for with the term *Shaping*. This could be (just ideas, I don't know whether all make sense):
- Variable string length (my use case)
- Writing styles (normal writing (`myKey#normal`); all capital characters (`myKey#CAPITAL`))
- Line breaks (without: `myKey#oneliner`, with: `myKey#linebreaks`)
- ...

## Proposals

Based on the background above, maybe the following terms could be appropriate:

- Shapings
- Shape variants
- Form variants
- Formings (does this make sense? Is this english?)
- Formation(s)
- Formatting (could be misunderstood as italic, bold, underline, ...)

Any other proposals?

**Comment by fennibay** [comment]
Thanks @nijel for involving us and thanks @rhofer for the comprehensive explanation.

Looking at the proposals, I'd favor "form variants", or simply "forms".

**Comment by comradekingu** [comment]
So if strings is a sort of link, could this be nets? Many links form a net?

**Comment by nijel** [comment]
This does group strings based on their keys. In the UI it looks like:

![](https://docs.weblate.org/en/latest/_images/shapings-translate.png)

The documentation is here: https://docs.weblate.org/en/latest/devel/translations.html#string-shapings

To add some proposal, how about "Variants"?

**Comment by fitojb** [comment]
“Variants” sounds good to me.

**Comment by orangesunny** [comment]
I am up for "Variants".

**Comment by rhofer** [comment]
"Variants" is fine to me, as well. I'd interpret this as "there are variants available for the same context". Furthermore, it is also agnostic to what is the exact type of variations to the context. Hence, each component could define it differently.

@fennibay what do you think?

**Comment by nijel** [comment]
Good, seems like we've reached a consensus after few months :-). The PR with the change is at https://github.com/WeblateOrg/weblate/pull/3913
