### ISSUE TITLE
Use PO file as translation template

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#3531]
Actually, only POT files are fully supported as template (PO files as templates don't work very well...)
This should fix also this error for PO files:
![immagine](https://user-images.githubusercontent.com/9463142/75435402-400d6a00-5953-11ea-9764-073b0b11c036.png)
or this one:
![immagine](https://user-images.githubusercontent.com/9463142/75436218-7f888600-5954-11ea-9801-f20f0fa96696.png)

**Comment by nijel** [comment]
What kind of template do you mean? For new translations, either PO or POT should work just fine (Weblate removes any existing translations). For monolingual it has to be PO, because POT isn't supposed to contain translations, but I don't think there is anything what would limit using POT here.

In case you really need the Italian file even if you are translating from Italian, you can ignore in using language filter in the component settings.

**Comment by maicol07** [comment]
At the moment I switched to POT but now I get this error:
![immagine](https://user-images.githubusercontent.com/9463142/75558641-6827c680-5a42-11ea-8255-180034eff23e.png)
The suggested solutions didn't work

**Comment by maicol07** [comment]
Tried POT works very well. I think that PO don't work because Weblate recognizes the file also as a translation file for Italian, in addition to template file

**Comment by nijel** [comment]
For "Template for new translations" it doesn't matter whether it's existing translation or not.

BTW: Are you using bilingual or monolingual translations?

**Comment by maicol07** [comment]
Bilingual
