### ISSUE TITLE
Lack of documentation and proper views using social_auth SAML backend

### ISSUE THREAD

**Issue by M0Rf30** [WeblateOrg/weblate#3532]
I'm trying to connect a Weblate instance to a SAML service (OKTA) and I'm facing some problems. I'm using the social_auth official doc, but also because of my lack of experiences in setting up a configuration like this, I don't know if my suggestions are going in the right way.

I will upload my configuration in these days. The question that I have. Is possible to configure a views.py and urls.py in a weblate docker environment only using settings-override.py? If not, or not so easily like for other providers, here I want to suggest the introduction of proper view and url settings to use the **saml_metadata_view** as suggested [here](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/saml.py) and introduces some references to SAML in the official documentation of this amazing project named Weblate.

**Comment by nijel** [comment]
Currently, it's not easily possible to do such customization in docker - the settings override can be used for settings, but cannot customize URL routing. The best approach probably would be to have such integration ready in Weblate so that only configuration is needed.

Just for the reference adding link to the python social auth docs: https://python-social-auth.readthedocs.io/en/latest/backends/saml.html

**Comment by nijel** [comment]
There seems to be some issue with SAML support in social-auth as well: https://github.com/python-social-auth/social-core/issues/446
