### ISSUE TITLE
Pushing changes from Weblate

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#3533]
**Is your feature request related to a problem? Please describe.**
Several times I see people hit problems when configuring pushing changes out of Weblate. The most usual problem is using https without credentials, which ends up with:

```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
 (128)
```

**Describe the solution you'd like**
Better guidance to users how to configure this properly. There is documentation covering this, but it's probably not easy to reach as people ending up asking instead of figuring this on their own.

**Additional context**
* https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-hosted-weblate
* https://docs.weblate.org/en/latest/vcs.html#https-repositories

**Comment by probonopd** [comment]
I am also getting

```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
 (128)
```

* How is Hosted Weblate supposed to get its permissions to push something into a GitHub Repository? Doesn't one need to enter a GitHub Token somewhere into the Weblate GUI? (Where is this documented?)
* Alternatively, how exactly does one need to set up hosted Weblate so that it creates (and appends to existing) GitHub Pull Requests instead of trying to push?

Unfortunately the documentation hints at those things but I did not find a concise description on how to set that up.

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/vcs.html#vcs-repos and https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate
