### ISSUE TITLE
"Update PO files to match POT (msgmerge)" addon doesn't trigger "Squash Git commits" addon

### ISSUE THREAD

**Issue by di** [WeblateOrg/weblate#3707]
**Is your feature request related to a problem? Please describe.**
We are currently attempting to use these two addons:
* "Squash Git commits"
* "Update PO files to match POT (msgmerge)"

We need to use the former to squash "all commits into one", because otherwise the merge strategy for our repo (squash & merge) produces merges conflicts for the weblate remote, requiring it to be manually reset.

However, commits from "Update PO files to match POT (msgmerge)" are not being entirely included in the squash, so if both addons are active in a PR, we sometimes get two commits ([example](https://github.com/pypa/warehouse/pull/7769)).

**Describe the solution you'd like**
All commits squashed into one commit regardless of addon.

**Comment by nijel** [comment]
Can you please keep it one problem per issue? That way it's much easier to track. 

Anyway the squashing doesn't work when the msgmerge is last operation on Weblate because it doesn't trigger the squash addon (see https://github.com/WeblateOrg/weblate/issues/3708).

We do no processing of commit messages in the squash addon. But adding `Co-authored-by` certainly makes sense. The messages are simply retrieved by `git log` right now:

https://github.com/WeblateOrg/weblate/blob/3c2c3143b1e246ab49abbd0034ad5836f13dd361/weblate/addons/git.py#L47

**Comment by di** [comment]
> Can you please keep it one problem per issue? That way it's much easier to track.

Sorry. I split this into #3709.

**Comment by di** [comment]
I noticed that after https://github.com/pypa/warehouse/pull/7769 got rebased a few times that it eventually got squashed into one commit, and the last commit was from the msgmerge add-on. Was this issue fixed or was it just a fluke?

**Comment by nijel** [comment]
It depends on ordering:

* Squashing happens after translation commit
* msgmerge us done after repo update

So in case you are looking just after msgmerge, the commit won't be squashed, but once some translation is commited after it, it will get squashed.

The technical reasons for this are explained in https://github.com/WeblateOrg/weblate/issues/3708

**Comment by Jibec** [comment]
Thank you for fixing this :)
