### ISSUE TITLE
Add PostgreSQL to list of used projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3712]
PostgreSQL should be in https://hosted.weblate.org/about/
Read the Docs https://github.com/readthedocs/readthedocs.org?
Docker, OpenShift, and Bitnami ?

**Comment by nijel** [comment]
This currently lists Python modules and (some) command line tools used by the instance. It probably makes sense to list database or cache backend here (we already do that partly in `list_version` CLI):

https://github.com/WeblateOrg/weblate/blob/70730c8391fe20f0c585dc7ac2bb1768fd1ba0c9/weblate/trans/management/commands/list_versions.py#L40-L73

The services used by the project are listed here: https://weblate.org/en/donate/#tech

**Comment by rajat641** [comment]
Hey, @nijel / @SaptakS  - Please assign it to me. I want to work on this.

**Comment by nijel** [comment]
Great, you're welcome.

**Comment by rajat641** [comment]
Hi @nijel ,
I have started working on this. I have a few points to clarify:

1. Do we have to show the PostgreSQL version on about page or just the database we are using?
2. `db.connections.databases` don't have a version number and so to do get the version we have to do something like `db.connection.cursor().connection.server_version` for PostgreSQL and convert it a proper version string. I doubt if it would work for other databases as well. Here is a link to understand more - https://www.psycopg.org/docs/connection.html#connection.server_version 
3. I'm assuming to show only database and cache services. Please let me know if any other important service is to be shown. Currently, `list_version` shows this:
![image](https://user-images.githubusercontent.com/8374949/82266226-ffa00580-991d-11ea-932c-8e00d2d4a995.png)

Please clarify them so that I can wrap this soon.

**Comment by nijel** [comment]
Versions for PostgreSQL and Redis are probably good enough. As for database backends there is MySQL supported as well, you might add it in case it's not that hard.

**Comment by rajat641** [comment]
Hi @nijel , Thanks for clarifying the doubt. I'll try to wrap by 9:00 PM MST tomorrow.

**Comment by rajat641** [comment]
Hi @nijel , I am done with adding database backends(Postgresql/MySql) but I realized that cache service i.e Redis is already present on [https://weblate.org/en/about/]() as Django Redis.
![image](https://user-images.githubusercontent.com/8374949/82535271-7ba37480-9afb-11ea-9292-fc92d10e09c2.png)
Please let me know if I have to still add it or it's a different thing altogether.

**Comment by nijel** [comment]
It lists version of the django-redis module, not version of the redis server.

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/weblate/pull/3929
