### ISSUE TITLE
Use string source location from a master .pot file if missing in .po

### ISSUE THREAD

**Issue by berrange** [WeblateOrg/weblate#3895]
**Is your feature request related to a problem? Please describe.**
I have a C gettext based project, where `po/*.po` contains the translations, and `po/$appname.pot` contains the master translation template. 

The .pot file contains source location information for all 'msgids'.

The individual `.po` files have source location removed, as this information is considered a redundant duplication of what is already present in the `.pot` file that adds to the size of the git repo for no gain, and harms the signal/noise ratio of any commits updating the `.po` files.

The intent is to never modify the `.po` files in upstream in order to eliminate conflicts with commits that weblate makes to the `.po` files. Thus upstream will just periodically update the `.pot`, and not run `msgmerge` for the `.po` files.

Instead the `msgmerge` add-on is enabled in weblate so that it will update the `*.po` files when new strings appear in the `.pot`.  The `Remove locations of translated strings` option is to used to prevent weblate re-adding source locations when it does this update.

The end result though is that when looking at the strings needing translation for a language in the weblate UI, no information about the source location is presented AFAICT. This is not good for translators, as they lack context if they need to understand more about the strings being translated.

I presume this same problem would be present even if not using the `msgmerge` add-on  in weblate at all, and letting the project run it upstream to update msgids in the `.po` files. So the `msgmerge` add-on and its `no location` option are probably tangential this problem.

**Describe the solution you'd like**
When the `.po` file has no source locations, the source locations in the `.pot` file mentioned for the  `Template for new translations` setting could be used in their place.

**Describe alternatives you've considered**
Even though the `.pot` file stored in git has locations present, this information is still liable to be out of date. Source locations can change after any single commit, so the only way to ensure freshness would be for the upstream project to re-generate the `.pot` on every commit. This is not very desirable as those updates have poor signal/noise ratio with locations changing very frequently.

The ideal situation is for weblate to have 100% up to date source string locations at all times. 

It isn't practical for weblate to run the application's actual build step to re-generate the `.pot` file itself, as there are so many different build systems involved and some of them can be insanely slow or have non-trivial dependencies.  Many projects, especially those on GitForges, have some kind of automated CI system. It is potentially quite easy for such a CI system to publish a new `.pot` file on a URL. Weblate could periodically fetch this URL, and this new .pot could then be used as the data for string source locations.

**Comment by nijel** [comment]
Right now, Weblate doesn't parse POT files at all when loading the translations (there is no need for that).

**Comment by berrange** [comment]
Potentially it would not need to parse the POT directly. IIUC, it reads/writes the .po files directly in the git repo. Perhaps it can use msgmerge "on the fly" so instead of reading & reading the .po files, it runs msgmerge and reads its output (thus adding locations which are not in git), and likewise when saving, run msgmerge to write its output (thus preventing locations being committed back into git).

**Comment by berrange** [comment]
Thank you for your work to implement this feature request ! I'm looking forward to seeing it when it gets rolled out to the live servers.

**Comment by nijel** [comment]
It's already deployed on Hosted Weblate and will be part of the 4.3 release.

**Comment by echoix** [comment]
Tell me if I need to open a new issue. I’m wondering if the changes of the PR that fixed this issue still exist in future versions (at least in 5.4.3). I tried looking at the blame of the source code, and multiple chunks are still there, so I suppose this feature still works. However, that’s not what I’m observing, in a self-hosted weblate instance. (I’m not the one that can update weblate version by myself). I was experimenting to use the "weblate.gettext.msgmerge" addon to remove the locations from the .po files (I read that in the latest 5.13, it isn’t an addon anymore), and only keep the ones in the .pot, and still be able to see the source string locations when translating. But the "Source string location"  line is simply not present for the components that have the "Remove locations of translated strings" option checked. 

One last thing I didn’t try yet, was to have the .po files with no_location be merged in the main branch and received by weblate when the repo changed. I wanted to try and make it work before doing the real commits.

My goal would be to reduce churn when line numbers are updated, since that information is duplicated in all languages, but the .pot files already contain it, are kept updated, and the .po files are already kept in sync with the msgmerge addon. With that, reviewing the PRs would allow us to (almost only) see the real string and translated trying changes, not hundreds of line number changes.
