### ISSUE TITLE
No way to open failing checks in new tabs

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3938]
![failingchecks](https://user-images.githubusercontent.com/13802408/82785204-a2daa880-9e51-11ea-98f7-bb16b65e6491.png)
The mouseover looks like this
![image](https://user-images.githubusercontent.com/13802408/82785327-ecc38e80-9e51-11ea-8827-8eb5e0f9b057.png)

Same for https://hosted.weblate.org/checks/  and https://hosted.weblate.org/checks/?language=nb_NO
There aren't complete links in `view-source:https://hosted.weblate.org/checks/`

Edit: Doesn't work in FF 68.8.0esr or Chromium 81

**Comment by julen** [comment]
This needs to check the event information to determine if a new tab needs to be opened. The code currently does a blind `window.location = $(this).data('href');`, so it additionally needs to check the event information to detect ctrl/cmd+click or middle-click. The downside of this is it will never have the browser's native right-click option to open a link in a new tab (because there's no actual link from the browser's PoV).

Another option would be to have anchors for every single table cell content, making sure the styling is adjusted accordingly. No JS needed and natively supported by browsers. Seeing how currently things are implemented, the first option is faster and easier to do, though.

**Comment by nijel** [comment]
Adding link inside the table is IMHO way to go, this is what we use on translate page as well and that would give native link behaviour there.

**Comment by julen** [comment]
IMHO that doesn't quite fix the issue because the UX is left in an inconsistent state:
* Using Ctrl/Cmd+click will now open the link both in the current tab **and** in a new tab
* The native link behavior only applies to the check name text; the padded cell contents look clickable but they don't behave the same way
* The rest of the cells still exhibit the previous behavior

**Comment by nijel** [comment]
It doesn't change current tab for me. Yes, it works only on the link, but it is consistent with what we already have elsewhere. Better solution is always welcome :-)
