### ISSUE TITLE
Wrong language to translate in the engage page

### ISSUE THREAD

**Issue by softwarerero** [WeblateOrg/weblate#4098]
The sentence "The translation project for `PROJECT_NAME` into English (`LANGUAGE`) currently contains..." for some languages refers to English instead of the language picked from the URL.

**To Reproduce**

https://weblate.duobiblo.com/engage/duobiblo/en/: LANGUAGE=English, OK
https://weblate.duobiblo.com/engage/duobiblo/de/: LANGUAGE=Englische, ERROR, Expected: 'Deutsche'
https://weblate.duobiblo.com/engage/duobiblo/es/: LANGUAGE=español, OK
https://weblate.duobiblo.com/engage/duobiblo/pt/: LANGUAGE=inglês, ERROR, Expected 'português'

**Screenshots**
![Screenshot from 2020-06-27 13-32-18](https://user-images.githubusercontent.com/2768891/85928504-600a5700-b87b-11ea-801a-fcbb1de63fa6.png)

**Server configuration and status**
 * Weblate: 4.1.1

**Comment by nijel** [comment]
This one is tricky - there is English in the translated string with comment for translators to use their language name instead:

https://github.com/WeblateOrg/weblate/blob/5b5c57694935d80801bcee9dc56c52e0a160dcca/weblate/templates/engage.html#L41-L42

What seems to go unnoticed in several cases, even though the comment is shown quite prominently: https://hosted.weblate.org/translate/weblate/application/cs/?checksum=ab4c416aa1f8f528

It could use placeholder for the language name, but it would then look weird in languages which need declination here. That's why this approach for localization has been chosen...

Overall it seems that in most cases the translation is correct and I'm fixing now the few ones where I know how to fix it...

**Comment by nijel** [comment]
I have fixed all the strings and I don't see approach to handle this better.

**Comment by softwarerero** [comment]
Thanks for doing what you can, I see how this is tricky. I love Weblate!

**Comment by nijel** [comment]
In the end I've decided to remove the language name from the string in a13b58ed4aa79dacbd5c74bbed7f67c179ba48ee.
