### ISSUE TITLE
catalan "l·l" letter triggers wrong failing check

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#4197]
**Describe the bug**

The Catalan string "Cancel·la la baixada" triggers a failing check "Consecutive duplicated words: Text contains the same word twice in a row: la".  In Catalan, `l·l` is a letter:
https://en.wikipedia.org/wiki/Ll#L_with_Middle_Dot

**To Reproduce**

https://hosted.weblate.org/translate/f-droid/f-droid/ca/?checksum=decd2845f97c7600

**Expected behavior**

Not trigger a "duplicate words check".  I don't know if the dot here is the correct dot.  If the dot is incorrect, then perhaps that should its own check. 

**Server configuration and status**

hosted.weblate.org

**Comment by nijel** [comment]
According to Wikipedia, it's a single char `ŀ`, so using two chars instead `l·` seems wrong.

**Comment by eighthave** [comment]
yeah, makes sense to me.  So it seems the failing check should be about
that letter.  I asked the translator to comment here on this issue.

**Comment by nijel** [comment]
Still Weblate should allow it in case it is widely used. There are already lot of similar cases in other checks.

**Comment by jmontane** [comment]
Hi,

"ŀ" and "Ŀ" are legacy characters for Catalan language, right, but they never were widespread used, because latin1 codepage lacks thems, and Spanish keyboard doesn't provide a way to type such characters. So, "l·l" (using middle dot) is widespread encoding used ever for Catalan geminated el.
 
Catalan preferred encoding for "l·l" is using middle dot U+00B7. Just read [Unicode info](https://www.unicode.org/charts/nameslist/n_0100.html):
> 0140 | ŀ | Latin Small Letter L With Middle Dot
> -- | -- | --
>   |   | ≈ | 006C l 00B7 ·
>   |   | • | Catalan legacy compatibility character for ISO/IEC 6937
>   |   | • | preferred representation for Catalan: 006C l 00B7 ·


Said that, I guess the problem is with Weblate text tokenizer. Text segmentation can be really difficult, and defining what is a word is not as simple like "[:alphanum:]+". Unicode provide 2 annexes, related with this issue: [UAX 29](https://unicode.org/reports/tr29/) (Text Segmentation) and [UAX 31](https://unicode.org/reports/tr31/) (Identifier and Pattern Syntax)

First one, UAX 29, is really good for text (read uses with grammar and spell checkers), as you can read in UAX 29. MIDDLE DOT 00B7 is a MidLetter character in this document. So, Catalan case is well supported with UAX 29. No tailoring is needed.

Second one, UAX 31, is simple, and good for identifiers (read hashtags and reserved words for program languages). As you can read in UAX 31, MIDDLE DOT 00B7 is in [table 3a](https://unicode.org/reports/tr31/#Table_Optional_Medial) for tailoring languages. Catalan case is quoted [here](https://unicode.org/reports/tr31/#Specific_Character_Adjustments). So Catalan can be fully supported with UAX 31. For instance, Twitter [supports hashtags with L·L](https://twitter.com/search?q=%23L%C2%B7L&src=typed_query&f=live)
