### ISSUE TITLE
Flat XML fields

### ISSUE THREAD

**Issue by Tocchopeggh** [WeblateOrg/weblate#4202]
Hello,

I'm using Weblate 4.1.1. and I'm having problems while loading XML files, setting the "Flat XML file" file format.

Exactly, my files follow this structure:

```
<labels>
     <label name="details">Details</label>
     <label name="protocol">Protocol</label>
     <label name="date_time">Date/Time</label>
</labels>
```

But Weblate requires mandatorily the following fields:

```
<root>
     <str key="details">Details</str>
     <str key="protocol">Protocol</str>
     <str key="date_time">Date/Time</str>
</root>
```

Is there a way to get him to accept custom fields/keys?

Thank you and have a good day,
Davide

**Comment by nijel** [comment]
There is currently no support to customize this easily (besides implementing own file format class within Weblate).

See #4158 and #1897

**Comment by BhaaLseN** [comment]
Hey @Tocchopeggh in case you use self-hosted Weblate, you can do the following (until a solution for #1897 is implemented):

1. Place this snippet somewhere in your Weblate installation folder, for example at `/var/www/weblate/weblate/custom/customxml.py` (and verify the values in `CustomXMLFile` are correct; I hope I didn't typo your `root_name`, `value_name` and `key_name`):
```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from weblate.formats.base import cached_property
from weblate.formats.ttkit import TTKitUnit, TTKitFormat
from translate.storage.flatxml import FlatXMLFile

from weblate.trans.util import get_string


class CustomXMLUnit(TTKitUnit):
    @cached_property
    def locations(self):
        return ''

    @cached_property
    def context(self):
        if self.template is not None:
            return self.template.getid()
        return self.unit.getid()

    @cached_property
    def source(self):
        if self.template is not None:
            return get_string(self.template.target)
        return self.mainunit.getid()

class CustomXMLFile(FlatXMLFile):
    def __init__(self, inputfile=None, **kwargs):
        super(CustomXMLFile, self).__init__(
                inputfile=inputfile,
                root_name="labels",
                value_name="label",
                key_name="name",
                indent_chars="    ",
                **kwargs)

class CustomXMLFormat(TTKitFormat):
    name = 'Custom XML translation file'
    format_id = 'customxml'
    loader = CustomXMLFile
    monolingual = True
    autoload = ('.xml',)
    unit_class = CustomXMLUnit
    new_translation = '<labels/>'
```
2. Place an empty file named `__init__.py` next to it (so, at `/var/www/weblate/weblate/custom/__init__.py`); otherwise Python won't load it (at least I think thats still the case)
3. Update your `/var/www/weblate/weblate/settings.py` to include it with `WEBLATE_FORMATS` (replace `custom` with your folder name, `customxml` with the file name and `CustomXMLFormat` with the class name if you changed them):
```python
WEBLATE_FORMATS = (
    'weblate.custom.customxml.CustomXMLFormat',
    # other formats here
)
```

If you're using a hosted one, you're out of luck unfortunately.

**Comment by Tocchopeggh** [comment]
Thank you @nijel and @BhaaLseN, in the next days I'll try something and I'll update you!

**Comment by Tocchopeggh** [comment]
Unfortunately, I couldn't solve my problem, because after having applied the great solution offered by @BhaaLseN (thank you again!) I've encountered several issues regarding the navigation among projects, components and, in general, pages in my Weblate site. I think that's because I've installed Weblate via Bitnami, and I suppose it cannot be modified in any way.

I think I'll write a Groovy script or something to convert XML from custom to the default format :(
