### ISSUE TITLE
Gitlab merge requests without forking repo

### ISSUE THREAD

**Issue by franta** [WeblateOrg/weblate#4285]
**Is your feature request related to a problem? Please describe.**
Gitlab pipelines from merge requests.
Weblate create merge request, gitlab trigger pipeline, but pipeline fail because different repo without required settings (gitlab ci variables).

**Describe the solution you'd like**
I completely understand why Weblate fork repo. Translator don't need commit permissions to original repo, but still can propose changes. Well known workflow eg. on public github.
But this solution is problematic for us, mainly because of problem described above.

Proposal is to add possibility (settings in project, component, special vcs type gitlab-nofork ... not sure - for us it's not problem to configure it globally) to create branch in original repo.

Our workflow is "everyone" (internal developers) can commit to repository and maintainers merge proposed changes to protected branches.

**Comment by nijel** [comment]
The option is already there, just set the push branch. See https://docs.weblate.org/en/latest/admin/continuous.html#push-changes

**Comment by georgescumihai** [comment]
Following the instructions for Github at https://docs.weblate.org/en/latest/admin/continuous.html#push-changes
I am unable to configure Weblate to push to a different branch.
I get the following error: `fatal: no path specified; see 'git help pull' for valid url syntax  (128)`

Weblate 4.1.1, Docker Image
My component configurations:
Version control system: Github
Source code repository: ssh to the repo
Repository branch: develop
Repository push URL: empty
Push branch: weblate-translations
Repository browser: empty string

Weblate is throwing this error when the manual push button is tapped or I add a different translations language which triggers a local commit. : `fatal: no path specified; see 'git help pull' for valid url syntax  (128)`

Also the local branch is develop instead of `weblate-translations`

If I set the git `Repository push URL`, then it will create a fork and will create a PR from the fork when push it tapped.

**Comment by nijel** [comment]
Can you please enable verbose logging of VCS operations to see which of the operations did fail?

Changing LOGGING in settings.py:

```python
    "weblate.vcs": {"handlers": [DEFAULT_LOG], "level": "DEBUG"},
```

**Comment by adhamelsabbagh** [comment]
i have the same problem

**Comment by georgescumihai** [comment]
I will try later this week again with the log level for vcs.

**Comment by nijel** [comment]
Another option is to configure [Sentry](https://docs.weblate.org/en/latest/admin/install.html#sentry) integration. It would collect such errors with more details.
