### ISSUE TITLE
Configuration to Hide Weblate Version Number

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4428]
**Is your feature request related to a problem? Please describe.**
I would like a setting that allows the weblate version number to be hidden from the user so that they cannot take advantage of a known exploit for said version.

The version number is currently viewable within the footer of each page and the documentation link (bottom left corner of image):
![weblate_home](https://user-images.githubusercontent.com/16519378/92017384-97015b00-ed4b-11ea-952b-35f45a1bf1ae.png)

**Describe the solution you'd like**
The ability to have `HIDE_VERSION_NUMBER = True` in the `settings.py` and the ability to use it in weblate docker as an environment variable (`WEBLATE_HIDE_VERSION_NUMBER`).

**Comment by nijel** [comment]
While we can easily hide the version number from the footer, removing it from the documentation link is not really an option as that has to point to matching documentation. It's used in many forms to provide documentation on the form fields and it has to link to matching version to provide accurate documentation.

**Comment by dgarana** [comment]
> While we can easily hide the version number from the footer, removing it from the documentation link is not really an option as that has to point to matching documentation. It's used in many forms to provide documentation on the form fields and it has to link to matching version to provide accurate documentation.

I'd suggest showing only the documentation link once the user has log in.

**Comment by nijel** [comment]
The other option would be to point to `latest` docs until user is authenticated.

**Comment by dgarana** [comment]
> The other option would be to point to `latest` docs until user is authenticated.

That's a very nice alternative.

**Comment by comradekingu** [comment]
So an attacker can't figure out what version it is running because an attacker could not possibly register an account to find out? Regardless of hidden status or not, it is trivial to find out what version it is anyway.

From the point of view of having the attack ready, why  not just test it/all of them?

Removing the status complicates reporting bugs for actual users.
I feel safer as a user knowing the version was at-least fairly recent. Seeing it removed seems dubious.
