### ISSUE TITLE
Machinery tab naming

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#4480]
**Describe the issue**

The term "Machinery" used for machine translation and translation memory suggestions seems confusing and hard to translate into some languages, see https://hosted.weblate.org/translate/weblate/application/en/?checksum=4ba81e83ac5d6fe0#comments

**Additional context**

Looking at existing translations, it seems to be translated as:

* *Machine translation*
* *Automated translation*
* *Automation*
* *Machinery*
* *Translation suggestions*
* *Automatic suggestions*

Brought up by @ilocit and @ldmpub, maybe @comradekingu or @orangesunny will have comments on this as well.

**Comment by orangesunny** [comment]
As this tab contains suggestions from the machines, I tend to use the term with _suggestions_ in it to be the clearest possible.
_Automatic suggestions_ is covering what is inside the best, but _Machine translation_ is probably what users are usually looking for.

I am for _Automatic suggestions_ or _Automated translation_.
What do you all think?

**Comment by ldmpub** [comment]
+1 for "**Automatic suggestions**" because it's done by a machine (automatic) and it's rather a suggestion than a translation (according to me translation stands for in full words: "string translated in a language and approved so it will appear in the final app for users").

**Comment by ilocit** [comment]
Since we also brought it up, I wanted to expand on my previous comments. I see it from both a technical and a "human" side ;-) Technically, those texts which are displayed on tab "Machinery" are two different things:
1) If configured on your weblate instance, they can be from an MT source like Google, Microsoft, DeepL, SAP and the likes. In this case, I think the term would be MT proposals (or suggestions if you like, but SAP and others refer to them as proposals).
2) if you use a TM Engine on your installation, those proposals could also come from a TM where translations of similar (fuzzy) or same (exact or 100% matches) are stored and retrieved from. In this case, if you are lucky, they were either manually translated by a human or at least post-edited and then stored in the TM.
So in case 2, which I consider an importand one and a most valuable one, it is not a machine making the those proposals, but a human. A machine simply searches for them and shows them to the user.
Long story short, I would not make this a technical and only technical term. When translators use weblate to translate, they will be familiar with terms like TM and MT and matches (like proposals or suggestions). That is what they will be looking for in the UI. Machinery is not something that would suggest to them that this is the place to look for those TM or MT matches.
Other humans (like developers, techies....) will not use this tab / feature much anyhow, I guess. They would rather use the task "Automatic Translation" to pre-translate whole componentes.
So in summary, in the context of this string we are not talking about a technical concept but a UI term which should be descriptive and tell the user what to expect.
Thus my suggestion to call it either 
a) Translation Proposals
or
b) Translation Suggestions (if you are happier with suggestions).

If length restrictions were not an issue, one could also add TM/MT for more clarity.
So "Translation Proposals from TM/MT"

My two cents. :-)

**Comment by comradekingu** [comment]
"Auto-translation" "Robot translation" "Neural-machine translation" "Assisted suggestion"?
