### ISSUE TITLE
Track changes of the component license

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/weblate#4508]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I don’t know who made the license change on the component. In `History`, it is authored by `None`

**Describe the solution you'd like**
Label license changes by username the same way as commits and translations.

**Additional context**
It may be useful to reconsider what to track and label from all the changes in history. Mostly because of the growing number of libre projects. Is there a list of what can be tracked and is not?

**Comment by comradekingu** [comment]
Maybe it can be found with "state change" in the regular search, but it isn't possible to search for it per user
https://hosted.weblate.org/changes/?user=nijel&project=boilr&lang=&action=55&user=nijel returns nothing, and
I know that should show it changing to AGPLv3+ 1st of sept.

I didn't understand

> It may be useful to reconsider what to track and label from all the changes in history. Mostly because of the growing number of libre projects. Is there a list of what can be tracked and is not?

Ultimately tracking license per string and allowing translators to accept changes would be costly, but fix problems. It is a bit of a headache removing strings from actual codebases because of it, but that grants a "white room" implementation for other translators.
