### ISSUE TITLE
Drop Twitter and LinkedIn from profile settings

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#4569]
https://hosted.weblate.org/accounts/profile/#profile
has Twitter and LinkedIn, which are both closed source services on non-federated networks.

Would be better to have gitlab.com and Codeberg, or all individual fields.

**Comment by nijel** [comment]
These fields were added as option for being contacted, there is still generic URL field you can use for whatever you prefer. You don't have to fill in the services you don't like.

PS: The good thing on non-federated services is that they provide you a short identifier which is easy to display on the public profile.

**Comment by comradekingu** [comment]
@nijel How about calling them "microblog" and "business network"?
Or, just listing the services that are supported for the available spots.
That way it is possible to have some level of ordering too, by putting the stuff you want
to be contacted by first.
---
_________
_________
_________

You can add: Twitter, LinkedIn, Omegele, etc.

**Comment by nijel** [comment]
We might add some way to include generic links, but I don't think removing Twitter and LinkedIn is a way to go. Like it or not, these are the most popular services in the area.

PS: Why you didn't include GitHub in the list as that is closed source service as well? ;-)

**Comment by comradekingu** [comment]
The functionality is not a problem, but having a specific field reserved is a bridge too far.

I didn't include GitHub, because it isn't my choice ;) Also, Weblate is on GitHub, so it would be a somewhat strange effort to remove it as a listing.

When you say it, having the name as a specific field doesn't make sense.
For the people that don't have GitHub, or want to use it for other things, the space is better used for something that has more utility, which means adaptable fields.

**Comment by nijel** [comment]
The reason for having these listed explicitly is that it allows entering just username. That is both convenient for user to enter and nice to display in the profile.

I don't think this is place to educate people, nobody will create a profile on Codeberg just because it is listed as one of services which can be included in user profile on Weblate.

But you're right that there should be more options to link to outside, so how about adding:

* Liberapay username, I think it makes perfect sense for libre localization and in this case it might even work as an education
* Fediverse link, to add link to any social network or microblogging site
* Code link, to add link to GitLab instances, Codeberg or similar services

**Comment by comradekingu** [comment]
Sounds good. While true that it neither is a place to sell Codeberg or give it special treatment, Weblate is the Codeberg of the world, so it makes more sense to put eggs in that basket as a collaboration. "Code link" is however a much better idea.
