### ISSUE TITLE
Repository Tools for a component only accessible by admin users

### ISSUE THREAD

**Issue by mikefonted** [WeblateOrg/weblate#4612]
**Describe the bug**

A project with Custom access.
A component in that project.
A role with the whole permissions available.
A group with that role, that project, that component and all languages.
A user with that group.

The user can access to Repository maintenance of the component, but the Repository Tools is empty.

**Expected behavior**

A way to use Repository Tools with a role and a no-admin user.

**Server configuration and status**

Docker image tag weblate/weblate:4.2.2-2

**Comment by nijel** [comment]
Indeed, the access is checked at project level there.

**Comment by KarinBerg** [comment]
I have a similar problem but with a project with private access. Does your bug fix also fix that problem?

**Describe the bug**
A project with private access.
A component in that project.
A role with the whole permissions available.
A group with that role, that project, that component and all languages.
A user with that group.

The user can access to Repository maintenance of the component, but the Repository Tools is empty.

**Expected behavior**
A way to use Repository Tools with a role and a no-admin user.

**Server configuration and status**
Docker image tag weblate/weblate:4.1.1-3

**Comment by nijel** [comment]
Yes, it should fix it.
