### ISSUE TITLE
the content of english translation field show wrong value

### ISSUE THREAD

**Issue by PawelSpoon** [WeblateOrg/weblate#4721]
**Describe the bug**
i have an intermediate file setup
.pot
contains key and intermediate language
en po
contains key and english translation
de po
contains key and german translation

i would expect to see on the german translation page the english po value in english field. and so it was in previous version.
now we did update to 4.2.2 two weeks ago and today the translator found this values switched or wrong as you wish

**To Reproduce**

see the last image for the component configuration

1. Go to english translation of component and check one string
2. Intermediate language is title style, English is sentence style (image1)
3. Scroll down , visit other languages tab, select german
4. English field shows title style (so imho the intermediate language), if you check the other image you will see that in other languages (english) the capitalization is correct. (image2)
so i think that field english obviously show the wrong value, the one of intermediate language rather then the english one..

**Expected behavior**
English field should show the propper english translation

**Screenshots**
![image](https://user-images.githubusercontent.com/11692361/96610679-2f539f00-12fc-11eb-89e3-11f319b63eda.png)

![image](https://user-images.githubusercontent.com/11692361/96611303-cd476980-12fc-11eb-9618-7be51631d7c7.png)

![image](https://user-images.githubusercontent.com/11692361/96610769-4a261380-12fc-11eb-805d-2b496dd25fcf.png)

**Server configuration and status**

**Weblate deploy checks**

**Exception traceback**

**Additional context**

**Comment by nijel** [comment]
Can you please post content of the PO/POT files? I've just added test for this to our testsuite and was not able to trigger such behavior.

**Comment by PawelSpoon** [comment]
but we agree that behaviour is incorrect right ?

upload does not support pot files :)
here is a zip of one of our files
[WeblateIssue.zip](https://github.com/WeblateOrg/weblate/files/5413905/WeblateIssue.zip)

**Comment by nijel** [comment]
> but we agree that behaviour is incorrect right ?

The source string should definitely match what is shown as translation in English.

Looking at the files:

* the .pot has "Testbed Operator"
* the English .po has "Testbed operator", maybe this should be the intermediate file?

So the source string is shown correctly, but the translations do not seem to reflect that.

**Comment by PawelSpoon** [comment]
i have sent you a direct mail yesterday as i do not want to discuss that in the open: support.weblate.org #2106

**Comment by nijel** [comment]
Maybe you should install msgmerge addon (https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge) instead of intermediate files, that seems better fit. It will update the .po files to match .pot.

Anyway when I imported these files locally, it behaves as expected - the source and intermediate files look as in your screenshot:

![image](https://user-images.githubusercontent.com/11692361/96610679-2f539f00-12fc-11eb-89e3-11f319b63eda.png)

However the source for German translation is with lowercase o, unlike like on your screenshots. All edits I've tried don't mess up the state and it's kept consistent. Maybe there was some issue in older version which got fixed meanwhile, that's hard to tell.

**Comment by PawelSpoon** [comment]
i do close the issue. i will remove the intermediate files and use msg-merge add-on instead.
