### ISSUE TITLE
Adding new translation key is too slow

### ISSUE THREAD

**Issue by thongnv** [WeblateOrg/weblate#4797]
It takes up to 35 seconds to add a new translation key. Removing a key is also slow. Other tasks have acceptable performance.

**Comment by nijel** [comment]
What Weblate version do you use? Can you check logs what takes most of the time?

**Comment by thongnv** [comment]
@nijel Weblate 4.3.1

The log shows that processing a translation file took too much time.

```
celery-notify stderr | [2020-11-02 09:56:12,907: INFO/MainProcess] Received task: weblate.accounts.tasks.notify_change[47b81bd4-ab86-4cfd-8fb0-599fd00754f6]

uwsgi stderr | INFO homologation/homologation-ui/vi: processing src/resources/translations/vi.json, content changed

celery-notify stderr | [2020-11-02 09:56:41,752: INFO/MainProcess] Received task: weblate.accounts.tasks.notify_change[550fc456-232d-484c-aa8c-65a1c7945878]

uwsgi stderr | INFO homologation/homologation-ui: checking triggered alerts
uwsgi stderr | INFO homologation/homologation-ui: running source checks for 1 strings
uwsgi stderr | INFO homologation/homologation-ui: updating stats caches`
```

As I noticed this happens only for the translation file with few translation keys (if I added all the keys then the speed is much improved)

**Comment by nijel** [comment]
> The log shows that processing a translation file took too much time

Unfortunately, the Docker logs do not show timestamps, so it's hard to tell from the log part you posted (I've improved logging for the next release in 7a5eee3073e079423e12782d8c6a7af274a51984).

> As I noticed this happens only for the translation file with few translation keys (if I added all the keys then the speed is much improved)

So, the performance gets better as the file is bigger?

**Comment by thongnv** [comment]
> Unfortunately, the Docker logs do not show timestamps

I thought the timestamps were showing, i.e from [2020-11-02 09:56:12,907: INFO/MainProcess] to [2020-11-02 09:56:41,752: INFO/MainProcess] which means the processing of the translation file took 29 seconds.
Anyhow, as I experimented, the processing time changes when I changes content of the translation file. 

> So, the performance gets better as the file is bigger?

I would say, it gets better when the translation files have identical keys.

**Comment by nijel** [comment]
No, the times are shown for the celery tasks, it doesn't tell anything about how long the update tell. As the output might be buffered and is coming from different processes, it's hard to guess anything from that.

Can you give some example how you add/remove keys and what is your component configuration (most notably used file format)?

**Comment by thongnv** [comment]
> Can you give some example how you add/remove keys and what is your component configuration (most notably used file format)?

The key is added via Tools > Add new translation string
The component configuration is 
- JSON nested structure
- Filemask: src/resources/translations/*.json
- Base language file: src/resources/translations/en.json
- Intermediate language file: src/resources/translations/en.json

**Comment by nijel** [comment]
The base and intermediate files should not be same. Keep the intermediate file blank instead. But I don't think it's causing the troubles here...

**Comment by nebulade** [comment]
I know this is closed, but we also experience about 30sec response time while adding new translation keys. Translating an existing key into other languages is very fast in comparison. I also found that adding more memory to the instance does not improve speed. Also since it is so slow I tried to have more tabs open to add keys but submitting more in parallel seemingly takes the same time as in sequence, I guess some queuing happens there anyways.

I can follow up with hopefully more server/container side logs, for a start just a screenshot showing the timings in one example key adding:

![image](https://user-images.githubusercontent.com/646768/105159409-572aec80-5b0f-11eb-82f1-432fcb59e240.png)

In our case we also use the nested JSON type even.

This is on Weblate 4.4.2 deployed on a Cloudron. I am happy to provide a clone of our instance for further debugging if there is interest to fix this.

**Comment by nijel** [comment]
Adding strings updates the file and that's protected by lock, so multiple requests will happen consequently and not in parallel.

But in current implementation it is expected to be somewhat slow - it adds a new string to the file and then parses files to load new strings. This is to gracefully handle any file format specifics when adding the string (for example it can change key or add flags). Most of the time is spent on parsing the files and updating the Weblate database with new string. There is certainly place for improvement in performance of this, but it's not really related to adding of new strings.

**Comment by nebulade** [comment]
Thanks for the clarification. One more question, which files is it trying to parse here? Aren't all translations in the database and the resulting, in this case json, files only generated as output?

**Comment by nijel** [comment]
It does the same thing as when the files would be updated in the upstream repo. The only difference is that the extra commit was created locally by adding the string to the base file. There used to be several optimizations in this code path, but it has proven to be fragile to keep it in sync with full update code and now the full update is used here as well.

**Comment by ChiragMoradiya** [comment]
We also encounter the same issue when deleting any key. API mostly takes more than 1 minute.

As @nijel has pointed out, this must not be relevant to the single action - it might be appearing for every actions like add new key, update a key etc. But, it's more visible on Delete Key.

I am attaching logs here. After deleting a key, I saw logs for N minutes. That seems too slow to work with.

I am experiencing this issue on a Weblate Project having 115 Components and 38 Languages. So, there are total 4370 `.json` files in the Git Repository.

And, I believe the issue is that, when I delete a key from a component, there are 38 files modified in the git repository. And, 4370 files are being scanned by 38 times. So, total files to be scanned is 166,060.

See [weblate-2.log.gz](https://github.com/WeblateOrg/weblate/files/13897890/weblate-2.log.gz) for reference.

**Comment by nijel** [comment]
I've just created https://github.com/WeblateOrg/weblate/issues/10787 to track the removal separately.
