### ISSUE TITLE
Cannot register an account in Weblate

### ISSUE THREAD

**Issue by eqMFqfFd** [WeblateOrg/weblate#5148]
## Description
I am trying to sgin up in your website to register an account on Weblate.

The problem is that when I enter an email and password, the verification email never arrives.

I've been 30 minutes submitting the form over and over again, Weblate doesn't send the confirmation email.

1. I am using the right email address.
2. icloud.com is my provider.
3. There is no new mail in the junk folder.

**Comment by nijel** [comment]
The emails are sent by the Celery worker, so most likely this is (again) the same issue as #5147

**Comment by kenygamer** [comment]
This problem is on your site, @nijel. I am maybe choosing to host with you if I can register as a non-profit organization. Hosting it gave me a lot of trouble and if I have it again I don't want to wait two months again.

**Comment by nijel** [comment]
Please stop blaming me, it's your problem, not mine. There are hundredths installations of Weblate, and people managed to get it running without any major problems and without reporting a dozen of issues here. There might be some things not covered by the documentation and improvements in that are always welcome. It would be great if you had addressed issues you had by extending our documentation and not by blaming us.

**Comment by kenygamer** [comment]
@nijel I understand, however my issue was regarding your Hosted Weblate website, since you have offered me hosting.

I have still detected a failure, it is that the verification email took 4 hours to send. The mail also reached the junk folder. There must be an issue with your website.

Affix: Do you know how to sign up if the source code is not public? We are non-profit, however we do not want that amount of translations for everyone to see.

**Comment by nijel** [comment]
So the problem with registration is at https://hosted.weblate.org/? There was no indication of that in the initial post and all your other issues were with your server. This one of the questions in the initial issue template which you have removed and this is why it's there, to clarify where the issue happens. Anyway in such case it's better to write to our support from e-mail address which had such issues so that we can investigate.

> Affix: Do you know how to sign up if the source code is not public? We are non-profit, however we do not want that amount of translations for everyone to see.

Gratis hosting is only available to libre projects, see https://hosted.weblate.org/hosting/ for detailed conditions. We do have  discounts for non-profit as well.
