### ISSUE TITLE
Improve Weblate support 

### ISSUE THREAD

**Issue by kenygamer** [WeblateOrg/weblate#5150]
A situation that I would like to be assessed is non-profit organizations.

I am the owner of a non profit organization and I hardly receive support. My issues take forever a reply.

I can completely understand that they were holidays recently as well as I can understand that this is a paid service. However, I am a user of your service who plans to give it a charitable use and it has been two months since I installed Weblate, still unable to use it.

I have filed multiple issues but much of the delay has been due to unefficient public support. I would like to know how you can sign up to the non profit organization for faster assistance.

We have paralyzed all the work of a company by having to wait for Weblate to supply us with the translations that we require.

Please assess the situation.

**Comment by orangesunny** [comment]
Hi @kenygamer,

I am sorry that you feel this way; thank you for the feedback. I will try to explain to you how our libre community and paid support work. If you like that, you are welcome to join the community. If you don’t, you can suggest a **solution** that might or might not be accepted. You can also download the sources and do everything in your own desired way.

We are trying to understand.
If you are communicating kindly and want to understand, you are on the way to something good. If you just want to yell out what you think, there are places on the internet just waiting for that, other than our GitHub repositories.

*Issues* is not the best place for support as you were able to read under nearly every issue you submitted. Thanks to patient @nijel and automatic comments.

**Support** works the same for commercial, libre projects, and non-profit organizations.

Free support:
- You can use our [discussions](https://github.com/WeblateOrg/weblate/discussions) to ask the community. 
- You can ask our support via e-mail. 
- You can even ask here in the issues. With limits you recognized.

You will get your answer once someone has time to make it. We can’t offer any guarantee, and you are not the one who measures the time in this case.

[Paid support](https://weblate.org/support/) is different. You will always get your answer. If you buy the Premium package, you will get your answer the NBD at the latest. Once you pay and send the e-mail, hand yourself your stopwatch and tell us the time. 

Free support is in our free time; we hold the stopwatch.

Note: If you are using something you have received for free and it does not work for you as you wish, please don’t blame the giver. Not only with Weblate, anytime.

What is common for both support options-paid and free-is that we want to understand and help with your problems. 

You tell us your problem, we ask for the details needed for a solution by a template or reply. If we have enough information, we help. If not, we ask you again. If you don’t provide the information needed, we cannot help you. Again, if this happens, we are the ones who don’t have the information. You can’t give us more information saying that you already told us. If you feel this way, please try to explain it differently as we could miss something. I promise we will try again.

If we don’t understand your problem, we can’t help you. If we don’t understand you, you are paralyzing the help. I am not trying to do blame shaming; I am trying to explain so we can move on.

**Comment by comradekingu** [comment]
@kenygamer (All the questions you have or could have had are answered on https://weblate.org/hosting/ Where else would you look for it?)

I saw this feature request and decided to read the reports in https://github.com/WeblateOrg/weblate/issues?q=is%3Aissue+author%3Akenygamer+
None of those are good error reports. You could have read the documentation to answer most of those.

Who you are or represent is beside the point, what matters whether you pay for paid support.
You don't seem to, yet have received gratis support. You got it from the lead developer that didn't just answer, but even went ahead to troubleshoot some of your issues and pinpointed the main one, and helped solve others, and now _another_ staff-member above here. How you concocted the idea of "hardly receive support. My issues take forever a reply." and "unefficient public support". That isn't the case. Only 3 (of 12 so far) have received support the next day. All the others are answered the same day, and for the ones fresh enough to still show it, within hours every time…

The support swift and to the point, for descriptions of problems that are vague enough to be anywhere, including outside of Weblate software and documentation at all. You are also asking about and making basic things, and even get help for those. How you went down this road is presumably through not reading https://weblate.org/hosting/ There is no priority bug-fixing or e-mail support for self-hosted instances without a support contract?

How you want to do things and how much your time spent being quick or slow getting there is entirely your decision.

You don't sign up to the non-profit organization. You sign up _as_ a non-profit organization and was offered a better price because of it.
Weblate does not supply translations, it is a platform for translators to do so. You can hire translators just like you can hire coders to work on your GitHub projects. As I understand it you have a registered non-profit company for a closed source software project? Makes no sense to me, but alas.

**Comment by kenygamer** [comment]
I'm very sorry, but my opinion stands. Thanks for answering.

My complaint is that some issues taken very long to fix. I have not had my issues late in answering the first time I open them, what you say is true. My issues are answered in a maximum of one day. However, I had a couple of issues where my replies were answered in up to two weeks.

In addition I appreciate the help, but I think that Weblate should provide greater support. Not all of us have the money to pay for a service like Weblate, as we are a company, but up there - we are non-profit, unlike you. It supposes a great cost to us.

And precisely there I want to stop because Weblate as @nijel said, Weblate has support for non profit torganizations that's free. However, I have spent two months trying to setup Weblate, because, indeed, many of the docs weren't clear enough or updated - that's true such that my issues triggered a few commits.

Since we are a non-profit company it does not mean that we are open source. I'm asking you why I can't sign up if I just have a repo with language files closed source. All that will be available in Weblate, so I don't understand the intention behind that the repository has to be public.

**Comment by orangesunny** [comment]
Hi again,
Thank you for the reply.

> My complaint is that some issues taken very long to fix. I have not had my issues late in answering the first time I open them, what you say is true. My issues are answered in a maximum of one day. However, I had a couple of issues where my replies were answered in up to two weeks.

1. Please kindly reread my previous reply, especially the *free* and *no guarantee* part. If you have any questions about it, please ask, and I will try to explain that particular misunderstanding again.
2. We are also getting to another thing. We like to help, but we can’t solve everything ASAP (or at the desired time). Some issues can take months or even years to be solved, not only in Weblate repositories. Every project has it’s roadmap. Paid custom development/consultations raise the priority and delivery date.

> In addition I appreciate the help, but I think that Weblate should provide greater support. Not all of us have the money to pay for a service like Weblate, as we are a company, but up there - we are non-profit, unlike you. It supposes a great cost to us.

1. As I mentioned in my previous reply, please provide a solution of greater support we could consider.
2. We have a free offer as it stays at https://weblate.org/hosting/#libre. Free support included. Libre software is open for everyone; that’s why projects and repositories are public. For non-profit associations looking for private translation projects, we offer discounts on hosting plans. That is what we can offer, nothing more. We won’t offer anything we cannot provide.
3. Kindly provide your non-profit company name and website.

> And precisely there I want to stop because Weblate as @nijel said, Weblate has support for non-profit organizations that's free. However, I have spent two months trying to setup Weblate, because, indeed, many of the docs weren't clear enough or updated - that's true such that my issues triggered a few commits.

1. Free for everyone and without a time guarantee. As I said before. The special offer for non-profit collectives is only on hosting plans.
2. Thank you for inspiring the documentation improvements; that’s how the libre software communities work!

> Since we are a non-profit company it does not mean that we are open source. I'm asking you why I can't sign up if I just have a repo with language files closed source. All that will be available in Weblate, so I don't understand the intention behind that the repository has to be public.

We support open-source software and their communities, and we do not offer free hosting for closed source repositories. I am sorry you don’t understand; I will try to explain it again this way: If there is no offer, there is no free thing. Telling someone they have to offer doesn’t create the offer.
The intention is that free translations happening on Hosted Weblate stay free and libre, not someone’s private content.

**Comment by comradekingu** [comment]
I am not Weblate. I am a contributor.

Fixing your issues isn't the same as a response. It takes time, because you ask a different question to the same effect of what you didn't fix the central problem pointed to in your earlier reports. Use the container-packaging if you can't configure things, license your code differently, hire someone at what you value your time to be worth. You can't support yourself out of your own problems with basic knowledge and documentation, so why should experts help you for free? You are counterproductive to your own stated goals because you don't fundamentally understand, nor wish to learn. Now you are questioning the basics of support. Nothing changes because Weblate isn't perfect, the documentation isn't perfect, or your company being non-profit.

It is just everyone bending over backwards, and I implore you to understand this, when you are being the worst kind of user there is.

How do you think Weblate can afford _any_ of the concerns you have, much less the esoterically described ones? It is a company that sells a service, and it takes donations. It has staff and expenses. A for-profit motive vis-a-vis non-profit doesn't change that dynamic. How does your non-profit survive, and what does it do?

You can start up a company with the Weblate codebase and offer service any way you want. Make it a non-profit, make it non-profit. Your call. Go ahead. There is no such opportunity for anyone else with your non-profit. Nobody can keep you from being unsuccessful in setting it up, because it relies on you., More importantly, nobody could run anything like what you envision Weblate is and not be at a loss financially. It is unsustainable and unproductive. You do you, but if you can excuse the expression, "be the whole bitch".
If you complain like you do, show the world what sort of services you can offer that others aren't providing.

If your company does great things and is fundamentally a non-profit you can ask for donations and hope to get them. Asking donations for closed source seems a bit rich, but that doesn't stop you from exploring exactly every option.

You can sign up as any type of company, and you pay for the service. It is cheaper for non-profits when that is offered, and it is gratis for libre software. Weblate _itself_ is libre software, and it lives on the reputation of its code, historical achievements, its staff, and its greater benefit to the community _from which it was created_. If there was no libre software coding languages, libraries, operating systems, etc. to work from, making what is today Weblate itself wouldn't be the bigger part of the undertaking.

It would be something along the lines of your position to feel entitled to help without contributing anything back. The reciprocal nature of just sending hard work into the world doesn't really work in the immediate sense of putting food on the table. Weblate would risk its existence doing so. You seem to think Weblate should put more energy into your project of setting up Weblate and your problems doing so than you. That is pure loss for everyone else involved. People who pay for the service, people that donate, people waiting to have their stuff merged so they can fix their own issues, etc, etc. As for the world should be ideal, I agree; it should be. It isn't.

Are you hiring translators for your resource, and are you licensing the translations freely? Do you understand what libre software is?

None of my commits for the documentation had anything to do with your issues. You wasted my time, because I chose to read them.

**Comment by kenygamer** [comment]
@orangesunny @comradekingu What I have tried to say is that I understand that Weblate is a libre software, but that you should have more consideration with @everyone then. If you have a service for sale, and you allege that your service must be paid to be faster, how can you tell me that the support is the same?

Anyway, I only came to request you to pay attention to issues. Exactly so that issues are not abandoned for as long as years. Many people are not playing around. I run a company and I need it, moreover, we are free. Although you don't change their way of proceeding with support, you should at least facilitate the registration of non-profit organizations.

I appreciate the effort, but you must have understood my point.

**Comment by orangesunny** [comment]
We care about every kind user of Weblate. As we want to keep doing that for a long time, we keep Weblate sustainable thanks to our clients who buy the services.

> If you have a service for sale, and you allege that your service must be paid to be faster, how can you tell me that the support is the same?

We do not say that. The codebase is the same; the support has different priorities and response times based on the price. Because we keep the promises we made to our customers.

> Exactly so that issues are not abandoned for as long as years.

There are no abandoned issues in Weblate repositories, there are some with lower priority as nobody can do all work in one week. With every of your pushy reply, you are guaranteeing a lower priority for yourself.

Thank you for repeating your cases for the last time. As you proved again that you are unable to answer a question so we could move forward, we are done here. I wish you all good with your secret non-profit company. 

As many people are asking for support capable of answering the questions, I am going to donate my time to them as it is going the right way of helping them :)

**Comment by kenygamer** [comment]
> We care about every kind user of Weblate. As we want to keep doing that for a long time, we keep Weblate sustainable thanks to our clients who buy the services.
> 
> > If you have a service for sale, and you allege that your service must be paid to be faster, how can you tell me that the support is the same?
> 
> We do not say that. The codebase is the same; the support has different priorities and response times based on the price. Because we keep the promises we made to our customers.
> 
> > Exactly so that issues are not abandoned for as long as years.
> 
> There are no abandoned issues in Weblate repositories, there are some with lower priority as nobody can do all work in one week. With every of your pushy reply, you are guaranteeing a lower priority for yourself.
> 
> Thank you for repeating your cases for the last time. As you proved again that you are unable to answer a question so we could move forward, we are done here. I wish you all good with your secret non-profit company.
> 
> As many people are asking for support capable of answering the questions, I am going to donate my time to them as it is going the right way of helping them :)

I wanted to make my point clear first, which you don't seeem understand. There was no targetedcriticism and I appreciate you answering me, I have in mind the time you put and I have in mind that being a paid service the support takes different priorities. However?

I just wish that you had a faster general support line because that would even motivate me to donate if I had money. f you don't want me to open issues, then the doc should not have all the flaws I found.

1. My company URL is https://crowdmc.us.to
2. My company name is CrowdMC.

We are a non-profit Minecraft server, we have a history of the greatest networks in Minecraft and we are known for being free to play.
