### ISSUE TITLE
RTL punctuation in JSON 

### ISSUE THREAD

**Issue by maggie0002** [WeblateOrg/weblate#5340]
I have an Arabic JSON file which has punctuation such as periods at the end of the sentence (which is the left): https://github.com/LearnersBlock/learners-block/blob/master/frontend/apps/file-manager/src/i18n/ar.json

Yet in Weblate it reads it the file and puts the punctuation on the far right, and reporting it as incorrect and missing a period (because it isn't on the left) (https://hosted.weblate.org/translate/learners-block/file-manager/ar/?q=state%3A%3E%3Dtranslated&offset=2). 

I already tried removing the file, adding it back in, and doing a reset under the 'Maintenance' menu. 

Is this a JSON thing, Github or Weblate?

**Comment by nijel** [comment]
To me, it looks that the strings are wrong in the JSON file - the period is really an initial character there, while it should be the last one.

Why it looks differently is because the RTL rendering is tricky and depends on context.

In Weblate editor the textarea for RTL languages is marked as RTL, and it renders the whole string as RTL.

When looking at the JSON file on GitHub, the string is LTR and the browser automatically switches to RTL upon first char. That's why the period seems to be in the correct position - it is rendered LTR and the rest of the text RTL.

You can see it yourself if you try to select the text char by char - it will behave correctly in Weblate, but the selection behaves weird on GitHub because of mixed text direction:

![image](https://user-images.githubusercontent.com/212189/107022860-2e108a00-67a6-11eb-9ada-52c2577aa40c.png)

That confirms that the period is still rendered LTR and rest of the string RTL.

**Comment by maggie0002** [comment]
Thanks for the info. Very confusing using RTL across the platforms. At the end of the day when processing the Json file in an app should I stick with how Weblate generates it or as it is? Note that when Weblate generates, it appears to have the same issue just the other way around: https://github.com/LearnersBlock/learners-block/commit/a865e42a2f4dae1f908fd07c7b0b021e054691f4#diff-c784c56faa9d7f71ca3db6fe9a64c914471b40593d0ce0d6f1a16e85cc64b56a

**Comment by nijel** [comment]
Just don't look at the JSON file as whole - it is mixed RTL/LTR content and won't display properly. I have no clue how the app handles this in the end, and that's probably what you should check instead.

**Comment by maggie0002** [comment]
> Just don't look at the JSON file as whole - it is mixed RTL/LTR content and won't display properly. I have no clue how the app handles this in the end, and that's probably what you should check instead.

Thanks for the info. I tested in within the app, and unsurprisingly it displays the string as it appears in the JSON (i.e. with the punctuation not he wrong end).

I'm struggling to see how this isn't Weblate related. If you export the files directly from the Weblate interface to either CSV, JSON, or anything else (i.e. taking out the GitHub dimension), the punctuation still appears on the wrong side.

**Comment by nijel** [comment]
In that case, most likely the app doesn't correctly set text direction for RTL languages. I have no clue how big deal is that as my knowledge of RTL languages is purely theoretical.

**Comment by maggie0002** [comment]
> In that case, most likely the app doesn't correctly set text direction for RTL languages. I have no clue how big deal is that as my knowledge of RTL languages is purely theoretical.

So it seems, although I was unsure how it was going to identify what went where. Top tip for anyone coming across the issue, open the JSON file in Firefox, it seems to render RTL JSON properly and now I can see it as expected. 

Thanks for your input.
