### ISSUE TITLE
Better digest and changed string e-mail layout

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5464]
Papercut
Something ala
![bilde](https://user-images.githubusercontent.com/13802408/108148269-c37a1b00-70d0-11eb-85a3-6d16d5a9766b.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/108147800-db9d6a80-70cf-11eb-9a92-ea29e498f0b5.png)

Right now it isn't super clear which string "Show" actually will display, since it isn't inline.
Also, there isn't any separation between source and translation, so that part could be improved.

Having the user-selected alternative languages would be a bonus, since that is what I am used to looking at. More errors could be found then too.

**Comment by comradekingu** [comment]
As long as the fields themselves are clickable, I don't see a need for the "Show" (Vis) button.
Instead you could click any one of the languages presented, whether your alternative languages are included or not.

![bilde](https://user-images.githubusercontent.com/13802408/108389132-a7c95e80-720f-11eb-917d-336d3f4bdcba.png)

**Comment by nijel** [comment]
I've added digest rendering as an option to changes view in a7c2507980b369d891ad76360c8b8f64c3e4e6d1. This makes it easier to improve the rendering while developing, just append `&digest=1` to any `/changes/` view to see the list of changes rendered as diget e-mail.

**Comment by nijel** [comment]
Right now there are more issues with the digest view:

![obrazek](https://github.com/user-attachments/assets/efdab968-ffa2-40c5-a7ab-dd90349b6e3a)


Especially the navigation is rendered as an ordered list, this is probably caused by switching to generic navigation while introducing categories, the CSS needs to be adjusted here.

**Comment by meel-hd** [comment]
I am working on this. I will fix the UI alignment in the digest view. @nijel is that the main issue now?

**Comment by nijel** [comment]
There are really more issues with the e-mail CSS, check yourself at https://hosted.weblate.org/changes/browse/weblate/application/cs/?digest=1 and compare it to https://hosted.weblate.org/changes/browse/weblate/application/cs/.

The e-mail rendering uses a separate CSS: 
https://github.com/WeblateOrg/weblate/blob/a96a13d41add9155ccfa89bf11268c14118ad761/weblate/templates/mail/style.css#L1-L461
which is then inlined:
https://github.com/WeblateOrg/weblate/blob/a96a13d41add9155ccfa89bf11268c14118ad761/weblate/templates/mail/base.html#L12-L16

It can't use the full CSS we use on the website, as that won't work in the e-mail clients. I'm not sure if there is some guidance on that, but I did some manual testing in Gmail, Live, Thunderbird and Evolution to verify it looks reasonable. Since then, the e-mail content got more complex (digest feature is newer than that) and the CSS was not properly updated to cover that.

**Comment by nijel** [comment]
While #12122 makes the rendering slightly better, it doesn't fully address the issues we have with e-mail rendering, reopening.
