### ISSUE TITLE
Global language statistics are misleading

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#5562]
**Describe the issue**

The global languages statistics are misleading since the translation percent shown is counted when a language has been added in a component. So if you have 3 components and a language added and fully translated in one of the component only, it will be counted as 100% translated while another language translated at 100% for two components but at 50% for the other will only be counted at 75% translated. 

**To Reproduce the issue**

1. Go to https://l10n.xwiki.org/languages/
2. Sort the languages by "Translated"
3. Check that Japanese is first while it concerns only one project

**Expected behavior**

IMO the percentage should be computed by ponderating the number of components where the language exists. Or at least the table in https://l10n.xwiki.org/languages/ should display the total number of translated keys for a language and allows to sort using that column.

**Comment by nijel** [comment]
We used to have that as an additional column with this, but it has proven to be confusing, see https://github.com/WeblateOrg/weblate/issues/2866 and https://github.com/WeblateOrg/weblate/issues/2732.

The missing strings are indicated by the ghost icon on each language.

**Comment by comradekingu** [comment]
@surli Partly the nomenclature "of total" proved difficult. There are no sufficiently short alternatives(?).
Having two sets of bars is also not ideal, considering many use Weblate on their phones.

The only thing that changed since then is the ghost-icons.

I think one bar that has a 100% line short of where the total is makes sense. Click ghost icon to move the line all the way to the right.

**Comment by comradekingu** [comment]
Possible words are "totality" "of existing" "of all avail." "of all" "of source" "Of origin" "sum total"

**Comment by surli** [comment]
> @surli Partly the nomenclature "of total" proved difficult. There are no sufficiently short alternatives(?).

> Possible words are "totality" "of existing" "of all avail." "of all" "of source" "Of origin" "sum total"

Not sure if it would remove  the ambiguity to be honest. Basically the issue is to express: 
  A. the number (or %) of translations performed in a given language, on the total number of strings for this language
  B. the number (or %) of translations performed in a given language, on the total number of source strings

What I'm not sure to understand is why A is more interesting to show by default than B. Especially for sorting languages since the ghost icon is indeed good to display the info but cannot be used for sorting. I guess the answer is because instances like weblate.org are used to translate multiple different projects, while in my case the instance is used to translate a unique project.

As @nijel mentioned in https://github.com/WeblateOrg/weblate/issues/2732#issuecomment-491500058 part of the answer is probably to use the Language consistency plugin for us.

**Comment by nijel** [comment]
In case you want all components translated into all languages, then you really care only about B. On the other side, in case you translate different components into different set of languages, B is useless for you, and you want A because you want to know which languages have completed the translations they need (and some will never reach 100% in B).

Weblate shows A because it has proven to be easier to understand and if you want B, enable the language consistency addon.

**Comment by comradekingu** [comment]
"strings/100%"

**Comment by comradekingu** [comment]
Neverstale
