### ISSUE TITLE
"Make your translations available under a libre license" for CC-BY-SA-4.0

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#5564]
**Describe the issue**

I just got emails for a few repos on hosted.weblate.org saying: "This project does no longer fit into libre hosting conditions.".  There is a red triangle next to "Make your translations available under a libre license.".  All of these projects are under the CC-BY-SA-4.0 license (listed as FSF-approved in SPDX) and have it set in "Basic Settings" -> Translation License.  Some of the git repos have a proper `LICENSE` file, others do not.

Here are the projects in question:
* https://hosted.weblate.org/projects/reproducible-builds/reproducible-website-pages
* https://hosted.weblate.org/projects/reproducible-builds/reproducible-website-docs
* https://hosted.weblate.org/projects/fsfe/reuse-docs/
* https://hosted.weblate.org/projects/fsfe/glossary/
* https://hosted.weblate.org/projects/reproducible-builds/glossary/

**Comment by nijel** [comment]
Argh, seems like SPDX changed the structure of the JSON files, and we're wrongly parsing the libre state...

**Comment by comradekingu** [comment]
@nijel Since when is -ND libre? https://github.com/WeblateOrg/weblate/commit/0ebd9071e4e66884c097706903ea7c7a5c3bfa50#diff-d3d2ebe935ab2e5d4443528aca4cefd89bb99d92068e92cc6a2e421cc4b72967R583
I wish people stopped using the mess that is CC licenses.

>https://www.gnu.org/licenses/license-list.html   Creative Commons Noderivatives, any version (#CC-BY-ND)
This license does not qualify as free, because there are restrictions on distributing modified versions. We recommend you do not use this license for documentation.

**Comment by nijel** [comment]
ND is not libre, you are misreading the diff. I'm not going to discuss the individual licenses here, we rely on SPDX which provides info whether it is considered libre by FSF or approved by OSI. Due to change in the SPDX data some of the flags were not correctly parsed and that has been fixed.
