### ISSUE TITLE
Weblate Internal Server Error

### ISSUE THREAD

**Issue by abode122** [WeblateOrg/weblate#5702]
**Describe the issue**
I keep receiving errors from Weblate in my mail saying "ERROR (EXTERNAL IP) TransactionManagementError
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block."

**I already tried**
I tried to find out what's causing the issue but I didn't succeed in doing that so couldn't try much  to solve it either
Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**Screenshots**
![image](https://user-images.githubusercontent.com/36990813/111871276-1f6ae480-899a-11eb-9c3c-28da476e6e43.png)

Thanks in advance

**Comment by nijel** [comment]
There will be probably one more exception on the error page, can you please post it as well?

**Comment by abode122** [comment]
https://paste.ee/p/MIEyC - Hmm are you referring to this by any chance?

**Comment by nijel** [comment]
There is MySQL erorr 2006, see https://docs.weblate.org/en/latest/admin/install.html#mysql-and-mariadb

**Comment by abode122** [comment]
So I edited that but I still get those errors, also I used to get 2006 errors in my mail but after I added `CONN_MAX_AGE` I don't get 2006 anymore but I still keep getting those kinds of errors, I'll attach some other errors I did get.

![image](https://user-images.githubusercontent.com/36990813/111964459-b0120380-8b05-11eb-8899-701b2163e4b9.png)
![image](https://user-images.githubusercontent.com/36990813/111964471-b2745d80-8b05-11eb-8a6b-c085493547c9.png)
![image](https://user-images.githubusercontent.com/36990813/111964480-b4d6b780-8b05-11eb-8f0b-66bef0580e5a.png)

All those errors happen frequently, I would say like once or twice per day

**Comment by nijel** [comment]
Well, the recommended database server for Weblate is PostgreSQL, so the solution could be to [migrate to PostgreSQL](https://docs.weblate.org/en/latest/admin/upgrade.html#database-migration).

If you want to dig deeper into fixing this, look for MySQL-specific solutions, for example https://bobcares.com/blog/mysql-error-1205-lock-wait-timeout/. The problem here is that many solutions are specific to some MySQL/MariaDB server versions. If you find out what to do with this, we would love to have this described in our documentation.
