### ISSUE TITLE
Can't unmark terminology and forbidden flags

### ISSUE THREAD

**Issue by HaasJona** [WeblateOrg/weblate#5791]
**Describe the issue**

 more or less accidentally marked a glossary item as forbidden and terminology and now I seem to be unable to remove these flags or even remove the glossary term.

**I already tried**

* Deleting the term, but it keeps reappering.
* Clicking on "Mark as terminology" / "Mark as forbidden" again, but the flag keeps set.
* Trying to remove the flags at the english Glossary

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Go to https://hosted.weblate.org/translate/kicad/glossary/de/?checksum=69b55c463455830d
2. Notice terminology and forbidden flags are set
3. Click on Tools ("Werkzeuge" in german)
4. Expect menu items to remove terminology and forbidden flag
5. Clicking on "Mark as Terminology" does nothing

**Expected behavior**
Possible to remove terminology

**Screenshots**

![Bildschirmfoto von 2021-04-02 09-44-18](https://user-images.githubusercontent.com/4310707/113394159-0994f080-9398-11eb-815f-b162feb51bcb.png)

**Comment by nijel** [comment]
The shortcuts in the menu seem indeed broken, you can edit the flags directly in the right sidebar and remove them.

**Comment by HaasJona** [comment]
> you can edit the flags directly in the right sidebar and remove them.

How? The labels there look like readonly text and don't react to clicks, and in the documentation is stated that you can set/remove them in bulk editing mode, which I can't find (maybe not enabled for this project or my user?)

**Comment by nijel** [comment]
Ah, you don't have permissions for that.

**Comment by HaasJona** [comment]
This is only fixed for the terminology flag. Try to open https://hosted.weblate.org/translate/kicad/glossary/de/?checksum=c8fb85f1ce1c4e1d and remove forbidden flag in the tools menu, nothing happens.

**Comment by nijel** [comment]
Good point, that should be fixed in bb92bc75b9.

**Comment by JohnRDOrazio** [comment]
I have a similar problem in a project of mine, I seem to have accidentally added a [term to the glossary](https://translate.johnromanodorazio.com/translate/liturgical-calendar/glossary/la/?checksum=79f2f64497399e8f), which I now can't delete. It seems to be marked as `read-only`, and I have no way of removing the `read-only` flag. When using the `Tools` menu and `delete string`, the string doesn't get deleted. I can't edit the string, because it's `read-only`. And I can't change the `read-only` flag, when I try to edit flags I get a message that says the flag is inherited from Project/Component/Language, funny thing is that is the Project/Component/Language arghhh.

**Comment by nijel** [comment]
Upgrade to 4.10, it should fix the string removal
