### ISSUE TITLE
Do not show all languages of a component to user

### ISSUE THREAD

**Issue by StefanBrand** [WeblateOrg/weblate#6405]
**Describe the issue**

We don't want to overwhelm translators and therefore I tried to limit a group to a language. I followed [the docs to set up a group that only has access to a specified set of languages](https://docs.weblate.org/en/weblate-4.5.2/admin/access.html#custom-permissions-for-languages-components-or-projects). I expected that the users of that group would only see these languages in the list of languages of a component. However, they would still see all languages listed, when they click on a component.

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and this did not achieve what I was trying to do: https://docs.weblate.org/en/weblate-4.5.2/admin/access.html#custom-permissions-for-languages-components-or-projects

**To Reproduce the issue**

1. Follow the configuration steps described [in the docs](https://docs.weblate.org/en/weblate-4.5.2/admin/access.html#custom-permissions-for-languages-components-or-projects)
2. Log-in as user of that newly created group
3. Click on a component
4. User can still see all languages (but can only translate one of them)

**Expected behavior**

Languages are not listed when user clicks on component.

**Server configuration and status**

Weblate installation: HelmRelease 0.4.0

**Comment by nijel** [comment]
Yes, all languages are always visible, the permissions only control who can translate/suggest/....

To avoid overwhelming translators, translator selected languages are shown first in the list.

**Comment by ilocit** [comment]
@StefanBrand 
One way I did use in the past is to create a specific set of permissions in a Role and then build a Group with those permissions and limit this group to certain projects and languages.

Like this:
(Group called e.g. "**Translators wo MT DE**")

![image](https://user-images.githubusercontent.com/26718215/130029355-b7df7751-2c8a-47fd-abe3-bc446180b6d9.png)

But it was a bit heavy on the admin side maintaining all the translators and roles and groups etc. Also this was in versions of weblate before the new User Admin view was introduced. When you use those custom setting (permissions, groups) you won't see the respecitve users in the User section of the respective project. Since I find this view really useful to track who is working on which project, I, at one point, discontinued the use of this (my) model in favor of simplicity and now accept that each translator (1) sees all languages and (2) could theoretically also change strings in a language he or she does not even speak. Not ideal, but .....
