### ISSUE TITLE
Profile shows languages I never contributed to

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#6639]
**Description of the issue**

https://hosted.weblate.org/user/Yaron/

This is my profile page, as you can see, there are many languages other than Hebrew, altough I wish I could speak all of them I'm still unable to do that plus I never contributed to these languages.

**To Reproduce the issue**

Go to my profile and look at the list below, I only translate to Hebrew but there are components in many other languages (I may have fixed some Arabic or Russian but definitely not Persian or Vietnamese).

**Expected behavior**

I would expect to see only components I actually contributed to.

**Screenshots**

![תמונה](https://user-images.githubusercontent.com/406826/136106690-0d4c78a9-e764-450f-9969-9f78a16e6ec4.png)

**Comment by Blueberryy** [comment]
Probably because of recent "internet apocalypse", but you may check and relog in on website

**Comment by nijel** [comment]
Some repository-wide operations were accounted to triggering user - for example when translating a string did trigger a commit in the repository, it would commit all pending strings and those operations would be accounted to the current user in all languages.

This was fixed in 674288ae0e8043d1112974f00f7de9b7ebdd6f5f
