### ISSUE TITLE
Support for Gitea Pull Requests

### ISSUE THREAD

**Issue by strk** [WeblateOrg/weblate#7099]
### Describe the problem

Pull requests are currently only supported against GitHub and GitLab, we'd like to use them against Gitea instead.

### Describe the solution you'd like

Add support fir Gitea pull requests.
Here's the API documentation: https://try.gitea.io/api/swagger#/repository/repoCreatePullRequest

**Comment by strk** [comment]
Here's the documentation for the HTTP API of Gitea: https://try.gitea.io/api/swagger
I gave a look at the GitMergeRequestBase class but I'm confused by the fact that Weblate confuses VCS with "Code Hosting" (ie: letting you choose between GitHub and Git as the `VCS`). I think for hosting a different set of configurations would be needed (like: where's the API URL ? What are the credentials... )

**Comment by nijel** [comment]
Historically, the implementation was done this way. The reason is that you need to change the VCS behavior to integrate with the code hosting site (for example, push to fork instead of pushing to original repo).

The API URL is generated from the VCS URL:

https://github.com/WeblateOrg/weblate/blob/833ead37f414dbba99a21b0ebe9606d42dd9cd45/weblate/vcs/git.py#L698-L732

It is customized per code hosting site:

https://github.com/WeblateOrg/weblate/blob/833ead37f414dbba99a21b0ebe9606d42dd9cd45/weblate/vcs/git.py#L839-L846

The credentials are stored in the settings GITHUB_CREDENTIALS / GITLAB_CREDENTIALS / PAGURE_CREDENTIALS.
