### ISSUE TITLE
Use zh_CN/zh_TW/zh_HK/zh_SG instead of zh_Hans/zh_Hant for Chinese language code

### ISSUE THREAD

**Issue by lumingzh** [WeblateOrg/weblate#7437]
### Describe the problem

The apps using zh_Hans from weblate can't display Chinese UI on GNOME, not test other desktop environment. [Collision](https://github.com/GeopJr/Collision/issues/58) changed from zh_Hans to zh_CN and works normal now.

### Describe the solution you'd like

Use zh_CN/zh_TW/zh_HK/zh_SG for Chinese.

### Additional context

OS: Fedora Silverblue 35
DE: Gnome Shell 41
APP: Installed from flathub as flatpak

**Comment by nijel** [comment]
There is no one solution that would fit all use cases. That's why there is [Language code style](https://docs.weblate.org/en/latest/admin/projects.html#language-code-style), see [Adding new translations](https://docs.weblate.org/en/latest/admin/languages.html#adding-new-translations) for more info. What might make sense is to add another option there that would cover POSIX style identifiers with legacy codes for Chinese.

**Comment by sonnyp** [comment]
@nijel is this something "Linux" could fix on their side? Like fallback to `zh_CN` for `zh_Hans` and vice versa ?

Where would that be - glibc?

**Comment by nijel** [comment]
This is just about naming of translation files created in Weblate. Once the file exists, Weblate doesn't care whether it is called `zh_CN` or `zh_Hans`.

**Comment by sonnyp** [comment]
I understand. I meant fixing on a higher level – where Weblate is not involved. 

I guess I'm looking for the right place to file a feature request so that this doesn't happen in the first place because the Linux understands that zh_CN = zh_Hans and so on.

**Comment by nijel** [comment]
Ah, that might be indeed in glibc.

**Comment by sonnyp** [comment]
For the record and in case someone is interested in picking this up,  Fedora already requested this from glibc and the developers basically said "yes but tricky”, which I understand as "ok if someone is willing to put the effort into it".

https://sourceware.org/legacy-ml/libc-alpha/2019-10/msg00358.html
