### ISSUE TITLE
Ability to flag canonical texts for review

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#756]
Occasionally during translator we wil notice that the original text is bad. If that happens I would like to have a very simple way for a translator to flag that message, and optionally add a (translator) comment to it. 
##

**Comment by mrogero** [comment]
Dear Weblate,

There are two types of changes happening during translation review - 1) the new text is being created and reviewed  2) the original text is being improved upon.

In the situation of a translator finding that the original has errors, they would create an improved string, which should trigger a review of the original and all the other languages which depend on it.

In our case we have Dutch / English / German / Japanese.  The Japanese translator finds that the original sentence (assume English) has an error in logic and creates a better Japanese sentence and drops a comment with an improved English one.  What they need is a check box to "review original text" so that the system can identify this text and the German and Dutch translators know that they need to update their translations.   

There is nothing to trigger this review.

**Comment by nijel** [comment]
With monolingual translation, it's already possible to directly edit the string.

As for review flag, I'm not sure if that's needed, IMHO ability to add comment is way better as that will also indicate what is wrong (what might not be obvious) and this feature is already there. Also with setting ``Source string bug report address`` in component settings you will automatically get such comments there.
