### ISSUE TITLE
Define state of the unit on create via API

### ISSUE THREAD

**Issue by antonkomarev** [WeblateOrg/weblate#7601]
### Describe the problem

It would be greate to have a way to define state of the unit on creation via an API.
If we will do it in 2 steps (1 — create unit, 2 — patch unit state), there may be an issue with data consistency. For example 1st request is done, but on second there will be network issue, or requester server has died unexpectedly.

`POST /api/translations/(string: project)/(string: component)/(string: language)/units/`
```json
{
    "key": "example_key",
    "value": ["Example translation"]
}
```

### Describe the solution you'd like

`POST /api/translations/(string: project)/(string: component)/(string: language)/units/`
```json
{
    "key": "example_key",
    "value": ["Example translation"],
    "state": 10 // Needs editing
}
```

**Comment by scott-gorman** [comment]
Hey, i'd like to work on this!

**Comment by nijel** [comment]
You are welcome. In case you need any guidance don't hesitate to ask.

**Comment by antonkomarev** [comment]
@scott-gorman any progress on it?

**Comment by rhofer** [comment]
@nijel with my example described in https://github.com/WeblateOrg/weblate/issues/7601#issuecomment-1316610725 above, this only addresses "meta data" as the state. But when doing such operations as mentioned, it would be good to act on further "meta data" as `suggestions` and `comments` , so that potentially API would allow to act on them as well.

Would this fit to this issue or shall I write a new one?

**Comment by nijel** [comment]
@rhofer  Please open separate issue for each of these.

**Comment by antonkomarev** [comment]
@nijel thank you!
