### ISSUE TITLE
Separate `docs/locales` and `weblate/locale` into a submodule/dependency

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7707]
### Describe the problem

* I'd say currently git history of this repo is not as usable as it could be if the translations weren't there. For example, looking at `git log` without any directory filters barely makes sense because ~80%+ of the commits are translations.
* The repo takes a lot of disk space because of all the history
* Even programmatic history search (e.g. `git log -S"|safe"` takes a long time.

### Describe the solution you'd like

1. Separate `docs/locales` and `weblate/locale` into submodules. They can be kept as a branch in the same repo.
2. (optionally) run `git filter branch` to clean up the history of the repo (we can keep the old history in a tag or a branch), like [here](https://stackoverflow.com/questions/12514197/convert-a-git-folder-to-a-submodule-retrospectively/12515629#12515629) (or [here](https://stackoverflow.com/questions/17413493/create-a-submodule-repository-from-a-folder-and-keep-its-git-commit-history))

For example, [the Tor Project does this](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake-webext/-/blob/07742beb2779d9d05646f1849495a14bda724664/.gitmodules). Also [myself](https://github.com/WofWca/jumpcutter/blob/81b4e507b68d9f7c50e90161326edc65038ae28c/.gitmodules).

Possible issues with this:
* Workflow may become a little obstructed. For example, if you want to make a source code change that also requires changing a source string, you'd have to do two separate commits in two separate branches. It's not super common though, I'd say. And I think it can go away with practice. Or scripts. Or both.
* https://github.com/WeblateOrg/weblate/issues/4139
* For people who have starred and/or forked the repo, their translations will stop displaying as contributions on their profile unless there is another repo with the translations branch as the default one, and these people have starred or forked that repo. See https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits
* Maybe something else I've missed because I don't work with this repo a lot.

### Describe alternatives you've considered

Make a section somewhere that shows useful git options (and maybe other tricks) that help with this (e.g. `git log -- ':!*locale*'`, which excludes paths containing `locale`).

**Comment by nijel** [comment]
I don't like using submodules in this. It would break many things which currently do work (for example, `pip install https://github.com/WeblateOrg/weblate/archive/main.zip` would no longer include locales).

> The repo takes a lot of disk space because of all the history

Moving locales to a different branch will not have an effect on the repository size - it would still be in the same repository.

I've been recently discussing repo size with GitHub support, and the conclusion is that repo takes a lot of disk space because of rebasing when merging the pull requests. This produces nicer history, but has a side effect that GitHub stores both original branch and rebased in the repository objects. You can get rid of that by using `git gc --aggressive` locally, but GitHub will always include these objects as they need them on their side. Moving out locales would remove only a small portion of this, same applies to code changes and dependency updates...
