### ISSUE TITLE
Markdown syntax check failed when there is `_something_` in the translated strings in Chinese

### ISSUE THREAD

**Issue by linsui** [WeblateOrg/weblate#7751]
### Describe the issue

Every translated string with `_something_` in Chinese gets `Markdown syntax` error. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

See https://hosted.weblate.org/translate/f-droid/website-posts/zh_Hans/?q=has%3Adismissed-check&offset=18 as an example.

### Expected behavior

No checking error.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Because it is not a valid markdown, it needs to have space around `_`. Taking https://hosted.weblate.org/translate/f-droid/website-posts/zh_Hans/?checksum=1aa1a619b8e071dd as an example.

The current text:

```
如果你安装了F-Droid 客户端 alpha2 _并且_正在使用[特权扩展](https://gitlab.com/fdroid/privileged-extension/#f-droid-privileged-extension)，你需要启用未知来源，以便能够升级。（之后你可以再把它关掉。）
```

This is how it is rendered - the underscore characters are used as literals:

如果你安装了F-Droid 客户端 alpha2 _并且_正在使用[特权扩展](https://gitlab.com/fdroid/privileged-extension/#f-droid-privileged-extension)，你需要启用未知来源，以便能够升级。（之后你可以再把它关掉。）

When adding spaces around `_`, it is properly rendered as italics:


如果你安装了F-Droid 客户端 alpha2 _并且_ 正在使用[特权扩展](https://gitlab.com/fdroid/privileged-extension/#f-droid-privileged-extension)，你需要启用未知来源，以便能够升级。（之后你可以再把它关掉。）

**Comment by linsui** [comment]
Thanks! You're right!
