### ISSUE TITLE
Make approved translations string editable

### ISSUE THREAD

**Issue by yangyangdaji** [WeblateOrg/weblate#8196]
### Describe the problem

As proposed at https://github.com/GradienceTeam/Gradience/pull/616#issuecomment-1272144043
When an Incorrect is found in the translation string of an annotation. It can be changed at any time. Instead of changing the translation source file
![Screenshot_20221008_184401](https://user-images.githubusercontent.com/108261729/194703623-570e9c7b-fe01-46f4-bac5-3bbf81be9d35.jpg)

![Screenshot_20221008_065409_edit_1522055337267](https://user-images.githubusercontent.com/108261729/194673345-5ac33087-7c5f-4cfa-96f2-8749437e7ff5.jpg)

### Describe the solution you'd like

Make approved translations string editable

**Comment by Geeyun-JY3** [comment]
No. Making translations uneditable is what approved translation is for.
The issue here is why these translations are approved when they are shown as `Translated` in the `History` tab.
![image](https://user-images.githubusercontent.com/49396421/194740391-b7b3996d-e9f7-4e8e-a295-6df295d2107a.png)

And I think you should ask the project maintainer whether some configurations about the review workflow are set.

**Comment by yangyangdaji** [comment]
ok

**Comment by yangyangdaji** [comment]
Replaced by https://github.com/WeblateOrg/weblate/issues/8196

**Comment by yangyangdaji** [comment]
Replaced by https://github.com/WeblateOrg/weblate/issues/8198
