### ISSUE TITLE
Extend glossary with forbidden terms

### ISSUE THREAD

**Issue by danielnaber** [WeblateOrg/weblate#846]
Example: One might add `folder` and its translation to the glossary. Often, this implies that `folder` should be used, and not a synonym like `directory`. These forbidden terms could be specified as a regular expression (e.g. `director(y|ies)`) and there could be a check which makes sure the forbidden words are not used.
##

**Comment by fastestnoob** [comment]
... or glossary just gives a message which says "you used another word for existing glossary term. are you sure?"

**Comment by comradekingu** [comment]
http://www.korrekturavdelingen.no/vanlige-skrivefeil_a.htm has a list of the words that most often end up being wrong, and the corresponding mistakes that pop up. It would be nice to set up a relational search for those.

Our Norwegian Bokmål glossary has entries accompanied by illegal and shunned variants  http://i18n.skulelinux.no/nb/Fellesordl.eng-no.html

If you see a ~~strike-through~~ word in the editor, it should serve as a reminder that the word is not to be used :)

**Comment by nijel** [comment]
I'm not sure using regexp is a good idea. The regexp experience so far is that it's a powerful feature, which many users are afraid and thus won't use.

Scope of this feature:

* Add flag for glossary terms that this is a prohibited term
* Add check looking at translation whether it contains one of these

Possible future extension:

* Once we have rich editor, the forbidden terms could be highlighted there

**Comment by comradekingu** [comment]
I meant as an automated check. Write a word that doesn't exist, and it pops up asking you to fix it.
Not everyone has a spellchecker it seems.

If the dictionary really is a database of single word strings and the type of word they are, it can be used to auto-translate and ensure consistency, with actually good results. Also it would make sense to work on the dictionary then, because it would be useful for the whole instance, and highlight missing words.

Right now I have a basic idea of what words are used in what projects, but it doesn't scale, and the info does not populate well between translators. So either you have some consistency with one major translator (and consequently as consistent errors, or you have scaling towards but ultimately away from consistency.

Consequently, the way to start it is to take the entire translation memory of single word strings, sort it by frequency, and start weeding out the errors.

The problem with the regexp is there is no overview of what the available terms are. https://github.com/WeblateOrg/weblate/issues/4541

**Comment by nijel** [comment]
@comradekingu Spell checker is option as well (see https://github.com/WeblateOrg/weblate/issues/443 or https://github.com/WeblateOrg/weblate/issues/977), but this issue is about prohibiting certain words. Typical example could be folder / dictionary mentioned in the initial post.
