### ISSUE TITLE
validate po file before commit/push

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#875]
Weblate checks po files for some errors, reports them to the user, but it allows to ignore some of them.

If would be nice to mark checks that cause error in "msgfmt -c" as fatal, both in web interface and file upload.

Otherwise translator can easily break automated build process of the package.

Developer then must solve it in a way that is not friendly to thanslators: e. g. remove the file from the GIT repository.
##

**Comment by stanislav-brabec** [comment]
Here is an example of such error:
https://github.com/openSUSE/libstorage/blob/7e556675fcdd0c88a28f51ef3d159e278c0d00ed/po/lt.po

Translator translated %2$s as %2$X and Weblate pushed broken translation.

**Comment by matejcik** [comment]
would it be helpful (or sufficient), for the first step, to display a list of failing checks next to the "push" button?

**Comment by scarabeusiv** [comment]
As a starter it might be good. But overall it needs to not allow the push if those checks fail ever.
On that note it should not allow the upload either. So if  you upload .po file the checks should be fatal too.

**Comment by scarabeusiv** [comment]
I would guess as a check it would be good start. We still need to disallow the push if those checks fail.

Also the same apply for uploading .po file. If there are bugs, the update should be discarded.

**Comment by aplanas** [comment]
AFAIS there are three elements in this issue:

1. Add an extra `msgfmt -c` check (some `weblate.trans.checks.format.MsgFmtCheck` class, disabled by default
2. Detect the placeholder bug (`%2$s` as `%2$X`)
3. Disable push if the PO still contains errors where `severity == 'danger'`

The feature in 2. looks like that is currently implemented in one of the `XXXFormatCheck` class, and is working in my local examples.

The feature 1 is a bit dangerous: on one side there is overlapping with 2, and `msgfmt -c` do not usually categorize the errors, even enumerate the total number of fatal errors. I guess that this can be fixed with some heuristics. Not sure that to do with the overlapping cases.

3 can make sense, but again we have 2, we forbid the push / upload from errors in the local checkers, or only for the ones found in msgfmt?

**Comment by aplanas** [comment]
After meeting: the critical part is to avoid commits that are critical, not using the `msgfmt -c` check

**Comment by stanislav-brabec** [comment]
aplanas: Exactly: Never allow to even commit broken translation that does not pass "msgfmt -c" check.

Once committed, it would be automatically pushed with the next commit (e. g. another language).

Even better would be identifying of all format checks that are considered as critical, so the user will see immediately that the translation is not valid and will not be pushed until the error is fixed.

I guess that Weblate check set is a superset of msgfmt checks. If not, new Weblate checks could be created.
