### ISSUE TITLE
Translation file for language contains 2 forms of plurals, whereas the language configuration contains only 1

### ISSUE THREAD

**Issue by dumiale** [WeblateOrg/weblate#8794]
### Describe the issue

Within one of our projects, the Spanish language contains 2 forms of plural (many & other), whereas the language is configured to have only one (other).

How can this be resolved so that only one form of plural is present, just like the language is configured?

![image](https://user-images.githubusercontent.com/125260216/218439487-2feef59b-f275-46bc-ac4b-e36b626c8c30.png)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

The translation file for that language should contain the plural configured for that language

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Spanish is supposed to have both since CLDR 38, see https://github.com/WeblateOrg/weblate/issues/7888. Support for this is evolving in Weblate, most parts landed in 109fac021f1.

**Comment by dumiale** [comment]
Hi @nijel, thank you for responding to this. Does that mean we should expect this to see in all other projects? I was confused because this was reported only in one project

**Comment by nijel** [comment]
Yes, it should be everywhere eventually.

**Comment by dumiale** [comment]
@nijel Thank you, we can now see the CLDR 38 plurals in Weblate, so this is fine. Can you please advise on how to use those instead of the default ones for existing components?

**Comment by klaytoncavalcante** [comment]
I have the same kind of issue.

Using the version 4.16.2, when I import translations using the format "i18next JSON file v4", the translations that have a "_zero" plural form are removed.

Example:
![image](https://user-images.githubusercontent.com/4523040/228934191-3b745707-5ba9-4941-8147-abf0f4db255c.png)

Those are totally valid plural forms, but for some reason when using Weblate they are being removed, as Weblate only displays:
- In English, the "Singular" and "Plural" fields
![image](https://user-images.githubusercontent.com/4523040/228935743-a5c69014-5355-44c8-b9e1-5dbfc9e2865e.png)

- In other languages (in my case, Spanish, Portuguese, French and Canadian French), the "One", "Many" and "Other" fields.
![image](https://user-images.githubusercontent.com/4523040/228935799-5f31212f-bb01-474c-9044-036db4c9932f.png)

It would be nice to see the plural forms I have, instead of just deleting them. The way it is right now, it works more like an enforced plural, that may not fit all use cases.
