### ISSUE TITLE
Users should not be able to add entries to other languages' glossaries by default

### ISSUE THREAD

**Issue by tjhietala** [WeblateOrg/weblate#8807]
### Describe the problem

Currently, if a user has the rights to add a glossary entry, they can add it for every language by checking the "Terminology" check box. I don't think this is good default behaviour for Weblate. Yes, the unneeded entries can be deleted, but it's an unnecessary annoyance.

### Describe the solution you'd like

The "Terminology" check box should be disabled by default, except for managers (or possibly also reviewers, if deemed necessary).

**Comment by comradekingu** [comment]
Has this ever been a problem?

**Comment by tjhietala** [comment]
@comradekingu Yes, on The Document Foundations's Weblate this happens every now and then. I just deleted some unwanted entries yesterday. It's not a huge problem though, but IMO what I propose would be a better default.

**Comment by comradekingu** [comment]
@tjhetala Pretty sure I am one of the people doing it for the source language.
The idea that users can't edit all languages has cost the TDF Weblate dearly.

Similarly, between good entries and bad entries in the glossary, the benefit greatly outweighs the detriment.
If you really wanted to do some damage, resetting all of them would be it.
In so doing, better functionality in resetting bulk changes or per-user changes for a given timeframe would be better.
Banning people instead of limiting functionality is also a better idea. In time there is vested interest and a purified pool.
TDF Weblate is hard to get into, and much harder still to get any changes made upstream in.
It would be wise to not model default functionality on the TDF Weblate.

**Comment by timothyqiu** [comment]
There are two situations that could be a problem.

First, some glossaries only make sense in a specific language.

For example, German users might create two glossaries for "lion", one for the male version "der Löwe" and one for the female version "die Löwin". This does not make sense for languages that don't have such grammatical gender.

Second, "Auto-adjust context when an identical string already exists." is on by default too. So I regularly see different versions of the same string with auto-generated context like "1". That's is so frustrating to maintain. I guess it's because some languages created a non-terminology glossary.

**Comment by tjhietala** [comment]
Apparently it's currently also possible to add the "forbidden" flag to other languages' glossaries by default, see: https://translations.documentfoundation.org/translate/libo_ui-master/glossary/fi/?checksum=6a157b0604755bd8

IMO this should not be allowed by default either.

**Comment by tjhietala** [comment]
@comradekingu I don't see how banning users would be preferable over setting good defaults. I think the people doing these changes are by and large doing it by accident, i.e. they don't know they're affecting other languages' glossaries.

**Comment by comradekingu** [comment]
@tjhietala **I disagree that limiting potential for getting work done is a good default for preventing harm.**
For how often malice occurs, it is exceedingly rare compared to the upside of just having stuff done well, or in a well-meaning manner.
There are no easy ways to r**evert changes from a particular user over a given time-period are lacking for every possible type of change.**
It is already possible to fine-tune what permissions different groups of users have.
Are we trying to find something that works for Hosted, or are we trying to shoot everyone in the foot because
people with special needs can and do run their own instance?

Weblate is IMO a better platform because of default openness and good functionality to deal with that,
and I like the one-big-stick method of dealing with the few problems that occur.
**The alternative**, as demonstrated by platforms that suck, is a bunch of authority-by-role, built on the idea that assignable blame is a good way to organize. It is a trashy way to mitigate functionality that doesn't work.
First-come basis is not a measure of quality, as the better translators often arrive later.
The task of picking a team of people with more editing rights is the same premise as being able to do all the work yourself in every language. I have never seen it done well.
Over time one may end up with a good team, and I pretty much know who to trust for most languages now.
I still don't, and people making their first project _especially_ don't.

**If the problem arises from it being difficult to gauge what dictionary the user is editing** and why, that is the problem to solve. Having the same problem for fewer users is largely the same problem.
I care about correctness over time.

If malice is what I want to do, changing the glossaries when the translations are wide open without quality-reaffirming tools is not what anyone clever enough to do real damage would attempt.

Where are the examples of what went wrong, and maybe we can work from there to avoid the confusion?

**Comment by tjhietala** [comment]
@comradekingu I don't think there's any malice involved. Like I said, my guess would be that these users think they're modifying the glossary for one language and don't realise they're doing it for other languages as well.

**Comment by timothyqiu** [comment]
Based on my experience using Weblate, I believe exposing the Terminology flag to regular users has caused a lot of management difficulties.

Different languages often have varying rules regarding which phrases should be included in the glossary. A phrase considered a term in one language may not hold the same status in another language, making it unwise to delegate decision-making power to users of different languages.
