### ISSUE TITLE
gettext error for translations that do not also end with \n (or have a newline when they should not)

### ISSUE THREAD

**Issue by smoe** [WeblateOrg/weblate#8966]
BAJ kindly requested to transform a customer care ticket to a GitHub issue:

Hello,
When the original was initially correctly translated with a terminal \n but in a revision loses that, then the translation needs to be updated accordingly. Just that small reddish square at the end is easily overlooked and then we get errors like these:
```
po/gmoccapy/tr.po:416: 'msgid' and 'msgstr' entries do not both end with '\n'
po/gmoccapy/tr.po:420: 'msgid' and 'msgstr' entries do not both end with '\n'
po/gmoccapy/tr.po:545: 'msgid' and 'msgstr' entries do not both end with '\n'
po/gmoccapy/tr.po:588: 'msgid' and 'msgstr' entries do not both end with '\n'
```
This happens more easily and more frequently than one may think. To spot the entry causing the trouble, one needs to check that file and then search for the text in weblate. Could you instead please find these instances and have these forced as fuzzy?

Just a comment since this was not clear to the other admins of our project (LinuxCNC): This error is related but not identical to the "number of lines not matching" check. Also, a different number of lines would be tolerated by gettext, but this one is not.

Many thanks!

**Comment by nijel** [comment]
* Such a string would fail the “Trailing newline” check, if you would not add `ignore-end-newline` flag to a component configuration.
* When having the check in place, you can also make it enforced via https://docs.weblate.org/en/latest/admin/projects.html#enforced-checks. It will then make failing strings fuzzy.
* This string would be automatically fixed by Weblate when editing if you would not turn that off via `ignore-end-space` flag.
