### ISSUE TITLE
Automatic translation support adding translation as "approved"

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#9048]
### Describe the problem

Following ticket https://github.com/WeblateOrg/weblate/issues/8979, I would like to have an option to set the automatically translated strings as "for review".   This will correspond with the "for review" workflow.

### Describe the solution you'd like

Add an option "Add as for review" to Automatic translation mode of the add-on set-up.

**Comment by nijel** [comment]
The strings should be added as “for review” right now. I thought you wanted to have the possibility to add strings as “approved”.

**Comment by KadAnna** [comment]
I just tried tool Automatic translation. There the Automatic translation mode Add as translation (together with Enabled reviews Setting) sets strings as for review. So it this is the same at the addon Automatic translation, then this ticket is unnecessary. Just that because of the bug https://github.com/WeblateOrg/weblate/issues/8979 I could not see it.

**Comment by nijel** [comment]
I still think it makes sense to add an option to add string as approved, so let's keep this issue open.

**Comment by nijel** [comment]
To implement this:

* `AutoForm` needs to extend `__init__` so that it adds `Add as approved` when reviews are enabled:

  https://github.com/WeblateOrg/weblate/blob/18f85422e98e2d3ea0960093c647ea59fef09371/weblate/trans/forms.py#L906

* `AutoTranslate` needs support for `mode` = `approved`, at leas here:
 
  https://github.com/WeblateOrg/weblate/blob/18f85422e98e2d3ea0960093c647ea59fef09371/weblate/trans/autotranslate.py#L34

**Comment by Krishhhnaa** [comment]
is this issue closed ?

**Comment by nijel** [comment]
No, it is open.
