### ISSUE TITLE
Openshift deployment instructions led me to installing git-tip

### ISSUE THREAD

**Issue by jirkadanek** [WeblateOrg/weblate#920]
I was following the instructions at https://docs.weblate.org/en/weblate-2.4/admin/deployments.html
1. Install Weblate with
   
   rhc -aweblate app create -t python-2.7 -t postgresql-9.2 --from-code https://github.com/nijel/weblate.git --no-git
2. add Cron cartridge
3. wait for Weblate to finish installing
4. open https://weblate-krno.rhcloud.com/
5. click "Documentation"
6. this opens https://docs.weblate.org/en/weblate-2.5/index.html which is a 404 error page.

I'd expect 1) that the example installation command installs the release being documented or possibly the most recent release, not git-tip 2) that the Documentation link in git-tip links to https://weblate.readthedocs.org/en/latest. 
##

**Comment by nijel** [comment]
I've created separate issue for the doc link (#921). 

As for installing current master, it should be more or less fine (it should be production ready and it's used on https://hosted.weblate.org/ as well).

However I have no clue what are generic expectations on Openshift, maybe @dtschan  or @paulpach  can comment on this?

**Comment by dtschan** [comment]
There are no technical reasons speaking against deploying the master head to OpenShift. However the Tracis CI tests currently don't test against OpenShift because as of now the password of the OpenShift account used for the tests would have to be checked into git. So the master branch may contain OpenShift related issues which have not been detected and fixed yet that are not present in the latest release. On the other side I run my own integration tests against master and OpenShift related issues are quite rare.

Originally the links in the documentation pointed to the latest release. However this has been changed in commit 213a5648995db593fa0b9779031285f4c6d43a9c, probably because this lead to incorrect links in the master head documentation.

**Comment by nijel** [comment]
The password can be passed as Travis secret variable, which is not exposed, so this is not a problem (we currently use this for Sauce Labs testing). So running tests would be quite easily possible...

As for the links, now I recall - the reason was that it was yet another place to update version information on release...

**Comment by dtschan** [comment]
Interesting, reading https://docs.travis-ci.com/user/deployment/openshift/ I assumed this not to be possible. I'll look into it when OpenShift Online based on the new Docker-based OpenShift 3 becomes available, shouldn't be too long now.

As for the links: Actually I used |version| in the links for this very reason. However this did not work everywhere. Another solution to refer to the latest release in the documentation would be to introduce a git tag like "latest" which always points to the latest release. Depending on the release process this could be automated. On the other hand the documentation already describes how to find the latest release manually.

**Comment by nijel** [comment]
But using |version| is problematic as well - in documentation for master it points to not yet existing tag :-). Having latest tag might solve this indeed...
