### ISSUE TITLE
Easier issue templates

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9477]
### Describe the problem

The templates are to restrictive.

e.g. Feature Requests do have a problem- and solution-field which are nearly useless in the context of a feature.

### Describe the solution you'd like

- no templates
- or templates with simple strings describing what you want. Bot now text fields with red wildcards.
- "screenhots" field is useless because of its location. Screenshots often better placed in context of the problem description.

**Comment by nijel** [comment]
Maybe the fields could be called differently, but we really need both of them. First is there for the user to describe what he is trying to solve (the problem), second how he would like to solve that (the solution). We really want people to think about both when filing the issue so that we have some kind of specification. Otherwise, we end up asking for that info in a follow-up questions.

**Comment by buhtz** [comment]
But the user is not dump and this is not kindergarden, except the exceptions. 😄 
What I have in mind is [something like this](https://github.com/bit-team/backintime/issues/new) makeing the user feel more free and not patronized.

This formula like layout do help no one. It make reporters feel treated like childs and it drive contributors away.

How long do you use it? Would you really say this increase the quality of issues reported?

**Comment by nijel** [comment]
> But the user is not dump and this is not kindergarden, except the exceptions. :smile:

Unfortunately, we saw numerous poorly reported issues before introducing this.

We use it since 2021. Before we had free form with guidance text as you link and that caused people to leave the template text there or mess up with that somehow. With forms, the formatting is not up to the user, so it's less likely to break.

**Comment by buhtz** [comment]
Thanks for sharing your experience as a maintainer. I'll take this into account in my own projects.

**Comment by nijel** [comment]
This really depends on the audience. In the beginning, where most people using Weblate were experienced developers, reporting issues didn't need much guidance. These days, when most of the reports come from inexperienced users, guidance is necessary because they have no clue what info is needed in a useful bug/feature report.
