### ISSUE TITLE
Tab behavior is not accessible on page to add new string 

### ISSUE THREAD

**Issue by Solene-Garda-Krebs** [WeblateOrg/weblate#9481]
### Describe the issue

On the page to add a translation string, the behavior when using tab is does not match what is expected.
Starting with the focus on the _Translation key_ input, focus goes to:
1. Language (ex: French) input
1. Menu items
1. Insert buttons for language input
1. Add button
1. Footer links

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the add new template page
1. Clic on _translation string_ input
1. Use the tab key (several times)

### Expected behavior

Order of focused items when using tab:

1. Translation key input
1. Language (ex: French) input
1. (Optionnal) Insert buttons for language input
1. Add button
1. Footer links
1. Menu items

### Screenshots

![Screenshot from 2023-06-29 14-23-11](https://github.com/WeblateOrg/weblate/assets/100767045/4f2f8757-83d1-43ed-ad36-da6372ea6f7f)

### How do you run Weblate?

weblate.org service

**Comment by harriebird** [comment]
Hi guys, check my PR #11952 for this issue.

**Comment by nijel** [comment]
@harriebird I don't think the issue is in lack of `tabindex` for all other elements, but rather in not working `tabindex` on the fields in the form. The very same happens when translating string with plural:

1. Click on the singular field (it has `tabindex="100"`).
2. Press `<tab>`
3. You end up on visual keyboard button which has no `tabindex`
4. Press `<tab>` more 
5. You end up on the plural field (it has `tabindex="101"`).
